// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package resources

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	wrtfoundation "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// IKnownResourceQualifierNameStatics is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IKnownResourceQualifierNameStatics.
// IID: dd6cdedc-559b-50c8-ac53-82fe21f915f3
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.KnownResourceQualifierName runtime class.
type IKnownResourceQualifierNameStatics struct {
	syswinrt.IInspectable
}

// IID_IKnownResourceQualifierNameStatics is the interface identifier for IKnownResourceQualifierNameStatics.
var IID_IKnownResourceQualifierNameStatics = win32.GUID{Data1: 0xdd6cdedc, Data2: 0x559b, Data3: 0x50c8, Data4: [8]byte{0xac, 0x53, 0x82, 0xfe, 0x21, 0xf9, 0x15, 0xf3}}

// Contrast (propget get_Contrast) dispatches through IKnownResourceQualifierNameStatics's vtable slot 6.
func (self *IKnownResourceQualifierNameStatics) Contrast() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Custom (propget get_Custom) dispatches through IKnownResourceQualifierNameStatics's vtable slot 7.
func (self *IKnownResourceQualifierNameStatics) Custom() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// DeviceFamily (propget get_DeviceFamily) dispatches through IKnownResourceQualifierNameStatics's vtable slot 8.
func (self *IKnownResourceQualifierNameStatics) DeviceFamily() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// HomeRegion (propget get_HomeRegion) dispatches through IKnownResourceQualifierNameStatics's vtable slot 9.
func (self *IKnownResourceQualifierNameStatics) HomeRegion() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Language (propget get_Language) dispatches through IKnownResourceQualifierNameStatics's vtable slot 10.
func (self *IKnownResourceQualifierNameStatics) Language() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// LayoutDirection (propget get_LayoutDirection) dispatches through IKnownResourceQualifierNameStatics's vtable slot 11.
func (self *IKnownResourceQualifierNameStatics) LayoutDirection() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Scale (propget get_Scale) dispatches through IKnownResourceQualifierNameStatics's vtable slot 12.
func (self *IKnownResourceQualifierNameStatics) Scale() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// TargetSize (propget get_TargetSize) dispatches through IKnownResourceQualifierNameStatics's vtable slot 13.
func (self *IKnownResourceQualifierNameStatics) TargetSize() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Theme (propget get_Theme) dispatches through IKnownResourceQualifierNameStatics's vtable slot 14.
func (self *IKnownResourceQualifierNameStatics) Theme() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IResourceCandidate is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceCandidate.
// IID: 6c54bc0c-ef1e-57b8-b478-34fece737356
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceCandidate runtime class.
type IResourceCandidate struct {
	syswinrt.IInspectable
}

// IID_IResourceCandidate is the interface identifier for IResourceCandidate.
var IID_IResourceCandidate = win32.GUID{Data1: 0x6c54bc0c, Data2: 0xef1e, Data3: 0x57b8, Data4: [8]byte{0xb4, 0x78, 0x34, 0xfe, 0xce, 0x73, 0x73, 0x56}}

// ValueAsString (propget get_ValueAsString) dispatches through IResourceCandidate's vtable slot 6.
func (self *IResourceCandidate) ValueAsString() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// slot 7: get_ValueAsBytes skipped: conformant array

// Kind (propget get_Kind) dispatches through IResourceCandidate's vtable slot 8.
func (self *IResourceCandidate) Kind() (ResourceCandidateKind, error) {
	result := new(ResourceCandidateKind)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// QualifierValues (propget get_QualifierValues) dispatches through IResourceCandidate's vtable slot 9.
func (self *IResourceCandidate) QualifierValues() (*IMapViewOfStringAndString, error) {
	result := new(*IMapViewOfStringAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IResourceCandidateFactory is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceCandidateFactory.
// IID: bb2b30f8-c19b-5f43-88d9-69ad728a32f4
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceCandidate runtime class.
type IResourceCandidateFactory struct {
	syswinrt.IInspectable
}

// IID_IResourceCandidateFactory is the interface identifier for IResourceCandidateFactory.
var IID_IResourceCandidateFactory = win32.GUID{Data1: 0xbb2b30f8, Data2: 0xc19b, Data3: 0x5f43, Data4: [8]byte{0x88, 0xd9, 0x69, 0xad, 0x72, 0x8a, 0x32, 0xf4}}

// CreateInstance dispatches through IResourceCandidateFactory's vtable slot 6.
func (self *IResourceCandidateFactory) CreateInstance(kind ResourceCandidateKind, data string) (*IResourceCandidate, error) {
	hData, err := winrt.NewHString(data)
	if err != nil {
		return nil, err
	}
	defer hData.Close()
	result := new(*IResourceCandidate)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(kind), uintptr(hData.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// slot 7: CreateInstance2 skipped: conformant array

// IResourceContext is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceContext.
// IID: 96fb48dc-f77d-55ff-af12-34861e3d4939
type IResourceContext struct {
	syswinrt.IInspectable
}

// IID_IResourceContext is the interface identifier for IResourceContext.
var IID_IResourceContext = win32.GUID{Data1: 0x96fb48dc, Data2: 0xf77d, Data3: 0x55ff, Data4: [8]byte{0xaf, 0x12, 0x34, 0x86, 0x1e, 0x3d, 0x49, 0x39}}

// QualifierValues (propget get_QualifierValues) dispatches through IResourceContext's vtable slot 6.
func (self *IResourceContext) QualifierValues() (*IMapOfStringAndString, error) {
	result := new(*IMapOfStringAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IResourceContext2 is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceContext2.
// IID: 7a3b1158-798c-5949-969d-03510b9ce6ca
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceContext runtime class.
type IResourceContext2 struct {
	syswinrt.IInspectable
}

// IID_IResourceContext2 is the interface identifier for IResourceContext2.
var IID_IResourceContext2 = win32.GUID{Data1: 0x7a3b1158, Data2: 0x798c, Data3: 0x5949, Data4: [8]byte{0x96, 0x9d, 0x03, 0x51, 0x0b, 0x9c, 0xe6, 0xca}}

// IResourceLoader is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceLoader.
// IID: bc3f76bf-da46-54cd-8715-8b8aaf16eaac
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceLoader runtime class.
type IResourceLoader struct {
	syswinrt.IInspectable
}

// IID_IResourceLoader is the interface identifier for IResourceLoader.
var IID_IResourceLoader = win32.GUID{Data1: 0xbc3f76bf, Data2: 0xda46, Data3: 0x54cd, Data4: [8]byte{0x87, 0x15, 0x8b, 0x8a, 0xaf, 0x16, 0xea, 0xac}}

// GetString dispatches through IResourceLoader's vtable slot 6.
func (self *IResourceLoader) GetString(resourceId string) (string, error) {
	hResourceId, err := winrt.NewHString(resourceId)
	if err != nil {
		return "", err
	}
	defer hResourceId.Close()
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hResourceId.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// GetStringForUri dispatches through IResourceLoader's vtable slot 7.
func (self *IResourceLoader) GetStringForUri(resourceUri *wrtfoundation.IUriRuntimeClass) (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(resourceUri)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IResourceLoaderFactory is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceLoaderFactory.
// IID: 871f83aa-fb34-50d6-b9b9-2c35f3ffc004
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceLoader runtime class.
type IResourceLoaderFactory struct {
	syswinrt.IInspectable
}

// IID_IResourceLoaderFactory is the interface identifier for IResourceLoaderFactory.
var IID_IResourceLoaderFactory = win32.GUID{Data1: 0x871f83aa, Data2: 0xfb34, Data3: 0x50d6, Data4: [8]byte{0xb9, 0xb9, 0x2c, 0x35, 0xf3, 0xff, 0xc0, 0x04}}

// CreateInstance dispatches through IResourceLoaderFactory's vtable slot 6.
func (self *IResourceLoaderFactory) CreateInstance(fileName string) (*IResourceLoader, error) {
	hFileName, err := winrt.NewHString(fileName)
	if err != nil {
		return nil, err
	}
	defer hFileName.Close()
	result := new(*IResourceLoader)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hFileName.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateInstance2 dispatches through IResourceLoaderFactory's vtable slot 7.
func (self *IResourceLoaderFactory) CreateInstance2(fileName string, resourceMap string) (*IResourceLoader, error) {
	hFileName, err := winrt.NewHString(fileName)
	if err != nil {
		return nil, err
	}
	defer hFileName.Close()
	hResourceMap, err := winrt.NewHString(resourceMap)
	if err != nil {
		return nil, err
	}
	defer hResourceMap.Close()
	result := new(*IResourceLoader)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hFileName.Raw()), uintptr(hResourceMap.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IResourceLoaderStatics is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceLoaderStatics.
// IID: ec9c894a-1466-5f2f-8eee-a70cbd2b51bb
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceLoader runtime class.
type IResourceLoaderStatics struct {
	syswinrt.IInspectable
}

// IID_IResourceLoaderStatics is the interface identifier for IResourceLoaderStatics.
var IID_IResourceLoaderStatics = win32.GUID{Data1: 0xec9c894a, Data2: 0x1466, Data3: 0x5f2f, Data4: [8]byte{0x8e, 0xee, 0xa7, 0x0c, 0xbd, 0x2b, 0x51, 0xbb}}

// GetDefaultResourceFilePath dispatches through IResourceLoaderStatics's vtable slot 6.
func (self *IResourceLoaderStatics) GetDefaultResourceFilePath() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IResourceManager is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceManager.
// IID: ac2291ef-81be-5c99-a0ae-bcee0180b8a8
type IResourceManager struct {
	syswinrt.IInspectable
}

// IID_IResourceManager is the interface identifier for IResourceManager.
var IID_IResourceManager = win32.GUID{Data1: 0xac2291ef, Data2: 0x81be, Data3: 0x5c99, Data4: [8]byte{0xa0, 0xae, 0xbc, 0xee, 0x01, 0x80, 0xb8, 0xa8}}

// MainResourceMap (propget get_MainResourceMap) dispatches through IResourceManager's vtable slot 6.
func (self *IResourceManager) MainResourceMap() (*IResourceMap, error) {
	result := new(*IResourceMap)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateResourceContext dispatches through IResourceManager's vtable slot 7.
func (self *IResourceManager) CreateResourceContext() (*IResourceContext, error) {
	result := new(*IResourceContext)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AddResourceNotFound (event add add_ResourceNotFound) dispatches through IResourceManager's vtable slot 8.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveResourceNotFound.
func (self *IResourceManager) AddResourceNotFound(handler *TypedEventHandlerOfResourceManagerAndResourceNotFoundEventArgs) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveResourceNotFound (event remove remove_ResourceNotFound) dispatches through IResourceManager's vtable slot 9,
// unregistering the ResourceNotFound handler the token was returned for.
func (self *IResourceManager) RemoveResourceNotFound(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// IResourceManager2 is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceManager2.
// IID: 7ec10160-a154-5c42-8268-30e306b1f585
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceManager runtime class.
type IResourceManager2 struct {
	syswinrt.IInspectable
}

// IID_IResourceManager2 is the interface identifier for IResourceManager2.
var IID_IResourceManager2 = win32.GUID{Data1: 0x7ec10160, Data2: 0xa154, Data3: 0x5c42, Data4: [8]byte{0x82, 0x68, 0x30, 0xe3, 0x06, 0xb1, 0xf5, 0x85}}

// IResourceManagerFactory is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceManagerFactory.
// IID: d6acf18f-458a-535b-a5c4-ac2dc4e49099
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceManager runtime class.
type IResourceManagerFactory struct {
	syswinrt.IInspectable
}

// IID_IResourceManagerFactory is the interface identifier for IResourceManagerFactory.
var IID_IResourceManagerFactory = win32.GUID{Data1: 0xd6acf18f, Data2: 0x458a, Data3: 0x535b, Data4: [8]byte{0xa5, 0xc4, 0xac, 0x2d, 0xc4, 0xe4, 0x90, 0x99}}

// CreateInstance dispatches through IResourceManagerFactory's vtable slot 6.
func (self *IResourceManagerFactory) CreateInstance(fileName string) (*IResourceManager, error) {
	hFileName, err := winrt.NewHString(fileName)
	if err != nil {
		return nil, err
	}
	defer hFileName.Close()
	result := new(*IResourceManager)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hFileName.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IResourceMap is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceMap.
// IID: 4abbd9bc-df4e-5c7b-812c-7e7bb0c22377
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceMap runtime class.
type IResourceMap struct {
	syswinrt.IInspectable
}

// IID_IResourceMap is the interface identifier for IResourceMap.
var IID_IResourceMap = win32.GUID{Data1: 0x4abbd9bc, Data2: 0xdf4e, Data3: 0x5c7b, Data4: [8]byte{0x81, 0x2c, 0x7e, 0x7b, 0xb0, 0xc2, 0x23, 0x77}}

// ResourceCount (propget get_ResourceCount) dispatches through IResourceMap's vtable slot 6.
func (self *IResourceMap) ResourceCount() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetSubtree dispatches through IResourceMap's vtable slot 7.
func (self *IResourceMap) GetSubtree(reference string) (*IResourceMap, error) {
	hReference, err := winrt.NewHString(reference)
	if err != nil {
		return nil, err
	}
	defer hReference.Close()
	result := new(*IResourceMap)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hReference.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// TryGetSubtree dispatches through IResourceMap's vtable slot 8.
func (self *IResourceMap) TryGetSubtree(reference string) (*IResourceMap, error) {
	hReference, err := winrt.NewHString(reference)
	if err != nil {
		return nil, err
	}
	defer hReference.Close()
	result := new(*IResourceMap)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hReference.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetValue dispatches through IResourceMap's vtable slot 9.
func (self *IResourceMap) GetValue(resource string) (*IResourceCandidate, error) {
	hResource, err := winrt.NewHString(resource)
	if err != nil {
		return nil, err
	}
	defer hResource.Close()
	result := new(*IResourceCandidate)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(hResource.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetValueWithContext dispatches through IResourceMap's vtable slot 10.
func (self *IResourceMap) GetValueWithContext(resource string, context *IResourceContext) (*IResourceCandidate, error) {
	hResource, err := winrt.NewHString(resource)
	if err != nil {
		return nil, err
	}
	defer hResource.Close()
	result := new(*IResourceCandidate)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(hResource.Raw()), uintptr(unsafe.Pointer(context)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetValueByIndex dispatches through IResourceMap's vtable slot 11.
func (self *IResourceMap) GetValueByIndex(index uint32) (*IKeyValuePairOfStringAndResourceCandidate, error) {
	result := new(*IKeyValuePairOfStringAndResourceCandidate)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetValueByIndexWithContext dispatches through IResourceMap's vtable slot 12.
func (self *IResourceMap) GetValueByIndexWithContext(index uint32, context *IResourceContext) (*IKeyValuePairOfStringAndResourceCandidate, error) {
	result := new(*IKeyValuePairOfStringAndResourceCandidate)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(context)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// TryGetValue dispatches through IResourceMap's vtable slot 13.
func (self *IResourceMap) TryGetValue(resource string) (*IResourceCandidate, error) {
	hResource, err := winrt.NewHString(resource)
	if err != nil {
		return nil, err
	}
	defer hResource.Close()
	result := new(*IResourceCandidate)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(hResource.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// TryGetValueWithContext dispatches through IResourceMap's vtable slot 14.
func (self *IResourceMap) TryGetValueWithContext(resource string, context *IResourceContext) (*IResourceCandidate, error) {
	hResource, err := winrt.NewHString(resource)
	if err != nil {
		return nil, err
	}
	defer hResource.Close()
	result := new(*IResourceCandidate)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(hResource.Raw()), uintptr(unsafe.Pointer(context)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IResourceNotFoundEventArgs is the WinRT interface Microsoft.Windows.ApplicationModel.Resources.IResourceNotFoundEventArgs.
// IID: 64abb08b-e77d-5b26-830f-15941e0e8200
// Exclusive to the Microsoft.Windows.ApplicationModel.Resources.ResourceNotFoundEventArgs runtime class.
type IResourceNotFoundEventArgs struct {
	syswinrt.IInspectable
}

// IID_IResourceNotFoundEventArgs is the interface identifier for IResourceNotFoundEventArgs.
var IID_IResourceNotFoundEventArgs = win32.GUID{Data1: 0x64abb08b, Data2: 0xe77d, Data3: 0x5b26, Data4: [8]byte{0x83, 0x0f, 0x15, 0x94, 0x1e, 0x0e, 0x82, 0x00}}

// Context (propget get_Context) dispatches through IResourceNotFoundEventArgs's vtable slot 6.
func (self *IResourceNotFoundEventArgs) Context() (*IResourceContext, error) {
	result := new(*IResourceContext)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Name (propget get_Name) dispatches through IResourceNotFoundEventArgs's vtable slot 7.
func (self *IResourceNotFoundEventArgs) Name() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SetResolvedCandidate dispatches through IResourceNotFoundEventArgs's vtable slot 8.
func (self *IResourceNotFoundEventArgs) SetResolvedCandidate(candidate *IResourceCandidate) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(candidate)))
	return win32.ErrIfFailed(int32(r1))
}
