// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package ui

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	wrtui "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/ui"
)

// IClosableNotifier is the WinRT interface Microsoft.UI.IClosableNotifier.
// IID: 2989e93b-ed0f-5e79-90f2-eac592fc6e6a
type IClosableNotifier struct {
	syswinrt.IInspectable
}

// IID_IClosableNotifier is the interface identifier for IClosableNotifier.
var IID_IClosableNotifier = win32.GUID{Data1: 0x2989e93b, Data2: 0xed0f, Data3: 0x5e79, Data4: [8]byte{0x90, 0xf2, 0xea, 0xc5, 0x92, 0xfc, 0x6e, 0x6a}}

// IsClosed (propget get_IsClosed) dispatches through IClosableNotifier's vtable slot 6.
func (self *IClosableNotifier) IsClosed() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// AddClosed (event add add_Closed) dispatches through IClosableNotifier's vtable slot 7.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveClosed.
func (self *IClosableNotifier) AddClosed(handler *ClosableNotifierHandler) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveClosed (event remove remove_Closed) dispatches through IClosableNotifier's vtable slot 8,
// unregistering the Closed handler the token was returned for.
func (self *IClosableNotifier) RemoveClosed(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// AddFrameworkClosed (event add add_FrameworkClosed) dispatches through IClosableNotifier's vtable slot 9.
// The handler stays registered (and referenced by the runtime) until the
// returned token is passed to RemoveFrameworkClosed.
func (self *IClosableNotifier) AddFrameworkClosed(handler *ClosableNotifierHandler) (syswinrt.EventRegistrationToken, error) {
	result := new(syswinrt.EventRegistrationToken)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), handler.Ptr(), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveFrameworkClosed (event remove remove_FrameworkClosed) dispatches through IClosableNotifier's vtable slot 10,
// unregistering the FrameworkClosed handler the token was returned for.
func (self *IClosableNotifier) RemoveFrameworkClosed(token syswinrt.EventRegistrationToken) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(token.Value))
	return win32.ErrIfFailed(int32(r1))
}

// IColorHelper is the WinRT interface Microsoft.UI.IColorHelper.
// IID: 3adddccd-3949-585b-a566-ccb8350dd221
// Exclusive to the Microsoft.UI.ColorHelper runtime class.
type IColorHelper struct {
	syswinrt.IInspectable
}

// IID_IColorHelper is the interface identifier for IColorHelper.
var IID_IColorHelper = win32.GUID{Data1: 0x3adddccd, Data2: 0x3949, Data3: 0x585b, Data4: [8]byte{0xa5, 0x66, 0xcc, 0xb8, 0x35, 0x0d, 0xd2, 0x21}}

// IColorHelperStatics is the WinRT interface Microsoft.UI.IColorHelperStatics.
// IID: 1d1d85a1-eb63-538a-84f0-019210bc406b
// Exclusive to the Microsoft.UI.ColorHelper runtime class.
type IColorHelperStatics struct {
	syswinrt.IInspectable
}

// IID_IColorHelperStatics is the interface identifier for IColorHelperStatics.
var IID_IColorHelperStatics = win32.GUID{Data1: 0x1d1d85a1, Data2: 0xeb63, Data3: 0x538a, Data4: [8]byte{0x84, 0xf0, 0x01, 0x92, 0x10, 0xbc, 0x40, 0x6b}}

// FromArgb dispatches through IColorHelperStatics's vtable slot 6.
func (self *IColorHelperStatics) FromArgb(a byte, r byte, g byte, b byte) (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(a), uintptr(r), uintptr(g), uintptr(b), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IColorHelperStatics2 is the WinRT interface Microsoft.UI.IColorHelperStatics2.
// IID: 982a2d93-0ec4-56b7-9c20-0b5c77949066
// Exclusive to the Microsoft.UI.ColorHelper runtime class.
type IColorHelperStatics2 struct {
	syswinrt.IInspectable
}

// IID_IColorHelperStatics2 is the interface identifier for IColorHelperStatics2.
var IID_IColorHelperStatics2 = win32.GUID{Data1: 0x982a2d93, Data2: 0x0ec4, Data3: 0x56b7, Data4: [8]byte{0x9c, 0x20, 0x0b, 0x5c, 0x77, 0x94, 0x90, 0x66}}

// ToDisplayName dispatches through IColorHelperStatics2's vtable slot 6.
func (self *IColorHelperStatics2) ToDisplayName(color wrtui.Color) (string, error) {
	_color := uintptr(*(*uint32)(unsafe.Pointer(&color)))
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _color, uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IColors is the WinRT interface Microsoft.UI.IColors.
// IID: 8cf15863-8411-5afd-946c-328e04da2f2f
// Exclusive to the Microsoft.UI.Colors runtime class.
type IColors struct {
	syswinrt.IInspectable
}

// IID_IColors is the interface identifier for IColors.
var IID_IColors = win32.GUID{Data1: 0x8cf15863, Data2: 0x8411, Data3: 0x5afd, Data4: [8]byte{0x94, 0x6c, 0x32, 0x8e, 0x04, 0xda, 0x2f, 0x2f}}

// IColorsStatics is the WinRT interface Microsoft.UI.IColorsStatics.
// IID: 8620a5b0-015a-57ac-a3f3-895d0b1269ae
// Exclusive to the Microsoft.UI.Colors runtime class.
type IColorsStatics struct {
	syswinrt.IInspectable
}

// IID_IColorsStatics is the interface identifier for IColorsStatics.
var IID_IColorsStatics = win32.GUID{Data1: 0x8620a5b0, Data2: 0x015a, Data3: 0x57ac, Data4: [8]byte{0xa3, 0xf3, 0x89, 0x5d, 0x0b, 0x12, 0x69, 0xae}}

// AliceBlue (propget get_AliceBlue) dispatches through IColorsStatics's vtable slot 6.
func (self *IColorsStatics) AliceBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AntiqueWhite (propget get_AntiqueWhite) dispatches through IColorsStatics's vtable slot 7.
func (self *IColorsStatics) AntiqueWhite() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Aqua (propget get_Aqua) dispatches through IColorsStatics's vtable slot 8.
func (self *IColorsStatics) Aqua() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Aquamarine (propget get_Aquamarine) dispatches through IColorsStatics's vtable slot 9.
func (self *IColorsStatics) Aquamarine() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Azure (propget get_Azure) dispatches through IColorsStatics's vtable slot 10.
func (self *IColorsStatics) Azure() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Beige (propget get_Beige) dispatches through IColorsStatics's vtable slot 11.
func (self *IColorsStatics) Beige() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Bisque (propget get_Bisque) dispatches through IColorsStatics's vtable slot 12.
func (self *IColorsStatics) Bisque() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Black (propget get_Black) dispatches through IColorsStatics's vtable slot 13.
func (self *IColorsStatics) Black() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// BlanchedAlmond (propget get_BlanchedAlmond) dispatches through IColorsStatics's vtable slot 14.
func (self *IColorsStatics) BlanchedAlmond() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Blue (propget get_Blue) dispatches through IColorsStatics's vtable slot 15.
func (self *IColorsStatics) Blue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// BlueViolet (propget get_BlueViolet) dispatches through IColorsStatics's vtable slot 16.
func (self *IColorsStatics) BlueViolet() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[16], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Brown (propget get_Brown) dispatches through IColorsStatics's vtable slot 17.
func (self *IColorsStatics) Brown() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[17], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// BurlyWood (propget get_BurlyWood) dispatches through IColorsStatics's vtable slot 18.
func (self *IColorsStatics) BurlyWood() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[18], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CadetBlue (propget get_CadetBlue) dispatches through IColorsStatics's vtable slot 19.
func (self *IColorsStatics) CadetBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[19], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Chartreuse (propget get_Chartreuse) dispatches through IColorsStatics's vtable slot 20.
func (self *IColorsStatics) Chartreuse() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[20], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Chocolate (propget get_Chocolate) dispatches through IColorsStatics's vtable slot 21.
func (self *IColorsStatics) Chocolate() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[21], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Coral (propget get_Coral) dispatches through IColorsStatics's vtable slot 22.
func (self *IColorsStatics) Coral() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[22], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CornflowerBlue (propget get_CornflowerBlue) dispatches through IColorsStatics's vtable slot 23.
func (self *IColorsStatics) CornflowerBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[23], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Cornsilk (propget get_Cornsilk) dispatches through IColorsStatics's vtable slot 24.
func (self *IColorsStatics) Cornsilk() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[24], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Crimson (propget get_Crimson) dispatches through IColorsStatics's vtable slot 25.
func (self *IColorsStatics) Crimson() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[25], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Cyan (propget get_Cyan) dispatches through IColorsStatics's vtable slot 26.
func (self *IColorsStatics) Cyan() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[26], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkBlue (propget get_DarkBlue) dispatches through IColorsStatics's vtable slot 27.
func (self *IColorsStatics) DarkBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[27], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkCyan (propget get_DarkCyan) dispatches through IColorsStatics's vtable slot 28.
func (self *IColorsStatics) DarkCyan() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[28], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkGoldenrod (propget get_DarkGoldenrod) dispatches through IColorsStatics's vtable slot 29.
func (self *IColorsStatics) DarkGoldenrod() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[29], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkGray (propget get_DarkGray) dispatches through IColorsStatics's vtable slot 30.
func (self *IColorsStatics) DarkGray() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[30], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkGreen (propget get_DarkGreen) dispatches through IColorsStatics's vtable slot 31.
func (self *IColorsStatics) DarkGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[31], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkKhaki (propget get_DarkKhaki) dispatches through IColorsStatics's vtable slot 32.
func (self *IColorsStatics) DarkKhaki() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[32], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkMagenta (propget get_DarkMagenta) dispatches through IColorsStatics's vtable slot 33.
func (self *IColorsStatics) DarkMagenta() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[33], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkOliveGreen (propget get_DarkOliveGreen) dispatches through IColorsStatics's vtable slot 34.
func (self *IColorsStatics) DarkOliveGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[34], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkOrange (propget get_DarkOrange) dispatches through IColorsStatics's vtable slot 35.
func (self *IColorsStatics) DarkOrange() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[35], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkOrchid (propget get_DarkOrchid) dispatches through IColorsStatics's vtable slot 36.
func (self *IColorsStatics) DarkOrchid() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[36], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkRed (propget get_DarkRed) dispatches through IColorsStatics's vtable slot 37.
func (self *IColorsStatics) DarkRed() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[37], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkSalmon (propget get_DarkSalmon) dispatches through IColorsStatics's vtable slot 38.
func (self *IColorsStatics) DarkSalmon() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[38], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkSeaGreen (propget get_DarkSeaGreen) dispatches through IColorsStatics's vtable slot 39.
func (self *IColorsStatics) DarkSeaGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[39], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkSlateBlue (propget get_DarkSlateBlue) dispatches through IColorsStatics's vtable slot 40.
func (self *IColorsStatics) DarkSlateBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[40], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkSlateGray (propget get_DarkSlateGray) dispatches through IColorsStatics's vtable slot 41.
func (self *IColorsStatics) DarkSlateGray() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[41], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkTurquoise (propget get_DarkTurquoise) dispatches through IColorsStatics's vtable slot 42.
func (self *IColorsStatics) DarkTurquoise() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[42], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DarkViolet (propget get_DarkViolet) dispatches through IColorsStatics's vtable slot 43.
func (self *IColorsStatics) DarkViolet() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[43], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DeepPink (propget get_DeepPink) dispatches through IColorsStatics's vtable slot 44.
func (self *IColorsStatics) DeepPink() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[44], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DeepSkyBlue (propget get_DeepSkyBlue) dispatches through IColorsStatics's vtable slot 45.
func (self *IColorsStatics) DeepSkyBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[45], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DimGray (propget get_DimGray) dispatches through IColorsStatics's vtable slot 46.
func (self *IColorsStatics) DimGray() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[46], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// DodgerBlue (propget get_DodgerBlue) dispatches through IColorsStatics's vtable slot 47.
func (self *IColorsStatics) DodgerBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[47], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Firebrick (propget get_Firebrick) dispatches through IColorsStatics's vtable slot 48.
func (self *IColorsStatics) Firebrick() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[48], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// FloralWhite (propget get_FloralWhite) dispatches through IColorsStatics's vtable slot 49.
func (self *IColorsStatics) FloralWhite() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[49], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ForestGreen (propget get_ForestGreen) dispatches through IColorsStatics's vtable slot 50.
func (self *IColorsStatics) ForestGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[50], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Fuchsia (propget get_Fuchsia) dispatches through IColorsStatics's vtable slot 51.
func (self *IColorsStatics) Fuchsia() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[51], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Gainsboro (propget get_Gainsboro) dispatches through IColorsStatics's vtable slot 52.
func (self *IColorsStatics) Gainsboro() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[52], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GhostWhite (propget get_GhostWhite) dispatches through IColorsStatics's vtable slot 53.
func (self *IColorsStatics) GhostWhite() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[53], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Gold (propget get_Gold) dispatches through IColorsStatics's vtable slot 54.
func (self *IColorsStatics) Gold() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[54], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Goldenrod (propget get_Goldenrod) dispatches through IColorsStatics's vtable slot 55.
func (self *IColorsStatics) Goldenrod() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[55], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Gray (propget get_Gray) dispatches through IColorsStatics's vtable slot 56.
func (self *IColorsStatics) Gray() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[56], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Green (propget get_Green) dispatches through IColorsStatics's vtable slot 57.
func (self *IColorsStatics) Green() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[57], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GreenYellow (propget get_GreenYellow) dispatches through IColorsStatics's vtable slot 58.
func (self *IColorsStatics) GreenYellow() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[58], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Honeydew (propget get_Honeydew) dispatches through IColorsStatics's vtable slot 59.
func (self *IColorsStatics) Honeydew() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[59], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HotPink (propget get_HotPink) dispatches through IColorsStatics's vtable slot 60.
func (self *IColorsStatics) HotPink() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[60], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndianRed (propget get_IndianRed) dispatches through IColorsStatics's vtable slot 61.
func (self *IColorsStatics) IndianRed() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[61], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Indigo (propget get_Indigo) dispatches through IColorsStatics's vtable slot 62.
func (self *IColorsStatics) Indigo() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[62], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Ivory (propget get_Ivory) dispatches through IColorsStatics's vtable slot 63.
func (self *IColorsStatics) Ivory() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[63], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Khaki (propget get_Khaki) dispatches through IColorsStatics's vtable slot 64.
func (self *IColorsStatics) Khaki() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[64], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Lavender (propget get_Lavender) dispatches through IColorsStatics's vtable slot 65.
func (self *IColorsStatics) Lavender() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[65], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LavenderBlush (propget get_LavenderBlush) dispatches through IColorsStatics's vtable slot 66.
func (self *IColorsStatics) LavenderBlush() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[66], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LawnGreen (propget get_LawnGreen) dispatches through IColorsStatics's vtable slot 67.
func (self *IColorsStatics) LawnGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[67], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LemonChiffon (propget get_LemonChiffon) dispatches through IColorsStatics's vtable slot 68.
func (self *IColorsStatics) LemonChiffon() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[68], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightBlue (propget get_LightBlue) dispatches through IColorsStatics's vtable slot 69.
func (self *IColorsStatics) LightBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[69], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightCoral (propget get_LightCoral) dispatches through IColorsStatics's vtable slot 70.
func (self *IColorsStatics) LightCoral() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[70], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightCyan (propget get_LightCyan) dispatches through IColorsStatics's vtable slot 71.
func (self *IColorsStatics) LightCyan() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[71], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightGoldenrodYellow (propget get_LightGoldenrodYellow) dispatches through IColorsStatics's vtable slot 72.
func (self *IColorsStatics) LightGoldenrodYellow() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[72], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightGreen (propget get_LightGreen) dispatches through IColorsStatics's vtable slot 73.
func (self *IColorsStatics) LightGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[73], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightGray (propget get_LightGray) dispatches through IColorsStatics's vtable slot 74.
func (self *IColorsStatics) LightGray() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[74], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightPink (propget get_LightPink) dispatches through IColorsStatics's vtable slot 75.
func (self *IColorsStatics) LightPink() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[75], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightSalmon (propget get_LightSalmon) dispatches through IColorsStatics's vtable slot 76.
func (self *IColorsStatics) LightSalmon() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[76], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightSeaGreen (propget get_LightSeaGreen) dispatches through IColorsStatics's vtable slot 77.
func (self *IColorsStatics) LightSeaGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[77], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightSkyBlue (propget get_LightSkyBlue) dispatches through IColorsStatics's vtable slot 78.
func (self *IColorsStatics) LightSkyBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[78], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightSlateGray (propget get_LightSlateGray) dispatches through IColorsStatics's vtable slot 79.
func (self *IColorsStatics) LightSlateGray() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[79], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightSteelBlue (propget get_LightSteelBlue) dispatches through IColorsStatics's vtable slot 80.
func (self *IColorsStatics) LightSteelBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[80], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LightYellow (propget get_LightYellow) dispatches through IColorsStatics's vtable slot 81.
func (self *IColorsStatics) LightYellow() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[81], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Lime (propget get_Lime) dispatches through IColorsStatics's vtable slot 82.
func (self *IColorsStatics) Lime() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[82], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LimeGreen (propget get_LimeGreen) dispatches through IColorsStatics's vtable slot 83.
func (self *IColorsStatics) LimeGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[83], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Linen (propget get_Linen) dispatches through IColorsStatics's vtable slot 84.
func (self *IColorsStatics) Linen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[84], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Magenta (propget get_Magenta) dispatches through IColorsStatics's vtable slot 85.
func (self *IColorsStatics) Magenta() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[85], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Maroon (propget get_Maroon) dispatches through IColorsStatics's vtable slot 86.
func (self *IColorsStatics) Maroon() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[86], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumAquamarine (propget get_MediumAquamarine) dispatches through IColorsStatics's vtable slot 87.
func (self *IColorsStatics) MediumAquamarine() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[87], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumBlue (propget get_MediumBlue) dispatches through IColorsStatics's vtable slot 88.
func (self *IColorsStatics) MediumBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[88], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumOrchid (propget get_MediumOrchid) dispatches through IColorsStatics's vtable slot 89.
func (self *IColorsStatics) MediumOrchid() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[89], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumPurple (propget get_MediumPurple) dispatches through IColorsStatics's vtable slot 90.
func (self *IColorsStatics) MediumPurple() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[90], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumSeaGreen (propget get_MediumSeaGreen) dispatches through IColorsStatics's vtable slot 91.
func (self *IColorsStatics) MediumSeaGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[91], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumSlateBlue (propget get_MediumSlateBlue) dispatches through IColorsStatics's vtable slot 92.
func (self *IColorsStatics) MediumSlateBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[92], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumSpringGreen (propget get_MediumSpringGreen) dispatches through IColorsStatics's vtable slot 93.
func (self *IColorsStatics) MediumSpringGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[93], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumTurquoise (propget get_MediumTurquoise) dispatches through IColorsStatics's vtable slot 94.
func (self *IColorsStatics) MediumTurquoise() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[94], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MediumVioletRed (propget get_MediumVioletRed) dispatches through IColorsStatics's vtable slot 95.
func (self *IColorsStatics) MediumVioletRed() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[95], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MidnightBlue (propget get_MidnightBlue) dispatches through IColorsStatics's vtable slot 96.
func (self *IColorsStatics) MidnightBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[96], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MintCream (propget get_MintCream) dispatches through IColorsStatics's vtable slot 97.
func (self *IColorsStatics) MintCream() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[97], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MistyRose (propget get_MistyRose) dispatches through IColorsStatics's vtable slot 98.
func (self *IColorsStatics) MistyRose() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[98], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Moccasin (propget get_Moccasin) dispatches through IColorsStatics's vtable slot 99.
func (self *IColorsStatics) Moccasin() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[99], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// NavajoWhite (propget get_NavajoWhite) dispatches through IColorsStatics's vtable slot 100.
func (self *IColorsStatics) NavajoWhite() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[100], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Navy (propget get_Navy) dispatches through IColorsStatics's vtable slot 101.
func (self *IColorsStatics) Navy() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[101], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// OldLace (propget get_OldLace) dispatches through IColorsStatics's vtable slot 102.
func (self *IColorsStatics) OldLace() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[102], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Olive (propget get_Olive) dispatches through IColorsStatics's vtable slot 103.
func (self *IColorsStatics) Olive() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[103], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// OliveDrab (propget get_OliveDrab) dispatches through IColorsStatics's vtable slot 104.
func (self *IColorsStatics) OliveDrab() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[104], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Orange (propget get_Orange) dispatches through IColorsStatics's vtable slot 105.
func (self *IColorsStatics) Orange() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[105], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// OrangeRed (propget get_OrangeRed) dispatches through IColorsStatics's vtable slot 106.
func (self *IColorsStatics) OrangeRed() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[106], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Orchid (propget get_Orchid) dispatches through IColorsStatics's vtable slot 107.
func (self *IColorsStatics) Orchid() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[107], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// PaleGoldenrod (propget get_PaleGoldenrod) dispatches through IColorsStatics's vtable slot 108.
func (self *IColorsStatics) PaleGoldenrod() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[108], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// PaleGreen (propget get_PaleGreen) dispatches through IColorsStatics's vtable slot 109.
func (self *IColorsStatics) PaleGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[109], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// PaleTurquoise (propget get_PaleTurquoise) dispatches through IColorsStatics's vtable slot 110.
func (self *IColorsStatics) PaleTurquoise() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[110], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// PaleVioletRed (propget get_PaleVioletRed) dispatches through IColorsStatics's vtable slot 111.
func (self *IColorsStatics) PaleVioletRed() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[111], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// PapayaWhip (propget get_PapayaWhip) dispatches through IColorsStatics's vtable slot 112.
func (self *IColorsStatics) PapayaWhip() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[112], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// PeachPuff (propget get_PeachPuff) dispatches through IColorsStatics's vtable slot 113.
func (self *IColorsStatics) PeachPuff() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[113], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Peru (propget get_Peru) dispatches through IColorsStatics's vtable slot 114.
func (self *IColorsStatics) Peru() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[114], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Pink (propget get_Pink) dispatches through IColorsStatics's vtable slot 115.
func (self *IColorsStatics) Pink() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[115], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Plum (propget get_Plum) dispatches through IColorsStatics's vtable slot 116.
func (self *IColorsStatics) Plum() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[116], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// PowderBlue (propget get_PowderBlue) dispatches through IColorsStatics's vtable slot 117.
func (self *IColorsStatics) PowderBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[117], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Purple (propget get_Purple) dispatches through IColorsStatics's vtable slot 118.
func (self *IColorsStatics) Purple() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[118], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Red (propget get_Red) dispatches through IColorsStatics's vtable slot 119.
func (self *IColorsStatics) Red() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[119], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RosyBrown (propget get_RosyBrown) dispatches through IColorsStatics's vtable slot 120.
func (self *IColorsStatics) RosyBrown() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[120], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RoyalBlue (propget get_RoyalBlue) dispatches through IColorsStatics's vtable slot 121.
func (self *IColorsStatics) RoyalBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[121], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SaddleBrown (propget get_SaddleBrown) dispatches through IColorsStatics's vtable slot 122.
func (self *IColorsStatics) SaddleBrown() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[122], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Salmon (propget get_Salmon) dispatches through IColorsStatics's vtable slot 123.
func (self *IColorsStatics) Salmon() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[123], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SandyBrown (propget get_SandyBrown) dispatches through IColorsStatics's vtable slot 124.
func (self *IColorsStatics) SandyBrown() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[124], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SeaGreen (propget get_SeaGreen) dispatches through IColorsStatics's vtable slot 125.
func (self *IColorsStatics) SeaGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[125], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SeaShell (propget get_SeaShell) dispatches through IColorsStatics's vtable slot 126.
func (self *IColorsStatics) SeaShell() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[126], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Sienna (propget get_Sienna) dispatches through IColorsStatics's vtable slot 127.
func (self *IColorsStatics) Sienna() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[127], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Silver (propget get_Silver) dispatches through IColorsStatics's vtable slot 128.
func (self *IColorsStatics) Silver() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[128], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SkyBlue (propget get_SkyBlue) dispatches through IColorsStatics's vtable slot 129.
func (self *IColorsStatics) SkyBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[129], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SlateBlue (propget get_SlateBlue) dispatches through IColorsStatics's vtable slot 130.
func (self *IColorsStatics) SlateBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[130], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SlateGray (propget get_SlateGray) dispatches through IColorsStatics's vtable slot 131.
func (self *IColorsStatics) SlateGray() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[131], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Snow (propget get_Snow) dispatches through IColorsStatics's vtable slot 132.
func (self *IColorsStatics) Snow() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[132], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SpringGreen (propget get_SpringGreen) dispatches through IColorsStatics's vtable slot 133.
func (self *IColorsStatics) SpringGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[133], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SteelBlue (propget get_SteelBlue) dispatches through IColorsStatics's vtable slot 134.
func (self *IColorsStatics) SteelBlue() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[134], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Tan (propget get_Tan) dispatches through IColorsStatics's vtable slot 135.
func (self *IColorsStatics) Tan() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[135], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Teal (propget get_Teal) dispatches through IColorsStatics's vtable slot 136.
func (self *IColorsStatics) Teal() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[136], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Thistle (propget get_Thistle) dispatches through IColorsStatics's vtable slot 137.
func (self *IColorsStatics) Thistle() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[137], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Tomato (propget get_Tomato) dispatches through IColorsStatics's vtable slot 138.
func (self *IColorsStatics) Tomato() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[138], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Transparent (propget get_Transparent) dispatches through IColorsStatics's vtable slot 139.
func (self *IColorsStatics) Transparent() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[139], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Turquoise (propget get_Turquoise) dispatches through IColorsStatics's vtable slot 140.
func (self *IColorsStatics) Turquoise() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[140], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Violet (propget get_Violet) dispatches through IColorsStatics's vtable slot 141.
func (self *IColorsStatics) Violet() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[141], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Wheat (propget get_Wheat) dispatches through IColorsStatics's vtable slot 142.
func (self *IColorsStatics) Wheat() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[142], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// White (propget get_White) dispatches through IColorsStatics's vtable slot 143.
func (self *IColorsStatics) White() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[143], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// WhiteSmoke (propget get_WhiteSmoke) dispatches through IColorsStatics's vtable slot 144.
func (self *IColorsStatics) WhiteSmoke() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[144], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Yellow (propget get_Yellow) dispatches through IColorsStatics's vtable slot 145.
func (self *IColorsStatics) Yellow() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[145], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// YellowGreen (propget get_YellowGreen) dispatches through IColorsStatics's vtable slot 146.
func (self *IColorsStatics) YellowGreen() (wrtui.Color, error) {
	result := new(wrtui.Color)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[146], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
