// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package dynamicdependency

// DynamicDependencyContract is Microsoft.Windows.ApplicationModel.DynamicDependency.DynamicDependencyContract.
type DynamicDependencyContract struct {
}

// PackageDependencyContextId is Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyContextId.
type PackageDependencyContextId struct {
	Id uint64
}
