// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package imaging

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	uixaml "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/ui/xaml"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// DownloadProgressEventHandler is a Go-implemented handler for the WinRT delegate
// Microsoft.UI.Xaml.Media.Imaging.DownloadProgressEventHandler.
// IID: 9a8e4af5-b124-5205-8ae9-3496e063c569
type DownloadProgressEventHandler struct {
	delegate *winrt.Delegate
}

// IID_DownloadProgressEventHandler is the delegate identifier for DownloadProgressEventHandler.
var IID_DownloadProgressEventHandler = win32.GUID{Data1: 0x9a8e4af5, Data2: 0xb124, Data3: 0x5205, Data4: [8]byte{0x8a, 0xe9, 0x34, 0x96, 0xe0, 0x63, 0xc5, 0x69}}

// NewDownloadProgressEventHandler wraps fn as a COM-callable Microsoft.UI.Xaml.Media.Imaging.DownloadProgressEventHandler.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewDownloadProgressEventHandler(fn func(sender *syswinrt.IInspectable, e *IDownloadProgressEventArgs)) (*DownloadProgressEventHandler, error) {
	delegate, err := winrt.NewDelegate(IID_DownloadProgressEventHandler, 2, func(raw []uintptr) uintptr {
		fn((*syswinrt.IInspectable)(unsafe.Pointer(raw[0])), (*IDownloadProgressEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &DownloadProgressEventHandler{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *DownloadProgressEventHandler) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can still
// invoke the handler — after the event source removed it, or closed. The runtime
// keeps its own references while the handler stays registered.
func (h *DownloadProgressEventHandler) Close() { h.delegate.Release() }

// ExceptionRoutedEventHandler is a Go-implemented handler for the WinRT delegate
// Microsoft.UI.Xaml.ExceptionRoutedEventHandler.
// IID: 45fbb85d-54f9-5a2a-8a38-00a3b7761f96
type ExceptionRoutedEventHandler struct {
	delegate *winrt.Delegate
}

// IID_ExceptionRoutedEventHandler is the delegate identifier for ExceptionRoutedEventHandler.
var IID_ExceptionRoutedEventHandler = win32.GUID{Data1: 0x45fbb85d, Data2: 0x54f9, Data3: 0x5a2a, Data4: [8]byte{0x8a, 0x38, 0x00, 0xa3, 0xb7, 0x76, 0x1f, 0x96}}

// NewExceptionRoutedEventHandler wraps fn as a COM-callable Microsoft.UI.Xaml.ExceptionRoutedEventHandler.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewExceptionRoutedEventHandler(fn func(sender *syswinrt.IInspectable, e *uixaml.IExceptionRoutedEventArgs)) (*ExceptionRoutedEventHandler, error) {
	delegate, err := winrt.NewDelegate(IID_ExceptionRoutedEventHandler, 2, func(raw []uintptr) uintptr {
		fn((*syswinrt.IInspectable)(unsafe.Pointer(raw[0])), (*uixaml.IExceptionRoutedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &ExceptionRoutedEventHandler{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *ExceptionRoutedEventHandler) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can still
// invoke the handler — after the event source removed it, or closed. The runtime
// keeps its own references while the handler stays registered.
func (h *ExceptionRoutedEventHandler) Close() { h.delegate.Release() }

// RoutedEventHandler is a Go-implemented handler for the WinRT delegate
// Microsoft.UI.Xaml.RoutedEventHandler.
// IID: dae23d85-69ca-5bdf-805b-6161a3a215cc
type RoutedEventHandler struct {
	delegate *winrt.Delegate
}

// IID_RoutedEventHandler is the delegate identifier for RoutedEventHandler.
var IID_RoutedEventHandler = win32.GUID{Data1: 0xdae23d85, Data2: 0x69ca, Data3: 0x5bdf, Data4: [8]byte{0x80, 0x5b, 0x61, 0x61, 0xa3, 0xa2, 0x15, 0xcc}}

// NewRoutedEventHandler wraps fn as a COM-callable Microsoft.UI.Xaml.RoutedEventHandler.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewRoutedEventHandler(fn func(sender *syswinrt.IInspectable, e *uixaml.IRoutedEventArgs)) (*RoutedEventHandler, error) {
	delegate, err := winrt.NewDelegate(IID_RoutedEventHandler, 2, func(raw []uintptr) uintptr {
		fn((*syswinrt.IInspectable)(unsafe.Pointer(raw[0])), (*uixaml.IRoutedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &RoutedEventHandler{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *RoutedEventHandler) Ptr() uintptr { return h.delegate.Ptr() }

// Close releases the Go-held reference. Call it once no native code can still
// invoke the handler — after the event source removed it, or closed. The runtime
// keeps its own references while the handler stays registered.
func (h *RoutedEventHandler) Close() { h.delegate.Release() }

// TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Microsoft.UI.Xaml.Media.Imaging.SvgImageSource, Microsoft.UI.Xaml.Media.Imaging.SvgImageSourceFailedEventArgs>.
// IID: c5f3237b-4599-5ef5-932f-4b8e723dd67e
type TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs is the delegate identifier for TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs.
var IID_TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs = win32.GUID{Data1: 0xc5f3237b, Data2: 0x4599, Data3: 0x5ef5, Data4: [8]byte{0x93, 0x2f, 0x4b, 0x8e, 0x72, 0x3d, 0xd6, 0x7e}}

// NewTypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Microsoft.UI.Xaml.Media.Imaging.SvgImageSource, Microsoft.UI.Xaml.Media.Imaging.SvgImageSourceFailedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs(fn func(sender *ISvgImageSource, args *ISvgImageSourceFailedEventArgs)) (*TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*ISvgImageSource)(unsafe.Pointer(raw[0])), (*ISvgImageSourceFailedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can still
// invoke the handler — after the event source removed it, or closed. The runtime
// keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfSvgImageSourceAndSvgImageSourceFailedEventArgs) Close() {
	h.delegate.Release()
}

// TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs is a Go-implemented handler for the WinRT delegate
// Windows.Foundation.TypedEventHandler`2<Microsoft.UI.Xaml.Media.Imaging.SvgImageSource, Microsoft.UI.Xaml.Media.Imaging.SvgImageSourceOpenedEventArgs>.
// IID: e81e0783-eb64-5e84-b57a-ac6164814f85
type TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs struct {
	delegate *winrt.Delegate
}

// IID_TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs is the delegate identifier for TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs.
var IID_TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs = win32.GUID{Data1: 0xe81e0783, Data2: 0xeb64, Data3: 0x5e84, Data4: [8]byte{0xb5, 0x7a, 0xac, 0x61, 0x64, 0x81, 0x4f, 0x85}}

// NewTypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs wraps fn as a COM-callable Windows.Foundation.TypedEventHandler`2<Microsoft.UI.Xaml.Media.Imaging.SvgImageSource, Microsoft.UI.Xaml.Media.Imaging.SvgImageSourceOpenedEventArgs>.
// The handler starts with one Go-held reference; Close it once no native
// code can still invoke it.
// Pointer-typed callback arguments are BORROWED references owned by the
// event source for the duration of the callback: do not Release them or
// retain them past its return.
func NewTypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs(fn func(sender *ISvgImageSource, args *ISvgImageSourceOpenedEventArgs)) (*TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs, error) {
	delegate, err := winrt.NewDelegate(IID_TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs, 2, func(raw []uintptr) uintptr {
		fn((*ISvgImageSource)(unsafe.Pointer(raw[0])), (*ISvgImageSourceOpenedEventArgs)(unsafe.Pointer(raw[1])))
		return 0
	})
	if err != nil {
		return nil, err
	}
	return &TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs{delegate: delegate}, nil
}

// Ptr is the COM object pointer an Add<Event> method registers.
func (h *TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs) Ptr() uintptr {
	return h.delegate.Ptr()
}

// Close releases the Go-held reference. Call it once no native code can still
// invoke the handler — after the event source removed it, or closed. The runtime
// keeps its own references while the handler stays registered.
func (h *TypedEventHandlerOfSvgImageSourceAndSvgImageSourceOpenedEventArgs) Close() {
	h.delegate.Release()
}
