// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

// Package accesscontrol binds the Microsoft.Windows.Security.AccessControl API surface of the Windows App SDK.
package accesscontrol
