package emitwinui

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/deploymenttheory/go-bindings-windowsappsdk/internal/codegen/pipeline"
	"github.com/deploymenttheory/go-bindings-windowsappsdk/internal/wasdkmeta/external"
)

const (
	metadataDir = "../../../../metadata/wasdk"
	modulePath  = "github.com/deploymenttheory/go-bindings-windowsappsdk"
)

// emitted is one whole-tree emission into a temporary directory, cached because
// generating 77 packages is not cheap.
type emitted struct {
	generator *Generator
	dir       string
	files     map[string]string
}

var cached *emitted

// emit runs the generator over the committed metadata. Real metadata rather than
// fixtures: the questions worth asking — does the Button click path come out
// callable, does an external reference use the prefixed alias — are questions about
// that metadata, and a fixture answering them would only be asserting its own
// contents.
func emit(t *testing.T) *emitted {
	t.Helper()
	if cached != nil {
		return cached
	}
	externalSet, err := external.Load("")
	if err != nil {
		t.Fatalf("loading the Windows.* universe: %v", err)
	}
	registry, err := pipeline.Load(metadataDir, externalSet)
	if err != nil {
		t.Fatalf("loading the committed metadata: %v", err)
	}
	// A stable directory outside the repository, reused across the run: t.TempDir
	// would be removed between tests and the emission redone each time.
	dir, err := os.MkdirTemp("", "winui-emit-")
	if err != nil {
		t.Fatal(err)
	}
	generator := New(registry, modulePath, dir)
	filter := map[string]bool{}
	for _, meta := range registry.Namespaces {
		filter[meta.Namespace] = true
	}
	count, err := generator.EmitAll(filter)
	if err != nil {
		t.Fatalf("EmitAll: %v", err)
	}
	if count != len(registry.Namespaces) {
		t.Fatalf("emitted %d packages, want %d", count, len(registry.Namespaces))
	}
	files := map[string]string{}
	err = filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() || !strings.HasSuffix(path, ".go") {
			return err
		}
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		relative, _ := filepath.Rel(dir, path)
		files[filepath.ToSlash(relative)] = string(content)
		return nil
	})
	if err != nil {
		t.Fatalf("reading the emitted tree: %v", err)
	}
	cached = &emitted{generator: generator, dir: dir, files: files}
	t.Cleanup(func() {})
	return cached
}

func source(t *testing.T, path string) string {
	t.Helper()
	result := emit(t)
	content, ok := result.files[path]
	if !ok {
		t.Fatalf("%s was not emitted", path)
	}
	return content
}

// TestEveryPackageHasTheScaffold checks what every generated file must carry:
// the header the pruner keys off, and the build constraint that keeps the tree off
// architectures where its float arguments would be corrupted.
func TestEveryPackageHasTheScaffold(t *testing.T) {
	result := emit(t)
	if len(result.files) == 0 {
		t.Fatal("no files emitted")
	}
	for path, content := range result.files {
		if !strings.HasPrefix(content, "// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.") {
			t.Errorf("%s does not start with the DO-NOT-EDIT header", path)
		}
		// The constraint line only. Searching the whole file for an excluded
		// architecture matches GUID hex — "3862" contains "386" — which says
		// nothing about the build tag.
		constraint, ok := buildConstraint(content)
		if !ok {
			t.Errorf("%s has no //go:build line", path)
			continue
		}
		if constraint != "windows && amd64" {
			t.Errorf("%s constrains to %q, want windows && amd64", path, constraint)
		}
	}
	t.Logf("%d files across the tree", len(result.files))
}

// TestButtonClickPathIsCallable is the acceptance criterion for the whole emitter,
// stated as one test. Every part has to be present for a Go program to respond to a
// click: a way to construct the Button, a grounded handler type, and an Add that
// dispatches at the right slot.
func TestButtonClickPathIsCallable(t *testing.T) {
	classes := source(t, "ui/xaml/controls/controls_classes.go")
	// Button is composable, so the constructor goes through the composable factory
	// with a null outer rather than RoActivateInstance.
	if !strings.Contains(classes, "func NewButton() (*Button, error)") {
		t.Error("no NewButton constructor")
	}
	if !strings.Contains(classes, "factory.CreateInstance(nil, inner)") {
		t.Error("NewButton does not call CreateInstance with a null outer")
	}
	if !strings.Contains(classes, "type Button struct {\n\tIButton\n}") {
		t.Error("Button does not embed its default interface")
	}

	primitives := source(t, "ui/xaml/controls/primitives/primitives_interfaces.go")
	// Slot 14 is pinned independently in internal/verify against the winmd.
	if !strings.Contains(primitives, "func (self *IButtonBase) AddClick(handler *RoutedEventHandler) (syswinrt.EventRegistrationToken, error)") {
		t.Error("IButtonBase.AddClick is not emitted with a typed handler")
	}
	if !strings.Contains(primitives, "self.LpVtbl[14]") {
		t.Error("AddClick does not dispatch through slot 14")
	}
	if !strings.Contains(primitives, "func (self *IButtonBase) RemoveClick(token syswinrt.EventRegistrationToken) error") {
		t.Error("IButtonBase.RemoveClick is not emitted")
	}

	delegates := source(t, "ui/xaml/controls/primitives/primitives_delegates.go")
	if !strings.Contains(delegates, "func NewRoutedEventHandler(fn func(") {
		t.Error("no RoutedEventHandler constructor was grounded into the primitives package")
	}
	if !strings.Contains(delegates, "winrt.NewDelegate(IID_RoutedEventHandler, 2,") {
		t.Error("the handler does not build a 2-word delegate")
	}
}

// TestExternalReferencesUseThePrefixedAlias is the collision check at the level
// that matters: emitted source. An unprefixed alias here would be a compile error
// in any package importing both UI.Xaml.Interop namespaces.
func TestExternalReferencesUseThePrefixedAlias(t *testing.T) {
	xaml := source(t, "ui/xaml/xaml_interfaces.go")
	if !strings.Contains(xaml, `wrtfoundation "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"`) {
		t.Error("the Windows.Foundation import is missing or unprefixed")
	}
	if !strings.Contains(xaml, "wrtfoundation.Rect") {
		t.Error("no use of the external Rect type")
	}
	// Every generated file's imports must have distinct aliases AND distinct
	// paths. Duplicate either way does not compile.
	result := emit(t)
	for path, content := range result.files {
		block, ok := importBlock(content)
		if !ok {
			continue
		}
		aliases, paths := map[string]bool{}, map[string]bool{}
		for _, line := range strings.Split(block, "\n") {
			alias, importPath, ok := parseImportLine(line)
			if !ok {
				continue
			}
			if aliases[alias] {
				t.Errorf("%s imports two packages as %q", path, alias)
			}
			if paths[importPath] {
				t.Errorf("%s imports %s twice", path, importPath)
			}
			aliases[alias], paths[importPath] = true, true
		}
	}
}

// buildConstraint returns the //go:build line's expression.
func buildConstraint(content string) (string, bool) {
	for _, line := range strings.Split(content, "\n") {
		if expression, found := strings.CutPrefix(strings.TrimSpace(line), "//go:build "); found {
			return strings.TrimSpace(expression), true
		}
	}
	return "", false
}

// importBlock extracts the parenthesised import block's contents.
func importBlock(content string) (string, bool) {
	start := strings.Index(content, "import (\n")
	if start < 0 {
		return "", false
	}
	rest := content[start+len("import (\n"):]
	end := strings.Index(rest, "\n)")
	if end < 0 {
		return "", false
	}
	return rest[:end], true
}

// parseImportLine reads one import line into its alias and path, deriving the
// implicit alias from the path's last element when none is written.
func parseImportLine(line string) (alias, path string, ok bool) {
	line = strings.TrimSpace(line)
	if line == "" {
		return "", "", false
	}
	if quoted := strings.HasPrefix(line, `"`); quoted {
		path = strings.Trim(line, `"`)
		if i := strings.LastIndex(path, "/"); i >= 0 {
			return path[i+1:], path, true
		}
		return path, path, true
	}
	alias, remainder, found := strings.Cut(line, " ")
	if !found {
		return "", "", false
	}
	return alias, strings.Trim(remainder, `"`), true
}

// TestSkippedMembersKeepTheirSlots is the invariant that makes a partial
// projection safe. A skipped member must leave an audit comment at its own slot and
// never renumber the ones after it, or every later method on that interface would
// dispatch to the wrong function.
func TestSkippedMembersKeepTheirSlots(t *testing.T) {
	result := emit(t)
	var checked int
	for path, content := range result.files {
		if !strings.HasSuffix(path, "_interfaces.go") && !strings.HasSuffix(path, "_pinterfaces.go") {
			continue
		}
		for _, line := range strings.Split(content, "\n") {
			if !strings.HasPrefix(strings.TrimSpace(line), "// slot ") || !strings.Contains(line, "skipped:") {
				continue
			}
			checked++
			// The comment has to carry a reason, or it says nothing useful about
			// why the slot is empty.
			if strings.HasSuffix(strings.TrimSpace(line), "skipped:") {
				t.Errorf("%s: a slot comment gives no reason: %s", path, strings.TrimSpace(line))
			}
		}
	}
	if checked == 0 {
		t.Error("no skipped-slot comments found; with 750 diagnostics some members must be skipped")
	}
	t.Logf("%d skipped slots, each with a reason", checked)
}

// TestNoForeignTypeReachesTheOutput is the WebView2 guarantee. A reference into a
// namespace with no Go bindings must be absent, never turned into an opaque word: a
// binding that compiles and then crashes is worse than one that is not there.
func TestNoForeignTypeReachesTheOutput(t *testing.T) {
	result := emit(t)
	for path, content := range result.files {
		if strings.Contains(content, "WebView2.Core") && !strings.Contains(path, "controls") {
			t.Errorf("%s mentions Microsoft.Web.WebView2.Core outside a skip comment", path)
		}
		if strings.Contains(content, "CoreWebView2Environment") &&
			!strings.Contains(content, "skipped:") {
			t.Errorf("%s names a WebView2 type outside a skip comment", path)
		}
	}
	// And it is diagnosed under its own key, so it can never be confused with an
	// unresolved reference — which would mean a broken metadata pin.
	var foreign int
	for _, diagnostic := range result.generator.Diagnostics {
		if strings.HasPrefix(diagnostic, "foreign-type-skipped:") {
			foreign++
		}
	}
	if foreign == 0 {
		t.Error("no foreign-type-skipped diagnostics; is the WebView2 reference still there?")
	}
}

// TestNoUnresolvedReferencesSurvive separates the two kinds of absence. A
// degradation with a documented cause is expected at this scale; an
// unresolved-typeref means the metadata pin is broken, and no generator change
// fixes it.
func TestNoUnresolvedReferencesSurvive(t *testing.T) {
	result := emit(t)
	var unresolved []string
	for _, diagnostic := range result.generator.Diagnostics {
		for _, bad := range []string{"unresolved-typeref:", "unknown-target-kind:", "unknown-native-type:", "malformed-guid:", "interface-missing-guid:"} {
			if strings.HasPrefix(diagnostic, bad) {
				unresolved = append(unresolved, diagnostic)
			}
		}
	}
	if len(unresolved) > 0 {
		limit := min(len(unresolved), 10)
		t.Errorf("%d references did not resolve at emit: %v", len(unresolved), unresolved[:limit])
	}
}

// TestEmissionIsDeterministic is what CI enforces over the committed tree. Checked
// here too, because the gather layer iterates maps in several places and the
// failure — a diff on an unchanged input — is confusing to diagnose from CI alone.
func TestEmissionIsDeterministic(t *testing.T) {
	externalSet, err := external.Load("")
	if err != nil {
		t.Fatalf("loading the Windows.* universe: %v", err)
	}
	registry, err := pipeline.Load(metadataDir, externalSet)
	if err != nil {
		t.Fatalf("loading the committed metadata: %v", err)
	}
	// A few namespaces rather than all 77: enough to cover cross-namespace
	// references, grounded delegates and instantiations, without emitting the tree
	// twice more.
	filter := map[string]bool{
		"Microsoft.UI.Xaml":                     true,
		"Microsoft.UI.Xaml.Controls":            true,
		"Microsoft.UI.Xaml.Controls.Primitives": true,
	}
	run := func() map[string]string {
		dir := t.TempDir()
		generator := New(registry, modulePath, dir)
		if _, err := generator.EmitAll(filter); err != nil {
			t.Fatalf("EmitAll: %v", err)
		}
		files := map[string]string{}
		walkErr := filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
			if err != nil || entry.IsDir() {
				return err
			}
			content, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			relative, _ := filepath.Rel(dir, path)
			files[filepath.ToSlash(relative)] = string(content)
			return nil
		})
		if walkErr != nil {
			t.Fatal(walkErr)
		}
		return files
	}
	first, second := run(), run()
	if len(first) != len(second) {
		t.Fatalf("%d files then %d", len(first), len(second))
	}
	for path, content := range first {
		if second[path] != content {
			t.Errorf("%s differs between two runs on identical input", path)
		}
	}
}

// TestPruningLeavesHandWrittenFilesAlone protects the one thing a self-cleaning
// generator could destroy. Pruning matches on the DO-NOT-EDIT header precisely so
// that anything else in the output tree survives.
func TestPruningLeavesHandWrittenFilesAlone(t *testing.T) {
	externalSet, err := external.Load("")
	if err != nil {
		t.Fatalf("loading the Windows.* universe: %v", err)
	}
	registry, err := pipeline.Load(metadataDir, externalSet)
	if err != nil {
		t.Fatalf("loading the committed metadata: %v", err)
	}
	dir := t.TempDir()
	packageDir := filepath.Join(dir, "ui", "xaml")
	if err := os.MkdirAll(packageDir, 0o755); err != nil {
		t.Fatal(err)
	}
	handWritten := filepath.Join(packageDir, "helpers.go")
	if err := os.WriteFile(handWritten, []byte("package xaml\n\n// Kept.\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// A stale generated file, which SHOULD go.
	stale := filepath.Join(packageDir, "xaml_gone.go")
	staleContent := "// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.\n\npackage xaml\n"
	if err := os.WriteFile(stale, []byte(staleContent), 0o644); err != nil {
		t.Fatal(err)
	}

	generator := New(registry, modulePath, dir)
	if _, err := generator.EmitAll(map[string]bool{"Microsoft.UI.Xaml": true}); err != nil {
		t.Fatalf("EmitAll: %v", err)
	}
	if _, err := os.Stat(handWritten); err != nil {
		t.Errorf("the hand-written file was pruned: %v", err)
	}
	if _, err := os.Stat(stale); err == nil {
		t.Error("the stale generated file survived pruning")
	}
}

// TestInheritedInterfacesAreReachable is the whole point of the base-class
// projection, stated on the type it was built for.
//
// A class's InterfaceImpl list names only the interfaces declared at its own level.
// Button's is [IButton], carrying Flyout and nothing else — so without walking
// Extends, a generated Button could not reach Content (IContentControl),
// Visibility (IUIElement) or Margin (IFrameworkElement), which is to say anything
// a button is used for.
func TestInheritedInterfacesAreReachable(t *testing.T) {
	classes := source(t, "ui/xaml/controls/controls_classes.go")
	block := classBlock(classes, "Button")
	if block == "" {
		t.Fatal("no Button class block found")
	}
	for _, accessor := range []string{
		"AsContentControl",   // Content
		"AsControl",          // FontSize, Background
		"AsFrameworkElement", // Margin, Width, Height
		"AsUIElement",        // Visibility, Opacity
		"AsDependencyObject", // GetValue/SetValue
	} {
		if !strings.Contains(block, "func (self *Button) "+accessor+"()") {
			t.Errorf("Button has no %s accessor", accessor)
		}
	}
	// Each inherited accessor says where it came from, so a reader can tell an
	// inherited member from a declared one without consulting the metadata.
	if !strings.Contains(block, "// Inherited from Microsoft.UI.Xaml.FrameworkElement.") {
		t.Error("inherited accessors do not record the base class they came from")
	}
	// Cross-namespace inheritance has to use the import alias, not a bare name.
	if !strings.Contains(block, "(*uixaml.IUIElement, error)") {
		t.Error("the inherited UIElement accessor is not package-qualified")
	}
}

// classBlock extracts the source from a class's type declaration up to the next
// package-level declaration that is not one of its methods.
func classBlock(content, typeName string) string {
	start := strings.Index(content, "type "+typeName+" struct {")
	if start < 0 {
		return ""
	}
	rest := content[start:]
	// The class's own methods and constructors run until the next type declaration.
	if end := strings.Index(rest[1:], "\ntype "); end >= 0 {
		return rest[:end+1]
	}
	return rest
}

// TestBaseChainIsAccountedForInTheImportGraph is the regression this phase created
// and had to fix. Projecting a base class's interfaces onto a derived class adds
// import edges that appear nowhere in the derived namespace's own TypeRefs, so the
// cycle breaker has to know about them — otherwise it severs by an incomplete graph
// and the output does not compile. It did exactly that once.
//
// ComputeBlockedImports and the class emitter now share the Registry's chain walk,
// which is what keeps the two graphs the same graph.
func TestBaseChainIsAccountedForInTheImportGraph(t *testing.T) {
	result := emit(t)
	// Every emitted file must import only packages that exist in the tree, and the
	// tree must be acyclic — which `go build` proves, but this catches the
	// generator-side cause: an inherited accessor whose package was never imported.
	for path, content := range result.files {
		if !strings.HasSuffix(path, "_classes.go") {
			continue
		}
		block, hasImports := importBlock(content)
		aliases := map[string]bool{}
		if hasImports {
			for _, line := range strings.Split(block, "\n") {
				if alias, _, ok := parseImportLine(line); ok {
					aliases[alias] = true
				}
			}
		}
		// Any qualified type in a query method's return has to name an imported
		// alias.
		for _, line := range strings.Split(content, "\n") {
			_, after, found := strings.Cut(line, ") (*")
			if !found || !strings.HasPrefix(strings.TrimSpace(line), "func (self *") {
				continue
			}
			qualified, _, ok := strings.Cut(after, ", error)")
			if !ok {
				continue
			}
			alias, _, qualifiedName := strings.Cut(qualified, ".")
			if !qualifiedName {
				continue // package-local, nothing to import
			}
			if !aliases[alias] {
				t.Errorf("%s returns %s but does not import %q", path, qualified, alias)
			}
		}
	}
}

// TestArrayShapesLowerToTheirABI pins the three conformant-array shapes in emitted
// source, because they are the ones where a wrong lowering compiles and then corrupts
// memory rather than failing.
//
// A WinRT array crosses as TWO words. Which two depends on who allocates:
//
//	[in] T[]        (UINT32 size,  T*  value)  caller owns
//	[out] T[]       (UINT32 size,  T*  value)  caller allocates, callee fills
//	[out] T[]&      (UINT32* size, T** value)  callee allocates, caller frees
//	T[] as retval   (UINT32* size, T** value)  same, in retval position
//
// The metadata distinguishes the last two from the middle one by ELEMENT_TYPE_BYREF
// alone. Pass a count where the callee expects a pointer and it writes through the
// count.
func TestArrayShapesLowerToTheirABI(t *testing.T) {
	pinterfaces := source(t, "ui/xaml/xaml_pinterfaces.go")

	// [in] T[] — count then data, and an empty slice passes (0, NULL) rather than
	// indexing element zero of a slice that has none.
	replaceAll := methodBody(pinterfaces, "func (self *IVectorOfResourceDictionary) ReplaceAll(")
	if replaceAll == "" {
		t.Fatal("IVectorOfResourceDictionary.ReplaceAll was not emitted")
	}
	for _, want := range []string{
		"items []*IResourceDictionary",
		"_itemsSize := uintptr(len(items))",
		"if len(items) > 0 {",
		"_itemsSize, _itemsData",
	} {
		if !strings.Contains(replaceAll, want) {
			t.Errorf("ReplaceAll is missing %q:\n%s", want, replaceAll)
		}
	}

	// [out] T[] fill — the caller supplies the buffer, so the Go signature TAKES a
	// slice and returns the count actually written. Identical arg words to the
	// input case.
	getMany := methodBody(pinterfaces, "func (self *IVectorOfResourceDictionary) GetMany(")
	if getMany == "" {
		t.Fatal("IVectorOfResourceDictionary.GetMany was not emitted")
	}
	if !strings.Contains(getMany, "items []*IResourceDictionary) (uint32, error)") {
		t.Errorf("GetMany does not take a caller-allocated slice and return a count:\n%s", getMany)
	}
	if strings.Contains(getMany, "CoTaskMemFree") {
		t.Error("GetMany frees the buffer, but the caller owns it in a fill array")
	}

	// A retval array — callee-allocated, so the body copies out and frees, and it
	// must short-circuit before touching the buffer on failure.
	result := emit(t)
	var found string
	for path, content := range result.files {
		if strings.Contains(content, "systemcom.CoTaskMemFree") {
			found = path
			for _, want := range []string{
				"resultSize := new(uint32)",
				"if *result == nil || *resultSize == 0 {",
				"copy(items, unsafe.Slice(*result, *resultSize))",
				"systemcom.CoTaskMemFree(unsafe.Pointer(*result))",
			} {
				if !strings.Contains(content, want) {
					t.Errorf("%s has a retval array but is missing %q", path, want)
				}
			}
			// Freeing before the HRESULT is checked would free a buffer that was
			// never allocated.
			freeAt := strings.Index(content, "systemcom.CoTaskMemFree")
			checkAt := strings.Index(content, "if err := win32.ErrIfFailed")
			if checkAt < 0 || checkAt > freeAt {
				t.Errorf("%s frees the retval buffer before checking the HRESULT", path)
			}
			break
		}
	}
	if found == "" {
		t.Error("no retval conformant array was emitted anywhere in the tree")
	} else {
		t.Logf("retval array shape verified in %s", found)
	}
}

// methodBody returns the source of one function, from its signature to its closing
// brace at column zero.
func methodBody(content, signature string) string {
	start := strings.Index(content, signature)
	if start < 0 {
		return ""
	}
	rest := content[start:]
	if end := strings.Index(rest, "\n}\n"); end >= 0 {
		return rest[:end+3]
	}
	return rest
}

// TestArrayElementsThatCannotConvertAreSkipped is the other half: an element whose Go
// form is not byte-identical to its ABI form must leave a slot comment, not a direct
// slice view over reinterpreted bytes.
func TestArrayElementsThatCannotConvertAreSkipped(t *testing.T) {
	result := emit(t)
	var elementSkips, receiveSkips int
	for _, diagnostic := range result.generator.Diagnostics {
		switch {
		case strings.HasPrefix(diagnostic, "array-element-skipped:"):
			elementSkips++
		case strings.HasPrefix(diagnostic, "array-receive-param-skipped:"):
			receiveSkips++
		case strings.HasPrefix(diagnostic, "array-param-skipped:"):
			t.Errorf("a member is still skipped wholesale for being an array: %s", diagnostic)
		}
	}
	if elementSkips == 0 {
		t.Error("no array-element-skipped diagnostics; HSTRING elements should still be refused")
	}
	// Exactly one byref array exists in the committed metadata. If that changes, the
	// promote-out-param-to-return path stops being a one-off and is worth building.
	if receiveSkips != 1 {
		t.Errorf("%d callee-allocated array parameters skipped, want 1 "+
			"(a second one makes the receive-param path worth implementing)", receiveSkips)
	}
}
