// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

// Package documents binds the Microsoft.UI.Xaml.Documents API surface of the Windows App SDK.
package documents
