// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package documents

import (
	"unsafe"

	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	uicomposition "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/ui/composition"
	uixaml "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/ui/xaml"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// Block is the Microsoft.UI.Xaml.Documents.Block runtime class, surfaced through its
// default interface IBlock. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Block struct {
	IBlock
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Block) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Block) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Block) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// BlockStatics returns the Microsoft.UI.Xaml.Documents.IBlockStatics statics of the
// Microsoft.UI.Xaml.Documents.Block runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func BlockStatics() (*IBlockStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Block", &IID_IBlockStatics)
	if err != nil {
		return nil, err
	}
	return (*IBlockStatics)(unsafe.Pointer(factory)), nil
}

// NewBlock constructs a Microsoft.UI.Xaml.Documents.Block instance through
// Microsoft.UI.Xaml.Documents.IBlockFactory.CreateInstance with a NULL controlling outer: the
// class is created as itself, not derived from (instantiate-only
// composition). The activation factory is fetched per call (a factory cache
// is a future optimization).
func NewBlock() (*Block, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Block", &IID_IBlockFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IBlockFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	inner := new(*syswinrt.IInspectable)
	instance, err := factory.CreateInstance(nil, inner)
	if err != nil {
		return nil, err
	}
	if *inner != nil {
		// Under null-outer composition the inner is a SECOND reference to
		// the same object instance carries: drop it.
		(*inner).Release()
	}
	return (*Block)(unsafe.Pointer(instance)), nil
}

// Bold is the Microsoft.UI.Xaml.Documents.Bold runtime class, surfaced through its
// default interface IBold. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Bold struct {
	IBold
}

// NewBold activates Microsoft.UI.Xaml.Documents.Bold through its default
// constructor.
func NewBold() (*Bold, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.Bold")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[Bold](unsafe.Pointer(instance), &IID_IBold)
}

// AsSpan queries the instance's ISpan interface.
// Inherited from Microsoft.UI.Xaml.Documents.Span.
// The returned reference is owned by the caller.
func (self *Bold) AsSpan() (*ISpan, error) {
	return winrt.QueryInterface[ISpan](unsafe.Pointer(self), &IID_ISpan)
}

// AsInline queries the instance's IInline interface.
// Inherited from Microsoft.UI.Xaml.Documents.Inline.
// The returned reference is owned by the caller.
func (self *Bold) AsInline() (*IInline, error) {
	return winrt.QueryInterface[IInline](unsafe.Pointer(self), &IID_IInline)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Bold) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Bold) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Bold) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// Glyphs is the Microsoft.UI.Xaml.Documents.Glyphs runtime class, surfaced through its
// default interface IGlyphs. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Glyphs struct {
	IGlyphs
}

// NewGlyphs activates Microsoft.UI.Xaml.Documents.Glyphs through its default
// constructor.
func NewGlyphs() (*Glyphs, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.Glyphs")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[Glyphs](unsafe.Pointer(instance), &IID_IGlyphs)
}

// AsFrameworkElement queries the instance's uixaml.IFrameworkElement interface.
// Inherited from Microsoft.UI.Xaml.FrameworkElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsFrameworkElement() (*uixaml.IFrameworkElement, error) {
	return winrt.QueryInterface[uixaml.IFrameworkElement](unsafe.Pointer(self), &uixaml.IID_IFrameworkElement)
}

// AsFrameworkElementProtected queries the instance's uixaml.IFrameworkElementProtected interface.
// Inherited from Microsoft.UI.Xaml.FrameworkElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsFrameworkElementProtected() (*uixaml.IFrameworkElementProtected, error) {
	return winrt.QueryInterface[uixaml.IFrameworkElementProtected](unsafe.Pointer(self), &uixaml.IID_IFrameworkElementProtected)
}

// AsFrameworkElementOverrides queries the instance's uixaml.IFrameworkElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.FrameworkElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsFrameworkElementOverrides() (*uixaml.IFrameworkElementOverrides, error) {
	return winrt.QueryInterface[uixaml.IFrameworkElementOverrides](unsafe.Pointer(self), &uixaml.IID_IFrameworkElementOverrides)
}

// AsUIElement queries the instance's uixaml.IUIElement interface.
// Inherited from Microsoft.UI.Xaml.UIElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsUIElement() (*uixaml.IUIElement, error) {
	return winrt.QueryInterface[uixaml.IUIElement](unsafe.Pointer(self), &uixaml.IID_IUIElement)
}

// AsUIElementProtected queries the instance's uixaml.IUIElementProtected interface.
// Inherited from Microsoft.UI.Xaml.UIElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsUIElementProtected() (*uixaml.IUIElementProtected, error) {
	return winrt.QueryInterface[uixaml.IUIElementProtected](unsafe.Pointer(self), &uixaml.IID_IUIElementProtected)
}

// AsUIElementOverrides queries the instance's uixaml.IUIElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.UIElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsUIElementOverrides() (*uixaml.IUIElementOverrides, error) {
	return winrt.QueryInterface[uixaml.IUIElementOverrides](unsafe.Pointer(self), &uixaml.IID_IUIElementOverrides)
}

// AsAnimationObject queries the instance's uicomposition.IAnimationObject interface.
// Inherited from Microsoft.UI.Xaml.UIElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsAnimationObject() (*uicomposition.IAnimationObject, error) {
	return winrt.QueryInterface[uicomposition.IAnimationObject](unsafe.Pointer(self), &uicomposition.IID_IAnimationObject)
}

// AsVisualElement queries the instance's uicomposition.IVisualElement interface.
// Inherited from Microsoft.UI.Xaml.UIElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsVisualElement() (*uicomposition.IVisualElement, error) {
	return winrt.QueryInterface[uicomposition.IVisualElement](unsafe.Pointer(self), &uicomposition.IID_IVisualElement)
}

// AsVisualElement2 queries the instance's uicomposition.IVisualElement2 interface.
// Inherited from Microsoft.UI.Xaml.UIElement.
// The returned reference is owned by the caller.
func (self *Glyphs) AsVisualElement2() (*uicomposition.IVisualElement2, error) {
	return winrt.QueryInterface[uicomposition.IVisualElement2](unsafe.Pointer(self), &uicomposition.IID_IVisualElement2)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Glyphs) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// GlyphsStatics returns the Microsoft.UI.Xaml.Documents.IGlyphsStatics statics of the
// Microsoft.UI.Xaml.Documents.Glyphs runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func GlyphsStatics() (*IGlyphsStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Glyphs", &IID_IGlyphsStatics)
	if err != nil {
		return nil, err
	}
	return (*IGlyphsStatics)(unsafe.Pointer(factory)), nil
}

// Hyperlink is the Microsoft.UI.Xaml.Documents.Hyperlink runtime class, surfaced through its
// default interface IHyperlink. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Hyperlink struct {
	IHyperlink
}

// NewHyperlink activates Microsoft.UI.Xaml.Documents.Hyperlink through its default
// constructor.
func NewHyperlink() (*Hyperlink, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.Hyperlink")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[Hyperlink](unsafe.Pointer(instance), &IID_IHyperlink)
}

// AsSpan queries the instance's ISpan interface.
// Inherited from Microsoft.UI.Xaml.Documents.Span.
// The returned reference is owned by the caller.
func (self *Hyperlink) AsSpan() (*ISpan, error) {
	return winrt.QueryInterface[ISpan](unsafe.Pointer(self), &IID_ISpan)
}

// AsInline queries the instance's IInline interface.
// Inherited from Microsoft.UI.Xaml.Documents.Inline.
// The returned reference is owned by the caller.
func (self *Hyperlink) AsInline() (*IInline, error) {
	return winrt.QueryInterface[IInline](unsafe.Pointer(self), &IID_IInline)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Hyperlink) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Hyperlink) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Hyperlink) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// HyperlinkStatics returns the Microsoft.UI.Xaml.Documents.IHyperlinkStatics statics of the
// Microsoft.UI.Xaml.Documents.Hyperlink runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func HyperlinkStatics() (*IHyperlinkStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Hyperlink", &IID_IHyperlinkStatics)
	if err != nil {
		return nil, err
	}
	return (*IHyperlinkStatics)(unsafe.Pointer(factory)), nil
}

// HyperlinkClickEventArgs is the Microsoft.UI.Xaml.Documents.HyperlinkClickEventArgs runtime class, surfaced through its
// default interface IHyperlinkClickEventArgs. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type HyperlinkClickEventArgs struct {
	IHyperlinkClickEventArgs
}

// AsRoutedEventArgs queries the instance's uixaml.IRoutedEventArgs interface.
// Inherited from Microsoft.UI.Xaml.RoutedEventArgs.
// The returned reference is owned by the caller.
func (self *HyperlinkClickEventArgs) AsRoutedEventArgs() (*uixaml.IRoutedEventArgs, error) {
	return winrt.QueryInterface[uixaml.IRoutedEventArgs](unsafe.Pointer(self), &uixaml.IID_IRoutedEventArgs)
}

// Inline is the Microsoft.UI.Xaml.Documents.Inline runtime class, surfaced through its
// default interface IInline. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Inline struct {
	IInline
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Inline) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Inline) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Inline) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// NewInline constructs a Microsoft.UI.Xaml.Documents.Inline instance through
// Microsoft.UI.Xaml.Documents.IInlineFactory.CreateInstance with a NULL controlling outer: the
// class is created as itself, not derived from (instantiate-only
// composition). The activation factory is fetched per call (a factory cache
// is a future optimization).
func NewInline() (*Inline, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Inline", &IID_IInlineFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IInlineFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	inner := new(*syswinrt.IInspectable)
	instance, err := factory.CreateInstance(nil, inner)
	if err != nil {
		return nil, err
	}
	if *inner != nil {
		// Under null-outer composition the inner is a SECOND reference to
		// the same object instance carries: drop it.
		(*inner).Release()
	}
	return (*Inline)(unsafe.Pointer(instance)), nil
}

// InlineUIContainer is the Microsoft.UI.Xaml.Documents.InlineUIContainer runtime class, surfaced through its
// default interface IInlineUIContainer. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type InlineUIContainer struct {
	IInlineUIContainer
}

// NewInlineUIContainer activates Microsoft.UI.Xaml.Documents.InlineUIContainer through its default
// constructor.
func NewInlineUIContainer() (*InlineUIContainer, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.InlineUIContainer")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[InlineUIContainer](unsafe.Pointer(instance), &IID_IInlineUIContainer)
}

// AsInline queries the instance's IInline interface.
// Inherited from Microsoft.UI.Xaml.Documents.Inline.
// The returned reference is owned by the caller.
func (self *InlineUIContainer) AsInline() (*IInline, error) {
	return winrt.QueryInterface[IInline](unsafe.Pointer(self), &IID_IInline)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *InlineUIContainer) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *InlineUIContainer) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *InlineUIContainer) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// Italic is the Microsoft.UI.Xaml.Documents.Italic runtime class, surfaced through its
// default interface IItalic. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Italic struct {
	IItalic
}

// NewItalic activates Microsoft.UI.Xaml.Documents.Italic through its default
// constructor.
func NewItalic() (*Italic, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.Italic")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[Italic](unsafe.Pointer(instance), &IID_IItalic)
}

// AsSpan queries the instance's ISpan interface.
// Inherited from Microsoft.UI.Xaml.Documents.Span.
// The returned reference is owned by the caller.
func (self *Italic) AsSpan() (*ISpan, error) {
	return winrt.QueryInterface[ISpan](unsafe.Pointer(self), &IID_ISpan)
}

// AsInline queries the instance's IInline interface.
// Inherited from Microsoft.UI.Xaml.Documents.Inline.
// The returned reference is owned by the caller.
func (self *Italic) AsInline() (*IInline, error) {
	return winrt.QueryInterface[IInline](unsafe.Pointer(self), &IID_IInline)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Italic) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Italic) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Italic) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// LineBreak is the Microsoft.UI.Xaml.Documents.LineBreak runtime class, surfaced through its
// default interface ILineBreak. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type LineBreak struct {
	ILineBreak
}

// NewLineBreak activates Microsoft.UI.Xaml.Documents.LineBreak through its default
// constructor.
func NewLineBreak() (*LineBreak, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.LineBreak")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[LineBreak](unsafe.Pointer(instance), &IID_ILineBreak)
}

// AsInline queries the instance's IInline interface.
// Inherited from Microsoft.UI.Xaml.Documents.Inline.
// The returned reference is owned by the caller.
func (self *LineBreak) AsInline() (*IInline, error) {
	return winrt.QueryInterface[IInline](unsafe.Pointer(self), &IID_IInline)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *LineBreak) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *LineBreak) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *LineBreak) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// Paragraph is the Microsoft.UI.Xaml.Documents.Paragraph runtime class, surfaced through its
// default interface IParagraph. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Paragraph struct {
	IParagraph
}

// NewParagraph activates Microsoft.UI.Xaml.Documents.Paragraph through its default
// constructor.
func NewParagraph() (*Paragraph, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.Paragraph")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[Paragraph](unsafe.Pointer(instance), &IID_IParagraph)
}

// AsBlock queries the instance's IBlock interface.
// Inherited from Microsoft.UI.Xaml.Documents.Block.
// The returned reference is owned by the caller.
func (self *Paragraph) AsBlock() (*IBlock, error) {
	return winrt.QueryInterface[IBlock](unsafe.Pointer(self), &IID_IBlock)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Paragraph) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Paragraph) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Paragraph) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// ParagraphStatics returns the Microsoft.UI.Xaml.Documents.IParagraphStatics statics of the
// Microsoft.UI.Xaml.Documents.Paragraph runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func ParagraphStatics() (*IParagraphStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Paragraph", &IID_IParagraphStatics)
	if err != nil {
		return nil, err
	}
	return (*IParagraphStatics)(unsafe.Pointer(factory)), nil
}

// Run is the Microsoft.UI.Xaml.Documents.Run runtime class, surfaced through its
// default interface IRun. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Run struct {
	IRun
}

// NewRun activates Microsoft.UI.Xaml.Documents.Run through its default
// constructor.
func NewRun() (*Run, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.Run")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[Run](unsafe.Pointer(instance), &IID_IRun)
}

// AsInline queries the instance's IInline interface.
// Inherited from Microsoft.UI.Xaml.Documents.Inline.
// The returned reference is owned by the caller.
func (self *Run) AsInline() (*IInline, error) {
	return winrt.QueryInterface[IInline](unsafe.Pointer(self), &IID_IInline)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Run) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Run) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Run) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// RunStatics returns the Microsoft.UI.Xaml.Documents.IRunStatics statics of the
// Microsoft.UI.Xaml.Documents.Run runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func RunStatics() (*IRunStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Run", &IID_IRunStatics)
	if err != nil {
		return nil, err
	}
	return (*IRunStatics)(unsafe.Pointer(factory)), nil
}

// Span is the Microsoft.UI.Xaml.Documents.Span runtime class, surfaced through its
// default interface ISpan. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Span struct {
	ISpan
}

// AsInline queries the instance's IInline interface.
// Inherited from Microsoft.UI.Xaml.Documents.Inline.
// The returned reference is owned by the caller.
func (self *Span) AsInline() (*IInline, error) {
	return winrt.QueryInterface[IInline](unsafe.Pointer(self), &IID_IInline)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Span) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Span) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Span) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// NewSpan constructs a Microsoft.UI.Xaml.Documents.Span instance through
// Microsoft.UI.Xaml.Documents.ISpanFactory.CreateInstance with a NULL controlling outer: the
// class is created as itself, not derived from (instantiate-only
// composition). The activation factory is fetched per call (a factory cache
// is a future optimization).
func NewSpan() (*Span, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Span", &IID_ISpanFactory)
	if err != nil {
		return nil, err
	}
	factory := (*ISpanFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	inner := new(*syswinrt.IInspectable)
	instance, err := factory.CreateInstance(nil, inner)
	if err != nil {
		return nil, err
	}
	if *inner != nil {
		// Under null-outer composition the inner is a SECOND reference to
		// the same object instance carries: drop it.
		(*inner).Release()
	}
	return (*Span)(unsafe.Pointer(instance)), nil
}

// TextElement is the Microsoft.UI.Xaml.Documents.TextElement runtime class, surfaced through its
// default interface ITextElement. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TextElement struct {
	ITextElement
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// The returned reference is owned by the caller.
func (self *TextElement) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *TextElement) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// TextElementStatics returns the Microsoft.UI.Xaml.Documents.ITextElementStatics statics of the
// Microsoft.UI.Xaml.Documents.TextElement runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func TextElementStatics() (*ITextElementStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.TextElement", &IID_ITextElementStatics)
	if err != nil {
		return nil, err
	}
	return (*ITextElementStatics)(unsafe.Pointer(factory)), nil
}

// TextHighlighter is the Microsoft.UI.Xaml.Documents.TextHighlighter runtime class, surfaced through its
// default interface ITextHighlighter. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TextHighlighter struct {
	ITextHighlighter
}

// TextHighlighterStatics returns the Microsoft.UI.Xaml.Documents.ITextHighlighterStatics statics of the
// Microsoft.UI.Xaml.Documents.TextHighlighter runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func TextHighlighterStatics() (*ITextHighlighterStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.TextHighlighter", &IID_ITextHighlighterStatics)
	if err != nil {
		return nil, err
	}
	return (*ITextHighlighterStatics)(unsafe.Pointer(factory)), nil
}

// NewTextHighlighter constructs a Microsoft.UI.Xaml.Documents.TextHighlighter instance through
// Microsoft.UI.Xaml.Documents.ITextHighlighterFactory.CreateInstance with a NULL controlling outer: the
// class is created as itself, not derived from (instantiate-only
// composition). The activation factory is fetched per call (a factory cache
// is a future optimization).
func NewTextHighlighter() (*TextHighlighter, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.TextHighlighter", &IID_ITextHighlighterFactory)
	if err != nil {
		return nil, err
	}
	factory := (*ITextHighlighterFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	inner := new(*syswinrt.IInspectable)
	instance, err := factory.CreateInstance(nil, inner)
	if err != nil {
		return nil, err
	}
	if *inner != nil {
		// Under null-outer composition the inner is a SECOND reference to
		// the same object instance carries: drop it.
		(*inner).Release()
	}
	return (*TextHighlighter)(unsafe.Pointer(instance)), nil
}

// TextHighlighterBase is the Microsoft.UI.Xaml.Documents.TextHighlighterBase runtime class, surfaced through its
// default interface ITextHighlighterBase. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TextHighlighterBase struct {
	ITextHighlighterBase
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *TextHighlighterBase) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}

// TextPointer is the Microsoft.UI.Xaml.Documents.TextPointer runtime class, surfaced through its
// default interface ITextPointer. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type TextPointer struct {
	ITextPointer
}

// Typography is the Microsoft.UI.Xaml.Documents.Typography runtime class, surfaced through its
// default interface ITypography. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Typography struct {
	ITypography
}

// TypographyStatics returns the Microsoft.UI.Xaml.Documents.ITypographyStatics statics of the
// Microsoft.UI.Xaml.Documents.Typography runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func TypographyStatics() (*ITypographyStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Xaml.Documents.Typography", &IID_ITypographyStatics)
	if err != nil {
		return nil, err
	}
	return (*ITypographyStatics)(unsafe.Pointer(factory)), nil
}

// Underline is the Microsoft.UI.Xaml.Documents.Underline runtime class, surfaced through its
// default interface IUnderline. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Underline struct {
	IUnderline
}

// NewUnderline activates Microsoft.UI.Xaml.Documents.Underline through its default
// constructor.
func NewUnderline() (*Underline, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Xaml.Documents.Underline")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[Underline](unsafe.Pointer(instance), &IID_IUnderline)
}

// AsSpan queries the instance's ISpan interface.
// Inherited from Microsoft.UI.Xaml.Documents.Span.
// The returned reference is owned by the caller.
func (self *Underline) AsSpan() (*ISpan, error) {
	return winrt.QueryInterface[ISpan](unsafe.Pointer(self), &IID_ISpan)
}

// AsInline queries the instance's IInline interface.
// Inherited from Microsoft.UI.Xaml.Documents.Inline.
// The returned reference is owned by the caller.
func (self *Underline) AsInline() (*IInline, error) {
	return winrt.QueryInterface[IInline](unsafe.Pointer(self), &IID_IInline)
}

// AsTextElement queries the instance's ITextElement interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Underline) AsTextElement() (*ITextElement, error) {
	return winrt.QueryInterface[ITextElement](unsafe.Pointer(self), &IID_ITextElement)
}

// AsTextElementOverrides queries the instance's ITextElementOverrides interface.
// Inherited from Microsoft.UI.Xaml.Documents.TextElement.
// The returned reference is owned by the caller.
func (self *Underline) AsTextElementOverrides() (*ITextElementOverrides, error) {
	return winrt.QueryInterface[ITextElementOverrides](unsafe.Pointer(self), &IID_ITextElementOverrides)
}

// AsDependencyObject queries the instance's uixaml.IDependencyObject interface.
// Inherited from Microsoft.UI.Xaml.DependencyObject.
// The returned reference is owned by the caller.
func (self *Underline) AsDependencyObject() (*uixaml.IDependencyObject, error) {
	return winrt.QueryInterface[uixaml.IDependencyObject](unsafe.Pointer(self), &uixaml.IID_IDependencyObject)
}
