// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package semanticsearch

// SemanticSearchContract is Microsoft.Windows.SemanticSearch.SemanticSearchContract.
type SemanticSearchContract struct {
}
