// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package semanticsearch

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// IEmbeddingVector is the WinRT interface Microsoft.Windows.SemanticSearch.IEmbeddingVector.
// IID: f80248aa-68e7-5de0-9166-b26e58935d34
// Exclusive to the Microsoft.Windows.SemanticSearch.EmbeddingVector runtime class.
type IEmbeddingVector struct {
	syswinrt.IInspectable
}

// IID_IEmbeddingVector is the interface identifier for IEmbeddingVector.
var IID_IEmbeddingVector = win32.GUID{Data1: 0xf80248aa, Data2: 0x68e7, Data3: 0x5de0, Data4: [8]byte{0x91, 0x66, 0xb2, 0x6e, 0x58, 0x93, 0x5d, 0x34}}

// slot 6: GetValues skipped: conformant array

// Count (propget get_Count) dispatches through IEmbeddingVector's vtable slot 7.
func (self *IEmbeddingVector) Count() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// VectorSpaceId (propget get_VectorSpaceId) dispatches through IEmbeddingVector's vtable slot 8.
func (self *IEmbeddingVector) VectorSpaceId() (win32.GUID, error) {
	result := new(win32.GUID)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IEmbeddingVectorFactory is the WinRT interface Microsoft.Windows.SemanticSearch.IEmbeddingVectorFactory.
// IID: 3a31ead7-1f01-5a4c-9c2e-9acfa6495cdd
// Exclusive to the Microsoft.Windows.SemanticSearch.EmbeddingVector runtime class.
type IEmbeddingVectorFactory struct {
	syswinrt.IInspectable
}

// IID_IEmbeddingVectorFactory is the interface identifier for IEmbeddingVectorFactory.
var IID_IEmbeddingVectorFactory = win32.GUID{Data1: 0x3a31ead7, Data2: 0x1f01, Data3: 0x5a4c, Data4: [8]byte{0x9c, 0x2e, 0x9a, 0xcf, 0xa6, 0x49, 0x5c, 0xdd}}

// slot 6: CreateInstance skipped: conformant array
