// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package text

import (
	"math"
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	windowsai "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/windows/ai"
	windowsaicontentsafety "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/windows/ai/contentsafety"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// IConversationItem is the WinRT interface Microsoft.Windows.AI.Text.IConversationItem.
// IID: 957b0b85-4d7e-5788-baae-af7cf256bb8e
// Exclusive to the Microsoft.Windows.AI.Text.ConversationItem runtime class.
type IConversationItem struct {
	syswinrt.IInspectable
}

// IID_IConversationItem is the interface identifier for IConversationItem.
var IID_IConversationItem = win32.GUID{Data1: 0x957b0b85, Data2: 0x4d7e, Data3: 0x5788, Data4: [8]byte{0xba, 0xae, 0xaf, 0x7c, 0xf2, 0x56, 0xbb, 0x8e}}

// Participant (propget get_Participant) dispatches through IConversationItem's vtable slot 6.
func (self *IConversationItem) Participant() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SetParticipant (propput put_Participant) dispatches through IConversationItem's vtable slot 7.
func (self *IConversationItem) SetParticipant(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// Message (propget get_Message) dispatches through IConversationItem's vtable slot 8.
func (self *IConversationItem) Message() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SetMessage (propput put_Message) dispatches through IConversationItem's vtable slot 9.
func (self *IConversationItem) SetMessage(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// IConversationSummaryOptions is the WinRT interface Microsoft.Windows.AI.Text.IConversationSummaryOptions.
// IID: 360bce9f-fd14-5d0e-bd24-fd78ed3038e6
// Exclusive to the Microsoft.Windows.AI.Text.ConversationSummaryOptions runtime class.
type IConversationSummaryOptions struct {
	syswinrt.IInspectable
}

// IID_IConversationSummaryOptions is the interface identifier for IConversationSummaryOptions.
var IID_IConversationSummaryOptions = win32.GUID{Data1: 0x360bce9f, Data2: 0xfd14, Data3: 0x5d0e, Data4: [8]byte{0xbd, 0x24, 0xfd, 0x78, 0xed, 0x30, 0x38, 0xe6}}

// InputKind (propget get_InputKind) dispatches through IConversationSummaryOptions's vtable slot 6.
func (self *IConversationSummaryOptions) InputKind() (InputKind, error) {
	result := new(InputKind)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetInputKind (propput put_InputKind) dispatches through IConversationSummaryOptions's vtable slot 7.
func (self *IConversationSummaryOptions) SetInputKind(value InputKind) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// IncludeMessageCitations (propget get_IncludeMessageCitations) dispatches through IConversationSummaryOptions's vtable slot 8.
func (self *IConversationSummaryOptions) IncludeMessageCitations() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetIncludeMessageCitations (propput put_IncludeMessageCitations) dispatches through IConversationSummaryOptions's vtable slot 9.
func (self *IConversationSummaryOptions) SetIncludeMessageCitations(value bool) error {
	_value := uintptr(0)
	if value {
		_value = 1
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), _value)
	return win32.ErrIfFailed(int32(r1))
}

// IncludeParticipantAttribution (propget get_IncludeParticipantAttribution) dispatches through IConversationSummaryOptions's vtable slot 10.
func (self *IConversationSummaryOptions) IncludeParticipantAttribution() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetIncludeParticipantAttribution (propput put_IncludeParticipantAttribution) dispatches through IConversationSummaryOptions's vtable slot 11.
func (self *IConversationSummaryOptions) SetIncludeParticipantAttribution(value bool) error {
	_value := uintptr(0)
	if value {
		_value = 1
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), _value)
	return win32.ErrIfFailed(int32(r1))
}

// MaxKeyPoints (propget get_MaxKeyPoints) dispatches through IConversationSummaryOptions's vtable slot 12.
func (self *IConversationSummaryOptions) MaxKeyPoints() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetMaxKeyPoints (propput put_MaxKeyPoints) dispatches through IConversationSummaryOptions's vtable slot 13.
func (self *IConversationSummaryOptions) SetMaxKeyPoints(value uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// Language (propget get_Language) dispatches through IConversationSummaryOptions's vtable slot 14.
func (self *IConversationSummaryOptions) Language() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// SetLanguage (propput put_Language) dispatches through IConversationSummaryOptions's vtable slot 15.
func (self *IConversationSummaryOptions) SetLanguage(value string) error {
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return err
	}
	defer hValue.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)), uintptr(hValue.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// IGenerateStructuredJsonResponseResult is the WinRT interface Microsoft.Windows.AI.Text.IGenerateStructuredJsonResponseResult.
// IID: 1cfe5f4c-897a-5692-b9ae-ccb54eda14c5
// Exclusive to the Microsoft.Windows.AI.Text.GenerateStructuredJsonResponseResult runtime class.
type IGenerateStructuredJsonResponseResult struct {
	syswinrt.IInspectable
}

// IID_IGenerateStructuredJsonResponseResult is the interface identifier for IGenerateStructuredJsonResponseResult.
var IID_IGenerateStructuredJsonResponseResult = win32.GUID{Data1: 0x1cfe5f4c, Data2: 0x897a, Data3: 0x5692, Data4: [8]byte{0xb9, 0xae, 0xcc, 0xb5, 0x4e, 0xda, 0x14, 0xc5}}

// Text (propget get_Text) dispatches through IGenerateStructuredJsonResponseResult's vtable slot 6.
func (self *IGenerateStructuredJsonResponseResult) Text() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Status (propget get_Status) dispatches through IGenerateStructuredJsonResponseResult's vtable slot 7.
func (self *IGenerateStructuredJsonResponseResult) Status() (GenerateStructuredJsonResponseStatus, error) {
	result := new(GenerateStructuredJsonResponseStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExtendedError (propget get_ExtendedError) dispatches through IGenerateStructuredJsonResponseResult's vtable slot 8.
func (self *IGenerateStructuredJsonResponseResult) ExtendedError() (int32, error) {
	result := new(int32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILanguageModel is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModel.
// IID: 6331c629-8c86-5bfe-8c4e-9ca5573cc14b
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModel runtime class.
type ILanguageModel struct {
	syswinrt.IInspectable
}

// IID_ILanguageModel is the interface identifier for ILanguageModel.
var IID_ILanguageModel = win32.GUID{Data1: 0x6331c629, Data2: 0x8c86, Data3: 0x5bfe, Data4: [8]byte{0x8c, 0x4e, 0x9c, 0xa5, 0x57, 0x3c, 0xc1, 0x4b}}

// ILanguageModel2 is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModel2.
// IID: 653b714e-f9b3-51cb-954f-5ea58f63ab89
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModel runtime class.
type ILanguageModel2 struct {
	syswinrt.IInspectable
}

// IID_ILanguageModel2 is the interface identifier for ILanguageModel2.
var IID_ILanguageModel2 = win32.GUID{Data1: 0x653b714e, Data2: 0xf9b3, Data3: 0x51cb, Data4: [8]byte{0x95, 0x4f, 0x5e, 0xa5, 0x8f, 0x63, 0xab, 0x89}}

// GenerateResponseAsync dispatches through ILanguageModel2's vtable slot 6.
func (self *ILanguageModel2) GenerateResponseAsync(prompt string) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return nil, err
	}
	defer hPrompt.Close()
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hPrompt.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GenerateResponseAsync2 dispatches through ILanguageModel2's vtable slot 7.
func (self *ILanguageModel2) GenerateResponseAsync2(prompt string, options *ILanguageModelOptions) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return nil, err
	}
	defer hPrompt.Close()
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hPrompt.Raw()), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GenerateResponseAsync3 dispatches through ILanguageModel2's vtable slot 8.
func (self *ILanguageModel2) GenerateResponseAsync3(context *ILanguageModelContext, prompt string, options *ILanguageModelOptions) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return nil, err
	}
	defer hPrompt.Close()
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(context)), uintptr(hPrompt.Raw()), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GenerateResponseFromEmbeddingsAsync dispatches through ILanguageModel2's vtable slot 9.
func (self *ILanguageModel2) GenerateResponseFromEmbeddingsAsync(promptEmbedding *IIterableOfEmbeddingVector) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(promptEmbedding)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GenerateResponseFromEmbeddingsAsync2 dispatches through ILanguageModel2's vtable slot 10.
func (self *ILanguageModel2) GenerateResponseFromEmbeddingsAsync2(promptEmbedding *IIterableOfEmbeddingVector, options *ILanguageModelOptions) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(promptEmbedding)), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GenerateResponseFromEmbeddingsAsync3 dispatches through ILanguageModel2's vtable slot 11.
func (self *ILanguageModel2) GenerateResponseFromEmbeddingsAsync3(context *ILanguageModelContext, promptEmbedding *IIterableOfEmbeddingVector, options *ILanguageModelOptions) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(context)), uintptr(unsafe.Pointer(promptEmbedding)), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GenerateEmbeddingVectors dispatches through ILanguageModel2's vtable slot 12.
func (self *ILanguageModel2) GenerateEmbeddingVectors(prompt string) (*ILanguageModelEmbeddingVectorResult, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return nil, err
	}
	defer hPrompt.Close()
	result := new(*ILanguageModelEmbeddingVectorResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(hPrompt.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GenerateEmbeddingVectors2 dispatches through ILanguageModel2's vtable slot 13.
func (self *ILanguageModel2) GenerateEmbeddingVectors2(prompt string, contentFilterOptions *windowsaicontentsafety.IContentFilterOptions) (*ILanguageModelEmbeddingVectorResult, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return nil, err
	}
	defer hPrompt.Close()
	result := new(*ILanguageModelEmbeddingVectorResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(hPrompt.Raw()), uintptr(unsafe.Pointer(contentFilterOptions)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetUsablePromptLength dispatches through ILanguageModel2's vtable slot 14.
func (self *ILanguageModel2) GetUsablePromptLength(prompt string) (uint64, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return 0, err
	}
	defer hPrompt.Close()
	result := new(uint64)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)), uintptr(hPrompt.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetUsablePromptLength2 dispatches through ILanguageModel2's vtable slot 15.
func (self *ILanguageModel2) GetUsablePromptLength2(context *ILanguageModelContext, prompt string) (uint64, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return 0, err
	}
	defer hPrompt.Close()
	result := new(uint64)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(context)), uintptr(hPrompt.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetVectorSpaceId dispatches through ILanguageModel2's vtable slot 16.
func (self *ILanguageModel2) GetVectorSpaceId() (win32.GUID, error) {
	result := new(win32.GUID)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[16], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateContext dispatches through ILanguageModel2's vtable slot 17.
func (self *ILanguageModel2) CreateContext() (*ILanguageModelContext, error) {
	result := new(*ILanguageModelContext)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[17], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateContext2 dispatches through ILanguageModel2's vtable slot 18.
func (self *ILanguageModel2) CreateContext2(systemPrompt string) (*ILanguageModelContext, error) {
	hSystemPrompt, err := winrt.NewHString(systemPrompt)
	if err != nil {
		return nil, err
	}
	defer hSystemPrompt.Close()
	result := new(*ILanguageModelContext)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[18], uintptr(unsafe.Pointer(self)), uintptr(hSystemPrompt.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateContext3 dispatches through ILanguageModel2's vtable slot 19.
func (self *ILanguageModel2) CreateContext3(systemPrompt string, contentFilterOptions *windowsaicontentsafety.IContentFilterOptions) (*ILanguageModelContext, error) {
	hSystemPrompt, err := winrt.NewHString(systemPrompt)
	if err != nil {
		return nil, err
	}
	defer hSystemPrompt.Close()
	result := new(*ILanguageModelContext)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[19], uintptr(unsafe.Pointer(self)), uintptr(hSystemPrompt.Raw()), uintptr(unsafe.Pointer(contentFilterOptions)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILanguageModel3 is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModel3.
// IID: e5f6b00d-a835-5170-864c-4aa810a7fd15
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModel runtime class.
type ILanguageModel3 struct {
	syswinrt.IInspectable
}

// IID_ILanguageModel3 is the interface identifier for ILanguageModel3.
var IID_ILanguageModel3 = win32.GUID{Data1: 0xe5f6b00d, Data2: 0xa835, Data3: 0x5170, Data4: [8]byte{0x86, 0x4c, 0x4a, 0xa8, 0x10, 0xa7, 0xfd, 0x15}}

// GenerateStructuredJsonResponseAsync dispatches through ILanguageModel3's vtable slot 6.
func (self *ILanguageModel3) GenerateStructuredJsonResponseAsync(prompt string, jsonSchema string) (*IAsyncOperationWithProgressOfGenerateStructuredJsonResponseResultAndString, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return nil, err
	}
	defer hPrompt.Close()
	hJsonSchema, err := winrt.NewHString(jsonSchema)
	if err != nil {
		return nil, err
	}
	defer hJsonSchema.Close()
	result := new(*IAsyncOperationWithProgressOfGenerateStructuredJsonResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hPrompt.Raw()), uintptr(hJsonSchema.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GenerateStructuredJsonResponseAsync2 dispatches through ILanguageModel3's vtable slot 7.
func (self *ILanguageModel3) GenerateStructuredJsonResponseAsync2(prompt string, jsonSchema string, options *ILanguageModelOptions) (*IAsyncOperationWithProgressOfGenerateStructuredJsonResponseResultAndString, error) {
	hPrompt, err := winrt.NewHString(prompt)
	if err != nil {
		return nil, err
	}
	defer hPrompt.Close()
	hJsonSchema, err := winrt.NewHString(jsonSchema)
	if err != nil {
		return nil, err
	}
	defer hJsonSchema.Close()
	result := new(*IAsyncOperationWithProgressOfGenerateStructuredJsonResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hPrompt.Raw()), uintptr(hJsonSchema.Raw()), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILanguageModelContext is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelContext.
// IID: 518b305c-7b69-5a33-8129-d47d6b8eec4e
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModelContext runtime class.
type ILanguageModelContext struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelContext is the interface identifier for ILanguageModelContext.
var IID_ILanguageModelContext = win32.GUID{Data1: 0x518b305c, Data2: 0x7b69, Data3: 0x5a33, Data4: [8]byte{0x81, 0x29, 0xd4, 0x7d, 0x6b, 0x8e, 0xec, 0x4e}}

// ILanguageModelEmbeddingVectorResult is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelEmbeddingVectorResult.
// IID: 4dbdb154-ee3c-56f6-a40b-413e95bd5acb
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModelEmbeddingVectorResult runtime class.
type ILanguageModelEmbeddingVectorResult struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelEmbeddingVectorResult is the interface identifier for ILanguageModelEmbeddingVectorResult.
var IID_ILanguageModelEmbeddingVectorResult = win32.GUID{Data1: 0x4dbdb154, Data2: 0xee3c, Data3: 0x56f6, Data4: [8]byte{0xa4, 0x0b, 0x41, 0x3e, 0x95, 0xbd, 0x5a, 0xcb}}

// EmbeddingVectors (propget get_EmbeddingVectors) dispatches through ILanguageModelEmbeddingVectorResult's vtable slot 6.
func (self *ILanguageModelEmbeddingVectorResult) EmbeddingVectors() (*IVectorViewOfEmbeddingVector, error) {
	result := new(*IVectorViewOfEmbeddingVector)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Status (propget get_Status) dispatches through ILanguageModelEmbeddingVectorResult's vtable slot 7.
func (self *ILanguageModelEmbeddingVectorResult) Status() (LanguageModelResponseStatus, error) {
	result := new(LanguageModelResponseStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExtendedError (propget get_ExtendedError) dispatches through ILanguageModelEmbeddingVectorResult's vtable slot 8.
func (self *ILanguageModelEmbeddingVectorResult) ExtendedError() (int32, error) {
	result := new(int32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILanguageModelLowRankAdapter is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelLowRankAdapter.
// IID: dc67c5f1-4a8b-5178-a0fd-5488fd49a681
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModelLowRankAdapter runtime class.
type ILanguageModelLowRankAdapter struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelLowRankAdapter is the interface identifier for ILanguageModelLowRankAdapter.
var IID_ILanguageModelLowRankAdapter = win32.GUID{Data1: 0xdc67c5f1, Data2: 0x4a8b, Data3: 0x5178, Data4: [8]byte{0xa0, 0xfd, 0x54, 0x88, 0xfd, 0x49, 0xa6, 0x81}}

// ILanguageModelLowRankAdapterResult is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelLowRankAdapterResult.
// IID: b23af149-70fd-53f1-9e5c-51ba642a7836
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModelLowRankAdapterResult runtime class.
type ILanguageModelLowRankAdapterResult struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelLowRankAdapterResult is the interface identifier for ILanguageModelLowRankAdapterResult.
var IID_ILanguageModelLowRankAdapterResult = win32.GUID{Data1: 0xb23af149, Data2: 0x70fd, Data3: 0x53f1, Data4: [8]byte{0x9e, 0x5c, 0x51, 0xba, 0x64, 0x2a, 0x78, 0x36}}

// LowRankAdapter (propget get_LowRankAdapter) dispatches through ILanguageModelLowRankAdapterResult's vtable slot 6.
func (self *ILanguageModelLowRankAdapterResult) LowRankAdapter() (*ILanguageModelLowRankAdapter, error) {
	result := new(*ILanguageModelLowRankAdapter)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExtendedError (propget get_ExtendedError) dispatches through ILanguageModelLowRankAdapterResult's vtable slot 7.
func (self *ILanguageModelLowRankAdapterResult) ExtendedError() (int32, error) {
	result := new(int32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILanguageModelLowRankAdapterStatics is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelLowRankAdapterStatics.
// IID: e3b61010-37c3-56d5-b112-1aa57ad5bfc7
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModelLowRankAdapter runtime class.
type ILanguageModelLowRankAdapterStatics struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelLowRankAdapterStatics is the interface identifier for ILanguageModelLowRankAdapterStatics.
var IID_ILanguageModelLowRankAdapterStatics = win32.GUID{Data1: 0xe3b61010, Data2: 0x37c3, Data3: 0x56d5, Data4: [8]byte{0xb1, 0x12, 0x1a, 0xa5, 0x7a, 0xd5, 0xbf, 0xc7}}

// CreateFromPath dispatches through ILanguageModelLowRankAdapterStatics's vtable slot 6.
func (self *ILanguageModelLowRankAdapterStatics) CreateFromPath(filePath string) (*ILanguageModelLowRankAdapterResult, error) {
	hFilePath, err := winrt.NewHString(filePath)
	if err != nil {
		return nil, err
	}
	defer hFilePath.Close()
	result := new(*ILanguageModelLowRankAdapterResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hFilePath.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILanguageModelOptions is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelOptions.
// IID: 7f380003-5a09-5f1f-afb0-aa483e3670cc
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModelOptions runtime class.
type ILanguageModelOptions struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelOptions is the interface identifier for ILanguageModelOptions.
var IID_ILanguageModelOptions = win32.GUID{Data1: 0x7f380003, Data2: 0x5a09, Data3: 0x5f1f, Data4: [8]byte{0xaf, 0xb0, 0xaa, 0x48, 0x3e, 0x36, 0x70, 0xcc}}

// Temperature (propget get_Temperature) dispatches through ILanguageModelOptions's vtable slot 6.
func (self *ILanguageModelOptions) Temperature() (float32, error) {
	result := new(float32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetTemperature (propput put_Temperature) dispatches through ILanguageModelOptions's vtable slot 7.
func (self *ILanguageModelOptions) SetTemperature(value float32) error {
	_value := uintptr(math.Float32bits(value))
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), _value)
	return win32.ErrIfFailed(int32(r1))
}

// TopP (propget get_TopP) dispatches through ILanguageModelOptions's vtable slot 8.
func (self *ILanguageModelOptions) TopP() (float32, error) {
	result := new(float32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetTopP (propput put_TopP) dispatches through ILanguageModelOptions's vtable slot 9.
func (self *ILanguageModelOptions) SetTopP(value float32) error {
	_value := uintptr(math.Float32bits(value))
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), _value)
	return win32.ErrIfFailed(int32(r1))
}

// TopK (propget get_TopK) dispatches through ILanguageModelOptions's vtable slot 10.
func (self *ILanguageModelOptions) TopK() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetTopK (propput put_TopK) dispatches through ILanguageModelOptions's vtable slot 11.
func (self *ILanguageModelOptions) SetTopK(value uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(value))
	return win32.ErrIfFailed(int32(r1))
}

// ContentFilterOptions (propget get_ContentFilterOptions) dispatches through ILanguageModelOptions's vtable slot 12.
func (self *ILanguageModelOptions) ContentFilterOptions() (*windowsaicontentsafety.IContentFilterOptions, error) {
	result := new(*windowsaicontentsafety.IContentFilterOptions)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetContentFilterOptions (propput put_ContentFilterOptions) dispatches through ILanguageModelOptions's vtable slot 13.
func (self *ILanguageModelOptions) SetContentFilterOptions(value *windowsaicontentsafety.IContentFilterOptions) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// ILanguageModelOptions2 is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelOptions2.
// IID: 8fac9616-a95f-56f7-96d8-e01ebdda1d39
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModelOptions runtime class.
type ILanguageModelOptions2 struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelOptions2 is the interface identifier for ILanguageModelOptions2.
var IID_ILanguageModelOptions2 = win32.GUID{Data1: 0x8fac9616, Data2: 0xa95f, Data3: 0x56f7, Data4: [8]byte{0x96, 0xd8, 0xe0, 0x1e, 0xbd, 0xda, 0x1d, 0x39}}

// LowRankAdapter (propget get_LowRankAdapter) dispatches through ILanguageModelOptions2's vtable slot 6.
func (self *ILanguageModelOptions2) LowRankAdapter() (*ILanguageModelLowRankAdapter, error) {
	result := new(*ILanguageModelLowRankAdapter)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetLowRankAdapter (propput put_LowRankAdapter) dispatches through ILanguageModelOptions2's vtable slot 7.
func (self *ILanguageModelOptions2) SetLowRankAdapter(value *ILanguageModelLowRankAdapter) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// ILanguageModelResponseResult is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelResponseResult.
// IID: 3a256fff-a426-5d3b-8e4b-3ac84162471e
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModelResponseResult runtime class.
type ILanguageModelResponseResult struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelResponseResult is the interface identifier for ILanguageModelResponseResult.
var IID_ILanguageModelResponseResult = win32.GUID{Data1: 0x3a256fff, Data2: 0xa426, Data3: 0x5d3b, Data4: [8]byte{0x8e, 0x4b, 0x3a, 0xc8, 0x41, 0x62, 0x47, 0x1e}}

// Text (propget get_Text) dispatches through ILanguageModelResponseResult's vtable slot 6.
func (self *ILanguageModelResponseResult) Text() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Status (propget get_Status) dispatches through ILanguageModelResponseResult's vtable slot 7.
func (self *ILanguageModelResponseResult) Status() (LanguageModelResponseStatus, error) {
	result := new(LanguageModelResponseStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExtendedError (propget get_ExtendedError) dispatches through ILanguageModelResponseResult's vtable slot 8.
func (self *ILanguageModelResponseResult) ExtendedError() (int32, error) {
	result := new(int32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ILanguageModelStatics is the WinRT interface Microsoft.Windows.AI.Text.ILanguageModelStatics.
// IID: 8f18f9af-6095-553b-8d9d-6bcc98026546
// Exclusive to the Microsoft.Windows.AI.Text.LanguageModel runtime class.
type ILanguageModelStatics struct {
	syswinrt.IInspectable
}

// IID_ILanguageModelStatics is the interface identifier for ILanguageModelStatics.
var IID_ILanguageModelStatics = win32.GUID{Data1: 0x8f18f9af, Data2: 0x6095, Data3: 0x553b, Data4: [8]byte{0x8d, 0x9d, 0x6b, 0xcc, 0x98, 0x02, 0x65, 0x46}}

// GetReadyState dispatches through ILanguageModelStatics's vtable slot 6.
func (self *ILanguageModelStatics) GetReadyState() (windowsai.AIFeatureReadyState, error) {
	result := new(windowsai.AIFeatureReadyState)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// EnsureReadyAsync dispatches through ILanguageModelStatics's vtable slot 7.
func (self *ILanguageModelStatics) EnsureReadyAsync() (*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble, error) {
	result := new(*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateAsync dispatches through ILanguageModelStatics's vtable slot 8.
func (self *ILanguageModelStatics) CreateAsync() (*IAsyncOperationOfLanguageModel, error) {
	result := new(*IAsyncOperationOfLanguageModel)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextRewriter is the WinRT interface Microsoft.Windows.AI.Text.ITextRewriter.
// IID: eb1e7cf0-e110-506c-b0ea-7a288d8e7778
// Exclusive to the Microsoft.Windows.AI.Text.TextRewriter runtime class.
type ITextRewriter struct {
	syswinrt.IInspectable
}

// IID_ITextRewriter is the interface identifier for ITextRewriter.
var IID_ITextRewriter = win32.GUID{Data1: 0xeb1e7cf0, Data2: 0xe110, Data3: 0x506c, Data4: [8]byte{0xb0, 0xea, 0x7a, 0x28, 0x8d, 0x8e, 0x77, 0x78}}

// RewriteAsync dispatches through ITextRewriter's vtable slot 6.
func (self *ITextRewriter) RewriteAsync(text string) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	hText, err := winrt.NewHString(text)
	if err != nil {
		return nil, err
	}
	defer hText.Close()
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hText.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextRewriter2 is the WinRT interface Microsoft.Windows.AI.Text.ITextRewriter2.
// IID: 7937d261-13ce-5b24-b17c-fe5cd0be23b6
// Exclusive to the Microsoft.Windows.AI.Text.TextRewriter runtime class.
type ITextRewriter2 struct {
	syswinrt.IInspectable
}

// IID_ITextRewriter2 is the interface identifier for ITextRewriter2.
var IID_ITextRewriter2 = win32.GUID{Data1: 0x7937d261, Data2: 0x13ce, Data3: 0x5b24, Data4: [8]byte{0xb1, 0x7c, 0xfe, 0x5c, 0xd0, 0xbe, 0x23, 0xb6}}

// RewriteAsync dispatches through ITextRewriter2's vtable slot 6.
func (self *ITextRewriter2) RewriteAsync(text string, tone TextRewriteTone) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	hText, err := winrt.NewHString(text)
	if err != nil {
		return nil, err
	}
	defer hText.Close()
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hText.Raw()), uintptr(tone), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextRewriter3 is the WinRT interface Microsoft.Windows.AI.Text.ITextRewriter3.
// IID: 622eb80a-ed1a-5525-80d8-c6e80236a195
// Exclusive to the Microsoft.Windows.AI.Text.TextRewriter runtime class.
type ITextRewriter3 struct {
	syswinrt.IInspectable
}

// IID_ITextRewriter3 is the interface identifier for ITextRewriter3.
var IID_ITextRewriter3 = win32.GUID{Data1: 0x622eb80a, Data2: 0xed1a, Data3: 0x5525, Data4: [8]byte{0x80, 0xd8, 0xc6, 0xe8, 0x02, 0x36, 0xa1, 0x95}}

// RewriteCustomAsync dispatches through ITextRewriter3's vtable slot 6.
func (self *ITextRewriter3) RewriteCustomAsync(text string, customTone string) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	hText, err := winrt.NewHString(text)
	if err != nil {
		return nil, err
	}
	defer hText.Close()
	hCustomTone, err := winrt.NewHString(customTone)
	if err != nil {
		return nil, err
	}
	defer hCustomTone.Close()
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hText.Raw()), uintptr(hCustomTone.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextRewriterFactory is the WinRT interface Microsoft.Windows.AI.Text.ITextRewriterFactory.
// IID: f452e60d-ef50-5bc9-b483-217d5b4e7151
// Exclusive to the Microsoft.Windows.AI.Text.TextRewriter runtime class.
type ITextRewriterFactory struct {
	syswinrt.IInspectable
}

// IID_ITextRewriterFactory is the interface identifier for ITextRewriterFactory.
var IID_ITextRewriterFactory = win32.GUID{Data1: 0xf452e60d, Data2: 0xef50, Data3: 0x5bc9, Data4: [8]byte{0xb4, 0x83, 0x21, 0x7d, 0x5b, 0x4e, 0x71, 0x51}}

// CreateInstance dispatches through ITextRewriterFactory's vtable slot 6.
func (self *ITextRewriterFactory) CreateInstance(languageModel *ILanguageModel) (*ITextRewriter, error) {
	result := new(*ITextRewriter)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(languageModel)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextSummarizer is the WinRT interface Microsoft.Windows.AI.Text.ITextSummarizer.
// IID: eef548c5-d7bc-50be-a8ab-29e241b78bd1
// Exclusive to the Microsoft.Windows.AI.Text.TextSummarizer runtime class.
type ITextSummarizer struct {
	syswinrt.IInspectable
}

// IID_ITextSummarizer is the interface identifier for ITextSummarizer.
var IID_ITextSummarizer = win32.GUID{Data1: 0xeef548c5, Data2: 0xd7bc, Data3: 0x50be, Data4: [8]byte{0xa8, 0xab, 0x29, 0xe2, 0x41, 0xb7, 0x8b, 0xd1}}

// SummarizeAsync dispatches through ITextSummarizer's vtable slot 6.
func (self *ITextSummarizer) SummarizeAsync(text string) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	hText, err := winrt.NewHString(text)
	if err != nil {
		return nil, err
	}
	defer hText.Close()
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hText.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SummarizeParagraphAsync dispatches through ITextSummarizer's vtable slot 7.
func (self *ITextSummarizer) SummarizeParagraphAsync(text string) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	hText, err := winrt.NewHString(text)
	if err != nil {
		return nil, err
	}
	defer hText.Close()
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(hText.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextSummarizer2 is the WinRT interface Microsoft.Windows.AI.Text.ITextSummarizer2.
// IID: 9e20797d-1ff6-5295-8cb6-d48fb8ba483b
// Exclusive to the Microsoft.Windows.AI.Text.TextSummarizer runtime class.
type ITextSummarizer2 struct {
	syswinrt.IInspectable
}

// IID_ITextSummarizer2 is the interface identifier for ITextSummarizer2.
var IID_ITextSummarizer2 = win32.GUID{Data1: 0x9e20797d, Data2: 0x1ff6, Data3: 0x5295, Data4: [8]byte{0x8c, 0xb6, 0xd4, 0x8f, 0xb8, 0xba, 0x48, 0x3b}}

// SummarizeConversationAsync dispatches through ITextSummarizer2's vtable slot 6.
func (self *ITextSummarizer2) SummarizeConversationAsync(messages *IVectorViewOfConversationItem, options *IConversationSummaryOptions) (*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString, error) {
	result := new(*IAsyncOperationWithProgressOfLanguageModelResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(messages)), uintptr(unsafe.Pointer(options)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextSummarizer3 is the WinRT interface Microsoft.Windows.AI.Text.ITextSummarizer3.
// IID: 493d32b9-dbc9-5d4b-802f-90473850500e
// Exclusive to the Microsoft.Windows.AI.Text.TextSummarizer runtime class.
type ITextSummarizer3 struct {
	syswinrt.IInspectable
}

// IID_ITextSummarizer3 is the interface identifier for ITextSummarizer3.
var IID_ITextSummarizer3 = win32.GUID{Data1: 0x493d32b9, Data2: 0xdbc9, Data3: 0x5d4b, Data4: [8]byte{0x80, 0x2f, 0x90, 0x47, 0x38, 0x50, 0x50, 0x0e}}

// slot 6: IsPromptLargerThanContext skipped: conformant array

// ITextSummarizer4 is the WinRT interface Microsoft.Windows.AI.Text.ITextSummarizer4.
// IID: 5b7a28c0-7777-52e5-9934-b95b514cf535
// Exclusive to the Microsoft.Windows.AI.Text.TextSummarizer runtime class.
type ITextSummarizer4 struct {
	syswinrt.IInspectable
}

// IID_ITextSummarizer4 is the interface identifier for ITextSummarizer4.
var IID_ITextSummarizer4 = win32.GUID{Data1: 0x5b7a28c0, Data2: 0x7777, Data3: 0x52e5, Data4: [8]byte{0x99, 0x34, 0xb9, 0x5b, 0x51, 0x4c, 0xf5, 0x35}}

// IsPromptLargerThanContext dispatches through ITextSummarizer4's vtable slot 6.
func (self *ITextSummarizer4) IsPromptLargerThanContext(text string, cutoffPosition *uint64) (bool, error) {
	hText, err := winrt.NewHString(text)
	if err != nil {
		return false, err
	}
	defer hText.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hText.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(cutoffPosition))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// ITextSummarizerFactory is the WinRT interface Microsoft.Windows.AI.Text.ITextSummarizerFactory.
// IID: b6a75913-4a1e-59e7-856a-ae7ab2383864
// Exclusive to the Microsoft.Windows.AI.Text.TextSummarizer runtime class.
type ITextSummarizerFactory struct {
	syswinrt.IInspectable
}

// IID_ITextSummarizerFactory is the interface identifier for ITextSummarizerFactory.
var IID_ITextSummarizerFactory = win32.GUID{Data1: 0xb6a75913, Data2: 0x4a1e, Data3: 0x59e7, Data4: [8]byte{0x85, 0x6a, 0xae, 0x7a, 0xb2, 0x38, 0x38, 0x64}}

// CreateInstance dispatches through ITextSummarizerFactory's vtable slot 6.
func (self *ITextSummarizerFactory) CreateInstance(languageModel *ILanguageModel) (*ITextSummarizer, error) {
	result := new(*ITextSummarizer)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(languageModel)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextToTableConverter is the WinRT interface Microsoft.Windows.AI.Text.ITextToTableConverter.
// IID: a008d9ad-25ce-5a6b-9ceb-d8e95d04e10b
// Exclusive to the Microsoft.Windows.AI.Text.TextToTableConverter runtime class.
type ITextToTableConverter struct {
	syswinrt.IInspectable
}

// IID_ITextToTableConverter is the interface identifier for ITextToTableConverter.
var IID_ITextToTableConverter = win32.GUID{Data1: 0xa008d9ad, Data2: 0x25ce, Data3: 0x5a6b, Data4: [8]byte{0x9c, 0xeb, 0xd8, 0xe9, 0x5d, 0x04, 0xe1, 0x0b}}

// ConvertAsync dispatches through ITextToTableConverter's vtable slot 6.
func (self *ITextToTableConverter) ConvertAsync(text string) (*IAsyncOperationWithProgressOfTextToTableResponseResultAndString, error) {
	hText, err := winrt.NewHString(text)
	if err != nil {
		return nil, err
	}
	defer hText.Close()
	result := new(*IAsyncOperationWithProgressOfTextToTableResponseResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hText.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextToTableConverterFactory is the WinRT interface Microsoft.Windows.AI.Text.ITextToTableConverterFactory.
// IID: bb84cbb5-19c8-5857-b65d-705aa1486404
// Exclusive to the Microsoft.Windows.AI.Text.TextToTableConverter runtime class.
type ITextToTableConverterFactory struct {
	syswinrt.IInspectable
}

// IID_ITextToTableConverterFactory is the interface identifier for ITextToTableConverterFactory.
var IID_ITextToTableConverterFactory = win32.GUID{Data1: 0xbb84cbb5, Data2: 0x19c8, Data3: 0x5857, Data4: [8]byte{0xb6, 0x5d, 0x70, 0x5a, 0xa1, 0x48, 0x64, 0x04}}

// CreateInstance dispatches through ITextToTableConverterFactory's vtable slot 6.
func (self *ITextToTableConverterFactory) CreateInstance(languageModel *ILanguageModel) (*ITextToTableConverter, error) {
	result := new(*ITextToTableConverter)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(languageModel)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextToTableResponseResult is the WinRT interface Microsoft.Windows.AI.Text.ITextToTableResponseResult.
// IID: 391fbf11-59cd-575d-834a-9ef823116f98
// Exclusive to the Microsoft.Windows.AI.Text.TextToTableResponseResult runtime class.
type ITextToTableResponseResult struct {
	syswinrt.IInspectable
}

// IID_ITextToTableResponseResult is the interface identifier for ITextToTableResponseResult.
var IID_ITextToTableResponseResult = win32.GUID{Data1: 0x391fbf11, Data2: 0x59cd, Data3: 0x575d, Data4: [8]byte{0x83, 0x4a, 0x9e, 0xf8, 0x23, 0x11, 0x6f, 0x98}}

// slot 6: GetRows skipped: conformant array

// Status (propget get_Status) dispatches through ITextToTableResponseResult's vtable slot 7.
func (self *ITextToTableResponseResult) Status() (LanguageModelResponseStatus, error) {
	result := new(LanguageModelResponseStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExtendedError (propget get_ExtendedError) dispatches through ITextToTableResponseResult's vtable slot 8.
func (self *ITextToTableResponseResult) ExtendedError() (int32, error) {
	result := new(int32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextToTableRow is the WinRT interface Microsoft.Windows.AI.Text.ITextToTableRow.
// IID: 036294fe-e53c-5e66-93d2-7c92338db881
// Exclusive to the Microsoft.Windows.AI.Text.TextToTableRow runtime class.
type ITextToTableRow struct {
	syswinrt.IInspectable
}

// IID_ITextToTableRow is the interface identifier for ITextToTableRow.
var IID_ITextToTableRow = win32.GUID{Data1: 0x036294fe, Data2: 0xe53c, Data3: 0x5e66, Data4: [8]byte{0x93, 0xd2, 0x7c, 0x92, 0x33, 0x8d, 0xb8, 0x81}}

// slot 6: GetColumns skipped: conformant array
