// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package scenes

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// SceneBoundingBox is the Microsoft.UI.Composition.Scenes.SceneBoundingBox runtime class, surfaced through its
// default interface ISceneBoundingBox. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneBoundingBox struct {
	ISceneBoundingBox
}

// SceneComponent is the Microsoft.UI.Composition.Scenes.SceneComponent runtime class, surfaced through its
// default interface ISceneComponent. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneComponent struct {
	ISceneComponent
}

// SceneMaterial is the Microsoft.UI.Composition.Scenes.SceneMaterial runtime class, surfaced through its
// default interface ISceneMaterial. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneMaterial struct {
	ISceneMaterial
}

// SceneMaterialInput is the Microsoft.UI.Composition.Scenes.SceneMaterialInput runtime class, surfaced through its
// default interface ISceneMaterialInput. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneMaterialInput struct {
	ISceneMaterialInput
}

// SceneMesh is the Microsoft.UI.Composition.Scenes.SceneMesh runtime class, surfaced through its
// default interface ISceneMesh. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneMesh struct {
	ISceneMesh
}

// SceneMeshStatics returns the Microsoft.UI.Composition.Scenes.ISceneMeshStatics statics of the
// Microsoft.UI.Composition.Scenes.SceneMesh runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SceneMeshStatics() (*ISceneMeshStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Composition.Scenes.SceneMesh", &IID_ISceneMeshStatics)
	if err != nil {
		return nil, err
	}
	return (*ISceneMeshStatics)(unsafe.Pointer(factory)), nil
}

// SceneMeshMaterialAttributeMap is the Microsoft.UI.Composition.Scenes.SceneMeshMaterialAttributeMap runtime class, surfaced through its
// default interface ISceneMeshMaterialAttributeMap. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneMeshMaterialAttributeMap struct {
	ISceneMeshMaterialAttributeMap
}

// AsMapOfStringAndSceneAttributeSemantic queries the instance's IMapOfStringAndSceneAttributeSemantic interface.
// The returned reference is owned by the caller.
func (self *SceneMeshMaterialAttributeMap) AsMapOfStringAndSceneAttributeSemantic() (*IMapOfStringAndSceneAttributeSemantic, error) {
	return winrt.QueryInterface[IMapOfStringAndSceneAttributeSemantic](unsafe.Pointer(self), &IID_IMapOfStringAndSceneAttributeSemantic)
}

// AsIterableOfIKeyValuePairOfStringAndSceneAttributeSemantic queries the instance's IIterableOfIKeyValuePairOfStringAndSceneAttributeSemantic interface.
// The returned reference is owned by the caller.
func (self *SceneMeshMaterialAttributeMap) AsIterableOfIKeyValuePairOfStringAndSceneAttributeSemantic() (*IIterableOfIKeyValuePairOfStringAndSceneAttributeSemantic, error) {
	return winrt.QueryInterface[IIterableOfIKeyValuePairOfStringAndSceneAttributeSemantic](unsafe.Pointer(self), &IID_IIterableOfIKeyValuePairOfStringAndSceneAttributeSemantic)
}

// SceneMeshRendererComponent is the Microsoft.UI.Composition.Scenes.SceneMeshRendererComponent runtime class, surfaced through its
// default interface ISceneMeshRendererComponent. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneMeshRendererComponent struct {
	ISceneMeshRendererComponent
}

// SceneMeshRendererComponentStatics returns the Microsoft.UI.Composition.Scenes.ISceneMeshRendererComponentStatics statics of the
// Microsoft.UI.Composition.Scenes.SceneMeshRendererComponent runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SceneMeshRendererComponentStatics() (*ISceneMeshRendererComponentStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Composition.Scenes.SceneMeshRendererComponent", &IID_ISceneMeshRendererComponentStatics)
	if err != nil {
		return nil, err
	}
	return (*ISceneMeshRendererComponentStatics)(unsafe.Pointer(factory)), nil
}

// SceneMetallicRoughnessMaterial is the Microsoft.UI.Composition.Scenes.SceneMetallicRoughnessMaterial runtime class, surfaced through its
// default interface ISceneMetallicRoughnessMaterial. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneMetallicRoughnessMaterial struct {
	ISceneMetallicRoughnessMaterial
}

// SceneMetallicRoughnessMaterialStatics returns the Microsoft.UI.Composition.Scenes.ISceneMetallicRoughnessMaterialStatics statics of the
// Microsoft.UI.Composition.Scenes.SceneMetallicRoughnessMaterial runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SceneMetallicRoughnessMaterialStatics() (*ISceneMetallicRoughnessMaterialStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Composition.Scenes.SceneMetallicRoughnessMaterial", &IID_ISceneMetallicRoughnessMaterialStatics)
	if err != nil {
		return nil, err
	}
	return (*ISceneMetallicRoughnessMaterialStatics)(unsafe.Pointer(factory)), nil
}

// SceneModelTransform is the Microsoft.UI.Composition.Scenes.SceneModelTransform runtime class, surfaced through its
// default interface ISceneModelTransform. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneModelTransform struct {
	ISceneModelTransform
}

// SceneNode is the Microsoft.UI.Composition.Scenes.SceneNode runtime class, surfaced through its
// default interface ISceneNode. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneNode struct {
	ISceneNode
}

// SceneNodeStatics returns the Microsoft.UI.Composition.Scenes.ISceneNodeStatics statics of the
// Microsoft.UI.Composition.Scenes.SceneNode runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SceneNodeStatics() (*ISceneNodeStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Composition.Scenes.SceneNode", &IID_ISceneNodeStatics)
	if err != nil {
		return nil, err
	}
	return (*ISceneNodeStatics)(unsafe.Pointer(factory)), nil
}

// SceneObject is the Microsoft.UI.Composition.Scenes.SceneObject runtime class, surfaced through its
// default interface ISceneObject. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneObject struct {
	ISceneObject
}

// ScenePbrMaterial is the Microsoft.UI.Composition.Scenes.ScenePbrMaterial runtime class, surfaced through its
// default interface IScenePbrMaterial. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type ScenePbrMaterial struct {
	IScenePbrMaterial
}

// SceneRendererComponent is the Microsoft.UI.Composition.Scenes.SceneRendererComponent runtime class, surfaced through its
// default interface ISceneRendererComponent. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneRendererComponent struct {
	ISceneRendererComponent
}

// SceneSurfaceMaterialInput is the Microsoft.UI.Composition.Scenes.SceneSurfaceMaterialInput runtime class, surfaced through its
// default interface ISceneSurfaceMaterialInput. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneSurfaceMaterialInput struct {
	ISceneSurfaceMaterialInput
}

// SceneSurfaceMaterialInputStatics returns the Microsoft.UI.Composition.Scenes.ISceneSurfaceMaterialInputStatics statics of the
// Microsoft.UI.Composition.Scenes.SceneSurfaceMaterialInput runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SceneSurfaceMaterialInputStatics() (*ISceneSurfaceMaterialInputStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Composition.Scenes.SceneSurfaceMaterialInput", &IID_ISceneSurfaceMaterialInputStatics)
	if err != nil {
		return nil, err
	}
	return (*ISceneSurfaceMaterialInputStatics)(unsafe.Pointer(factory)), nil
}

// SceneVisual is the Microsoft.UI.Composition.Scenes.SceneVisual runtime class, surfaced through its
// default interface ISceneVisual. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type SceneVisual struct {
	ISceneVisual
}

// SceneVisualStatics returns the Microsoft.UI.Composition.Scenes.ISceneVisualStatics statics of the
// Microsoft.UI.Composition.Scenes.SceneVisual runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func SceneVisualStatics() (*ISceneVisualStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Composition.Scenes.SceneVisual", &IID_ISceneVisualStatics)
	if err != nil {
		return nil, err
	}
	return (*ISceneVisualStatics)(unsafe.Pointer(factory)), nil
}
