// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package dragdrop

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	wrtfoundation "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/foundation"
)

// DragDropManager is the Microsoft.UI.Input.DragDrop.DragDropManager runtime class, surfaced through its
// default interface IDragDropManager. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DragDropManager struct {
	IDragDropManager
}

// AsClosable queries the instance's wrtfoundation.IClosable interface.
// The returned reference is owned by the caller.
func (self *DragDropManager) AsClosable() (*wrtfoundation.IClosable, error) {
	return winrt.QueryInterface[wrtfoundation.IClosable](unsafe.Pointer(self), &wrtfoundation.IID_IClosable)
}

// DragDropManagerStatics returns the Microsoft.UI.Input.DragDrop.IDragDropManagerStatics statics of the
// Microsoft.UI.Input.DragDrop.DragDropManager runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func DragDropManagerStatics() (*IDragDropManagerStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.UI.Input.DragDrop.DragDropManager", &IID_IDragDropManagerStatics)
	if err != nil {
		return nil, err
	}
	return (*IDragDropManagerStatics)(unsafe.Pointer(factory)), nil
}

// DragInfo is the Microsoft.UI.Input.DragDrop.DragInfo runtime class, surfaced through its
// default interface IDragInfo. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DragInfo struct {
	IDragInfo
}

// DragOperation is the Microsoft.UI.Input.DragDrop.DragOperation runtime class, surfaced through its
// default interface IDragOperation. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DragOperation struct {
	IDragOperation
}

// NewDragOperation activates Microsoft.UI.Input.DragDrop.DragOperation through its default
// constructor.
func NewDragOperation() (*DragOperation, error) {
	instance, err := winrt.ActivateInstance("Microsoft.UI.Input.DragDrop.DragOperation")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[DragOperation](unsafe.Pointer(instance), &IID_IDragOperation)
}

// AsClosable queries the instance's wrtfoundation.IClosable interface.
// The returned reference is owned by the caller.
func (self *DragOperation) AsClosable() (*wrtfoundation.IClosable, error) {
	return winrt.QueryInterface[wrtfoundation.IClosable](unsafe.Pointer(self), &wrtfoundation.IID_IClosable)
}

// DragUIOverride is the Microsoft.UI.Input.DragDrop.DragUIOverride runtime class, surfaced through its
// default interface IDragUIOverride. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DragUIOverride struct {
	IDragUIOverride
}

// DropOperationTargetRequestedEventArgs is the Microsoft.UI.Input.DragDrop.DropOperationTargetRequestedEventArgs runtime class, surfaced through its
// default interface IDropOperationTargetRequestedEventArgs. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type DropOperationTargetRequestedEventArgs struct {
	IDropOperationTargetRequestedEventArgs
}
