// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package dragdrop

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	wrtapplicationmodeldatatransfer "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/applicationmodel/datatransfer"
)

// IAsyncOperationOfDataPackageOperation is the WinRT interface Windows.Foundation.IAsyncOperation`1<Windows.ApplicationModel.DataTransfer.DataPackageOperation>.
// IID: 8b98aea9-64f0-5672-b30e-dfd9c2e4f6fe
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfDataPackageOperation struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfDataPackageOperation is the interface identifier for IAsyncOperationOfDataPackageOperation.
var IID_IAsyncOperationOfDataPackageOperation = win32.GUID{Data1: 0x8b98aea9, Data2: 0x64f0, Data3: 0x5672, Data4: [8]byte{0xb3, 0x0e, 0xdf, 0xd9, 0xc2, 0xe4, 0xf6, 0xfe}}

// slot 6: put_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// slot 7: get_Completed skipped: parameterized type Windows.Foundation.AsyncOperationCompletedHandler`1

// GetResults dispatches through IAsyncOperationOfDataPackageOperation's vtable slot 8.
func (self *IAsyncOperationOfDataPackageOperation) GetResults() (wrtapplicationmodeldatatransfer.DataPackageOperation, error) {
	result := new(wrtapplicationmodeldatatransfer.DataPackageOperation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
