// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

// Package builder binds the Microsoft.Windows.AppNotifications.Builder API surface of the Windows App SDK.
package builder
