// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package windowsappruntime

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	wrtapplicationmodel "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/applicationmodel"
)

// IDeploymentInitializeOptions is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentInitializeOptions.
// IID: 578a5fd4-9d7f-5e01-97b8-d8ea61db4027
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions runtime class.
type IDeploymentInitializeOptions struct {
	syswinrt.IInspectable
}

// IID_IDeploymentInitializeOptions is the interface identifier for IDeploymentInitializeOptions.
var IID_IDeploymentInitializeOptions = win32.GUID{Data1: 0x578a5fd4, Data2: 0x9d7f, Data3: 0x5e01, Data4: [8]byte{0x97, 0xb8, 0xd8, 0xea, 0x61, 0xdb, 0x40, 0x27}}

// ForceDeployment (propget get_ForceDeployment) dispatches through IDeploymentInitializeOptions's vtable slot 6.
func (self *IDeploymentInitializeOptions) ForceDeployment() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetForceDeployment (propput put_ForceDeployment) dispatches through IDeploymentInitializeOptions's vtable slot 7.
func (self *IDeploymentInitializeOptions) SetForceDeployment(value bool) error {
	_value := uintptr(0)
	if value {
		_value = 1
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), _value)
	return win32.ErrIfFailed(int32(r1))
}

// IDeploymentInitializeOptions2 is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentInitializeOptions2.
// IID: ad902820-149f-5e16-a566-9b2363997de2
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions runtime class.
type IDeploymentInitializeOptions2 struct {
	syswinrt.IInspectable
}

// IID_IDeploymentInitializeOptions2 is the interface identifier for IDeploymentInitializeOptions2.
var IID_IDeploymentInitializeOptions2 = win32.GUID{Data1: 0xad902820, Data2: 0x149f, Data3: 0x5e16, Data4: [8]byte{0xa5, 0x66, 0x9b, 0x23, 0x63, 0x99, 0x7d, 0xe2}}

// OnErrorShowUI (propget get_OnErrorShowUI) dispatches through IDeploymentInitializeOptions2's vtable slot 6.
func (self *IDeploymentInitializeOptions2) OnErrorShowUI() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetOnErrorShowUI (propput put_OnErrorShowUI) dispatches through IDeploymentInitializeOptions2's vtable slot 7.
func (self *IDeploymentInitializeOptions2) SetOnErrorShowUI(value bool) error {
	_value := uintptr(0)
	if value {
		_value = 1
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), _value)
	return win32.ErrIfFailed(int32(r1))
}

// IDeploymentManagerStatics is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentManagerStatics.
// IID: 6782a9d0-bfd0-50ea-81b0-32e9ed37cdf0
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager runtime class.
type IDeploymentManagerStatics struct {
	syswinrt.IInspectable
}

// IID_IDeploymentManagerStatics is the interface identifier for IDeploymentManagerStatics.
var IID_IDeploymentManagerStatics = win32.GUID{Data1: 0x6782a9d0, Data2: 0xbfd0, Data3: 0x50ea, Data4: [8]byte{0x81, 0xb0, 0x32, 0xe9, 0xed, 0x37, 0xcd, 0xf0}}

// GetStatus dispatches through IDeploymentManagerStatics's vtable slot 6.
func (self *IDeploymentManagerStatics) GetStatus() (*IDeploymentResult, error) {
	result := new(*IDeploymentResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Initialize dispatches through IDeploymentManagerStatics's vtable slot 7.
func (self *IDeploymentManagerStatics) Initialize() (*IDeploymentResult, error) {
	result := new(*IDeploymentResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IDeploymentManagerStatics2 is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentManagerStatics2.
// IID: f49c16ee-6ebc-5f15-bebb-2ba49f8c0b30
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager runtime class.
type IDeploymentManagerStatics2 struct {
	syswinrt.IInspectable
}

// IID_IDeploymentManagerStatics2 is the interface identifier for IDeploymentManagerStatics2.
var IID_IDeploymentManagerStatics2 = win32.GUID{Data1: 0xf49c16ee, Data2: 0x6ebc, Data3: 0x5f15, Data4: [8]byte{0xbe, 0xbb, 0x2b, 0xa4, 0x9f, 0x8c, 0x0b, 0x30}}

// Initialize dispatches through IDeploymentManagerStatics2's vtable slot 6.
func (self *IDeploymentManagerStatics2) Initialize(deploymentInitializeOptions *IDeploymentInitializeOptions) (*IDeploymentResult, error) {
	result := new(*IDeploymentResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(deploymentInitializeOptions)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IDeploymentResult is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentResult.
// IID: 27203f62-463d-587a-8eb7-870098901078
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentResult runtime class.
type IDeploymentResult struct {
	syswinrt.IInspectable
}

// IID_IDeploymentResult is the interface identifier for IDeploymentResult.
var IID_IDeploymentResult = win32.GUID{Data1: 0x27203f62, Data2: 0x463d, Data3: 0x587a, Data4: [8]byte{0x8e, 0xb7, 0x87, 0x00, 0x98, 0x90, 0x10, 0x78}}

// Status (propget get_Status) dispatches through IDeploymentResult's vtable slot 6.
func (self *IDeploymentResult) Status() (DeploymentStatus, error) {
	result := new(DeploymentStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExtendedError (propget get_ExtendedError) dispatches through IDeploymentResult's vtable slot 7.
func (self *IDeploymentResult) ExtendedError() (int32, error) {
	result := new(int32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IDeploymentResultFactory is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentResultFactory.
// IID: acd7bdae-4ae6-5cac-8205-1e8c305f953b
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentResult runtime class.
type IDeploymentResultFactory struct {
	syswinrt.IInspectable
}

// IID_IDeploymentResultFactory is the interface identifier for IDeploymentResultFactory.
var IID_IDeploymentResultFactory = win32.GUID{Data1: 0xacd7bdae, Data2: 0x4ae6, Data3: 0x5cac, Data4: [8]byte{0x82, 0x05, 0x1e, 0x8c, 0x30, 0x5f, 0x95, 0x3b}}

// CreateInstance dispatches through IDeploymentResultFactory's vtable slot 6.
func (self *IDeploymentResultFactory) CreateInstance(status DeploymentStatus, extendedError int32) (*IDeploymentResult, error) {
	result := new(*IDeploymentResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(status), uintptr(extendedError), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IReleaseInfoStatics is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IReleaseInfoStatics.
// IID: ed9be8ff-073c-5c66-bf97-ef0ce67405c3
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.ReleaseInfo runtime class.
type IReleaseInfoStatics struct {
	syswinrt.IInspectable
}

// IID_IReleaseInfoStatics is the interface identifier for IReleaseInfoStatics.
var IID_IReleaseInfoStatics = win32.GUID{Data1: 0xed9be8ff, Data2: 0x073c, Data3: 0x5c66, Data4: [8]byte{0xbf, 0x97, 0xef, 0x0c, 0xe6, 0x74, 0x05, 0xc3}}

// Major (propget get_Major) dispatches through IReleaseInfoStatics's vtable slot 6.
func (self *IReleaseInfoStatics) Major() (uint16, error) {
	result := new(uint16)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Minor (propget get_Minor) dispatches through IReleaseInfoStatics's vtable slot 7.
func (self *IReleaseInfoStatics) Minor() (uint16, error) {
	result := new(uint16)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Patch (propget get_Patch) dispatches through IReleaseInfoStatics's vtable slot 8.
func (self *IReleaseInfoStatics) Patch() (uint16, error) {
	result := new(uint16)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// VersionTag (propget get_VersionTag) dispatches through IReleaseInfoStatics's vtable slot 9.
func (self *IReleaseInfoStatics) VersionTag() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// AsString (propget get_AsString) dispatches through IReleaseInfoStatics's vtable slot 10.
func (self *IReleaseInfoStatics) AsString() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// IRuntimeCompatibilityOptions is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IRuntimeCompatibilityOptions.
// IID: d7403bd9-b25d-5b8f-8de1-9dcb57d99f6c
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeCompatibilityOptions runtime class.
type IRuntimeCompatibilityOptions struct {
	syswinrt.IInspectable
}

// IID_IRuntimeCompatibilityOptions is the interface identifier for IRuntimeCompatibilityOptions.
var IID_IRuntimeCompatibilityOptions = win32.GUID{Data1: 0xd7403bd9, Data2: 0xb25d, Data3: 0x5b8f, Data4: [8]byte{0x8d, 0xe1, 0x9d, 0xcb, 0x57, 0xd9, 0x9f, 0x6c}}

// PatchLevel1 (propget get_PatchLevel1) dispatches through IRuntimeCompatibilityOptions's vtable slot 6.
func (self *IRuntimeCompatibilityOptions) PatchLevel1() (WindowsAppRuntimeVersion, error) {
	result := new(WindowsAppRuntimeVersion)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetPatchLevel1 (propput put_PatchLevel1) dispatches through IRuntimeCompatibilityOptions's vtable slot 7.
func (self *IRuntimeCompatibilityOptions) SetPatchLevel1(value WindowsAppRuntimeVersion) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(&value))))
	return win32.ErrIfFailed(int32(r1))
}

// PatchLevel2 (propget get_PatchLevel2) dispatches through IRuntimeCompatibilityOptions's vtable slot 8.
func (self *IRuntimeCompatibilityOptions) PatchLevel2() (WindowsAppRuntimeVersion, error) {
	result := new(WindowsAppRuntimeVersion)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetPatchLevel2 (propput put_PatchLevel2) dispatches through IRuntimeCompatibilityOptions's vtable slot 9.
func (self *IRuntimeCompatibilityOptions) SetPatchLevel2(value WindowsAppRuntimeVersion) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(&value))))
	return win32.ErrIfFailed(int32(r1))
}

// DisabledChanges (propget get_DisabledChanges) dispatches through IRuntimeCompatibilityOptions's vtable slot 10.
func (self *IRuntimeCompatibilityOptions) DisabledChanges() (*IVectorOfRuntimeCompatibilityChange, error) {
	result := new(*IVectorOfRuntimeCompatibilityChange)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Apply dispatches through IRuntimeCompatibilityOptions's vtable slot 11.
func (self *IRuntimeCompatibilityOptions) Apply() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// IRuntimeInfoStatics is the WinRT interface Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IRuntimeInfoStatics.
// IID: e5cb9549-8951-590e-a753-8f281cd77ab5
// Exclusive to the Microsoft.Windows.ApplicationModel.WindowsAppRuntime.RuntimeInfo runtime class.
type IRuntimeInfoStatics struct {
	syswinrt.IInspectable
}

// IID_IRuntimeInfoStatics is the interface identifier for IRuntimeInfoStatics.
var IID_IRuntimeInfoStatics = win32.GUID{Data1: 0xe5cb9549, Data2: 0x8951, Data3: 0x590e, Data4: [8]byte{0xa7, 0x53, 0x8f, 0x28, 0x1c, 0xd7, 0x7a, 0xb5}}

// Version (propget get_Version) dispatches through IRuntimeInfoStatics's vtable slot 6.
func (self *IRuntimeInfoStatics) Version() (wrtapplicationmodel.PackageVersion, error) {
	result := new(wrtapplicationmodel.PackageVersion)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// AsString (propget get_AsString) dispatches through IRuntimeInfoStatics's vtable slot 7.
func (self *IRuntimeInfoStatics) AsString() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}
