// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package badgenotifications

// BadgeNotificationsContract is Microsoft.Windows.BadgeNotifications.BadgeNotificationsContract.
type BadgeNotificationsContract struct {
}
