// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package universalbgtask

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	wrtapplicationmodelbackground "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/applicationmodel/background"
)

// Task is the Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.Task runtime class, surfaced through its
// default interface ITask. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type Task struct {
	ITask
}

// NewTask activates Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.Task through its default
// constructor.
func NewTask() (*Task, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.ApplicationModel.Background.UniversalBGTask.Task")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[Task](unsafe.Pointer(instance), &IID_ITask)
}

// AsTask queries the instance's ITask interface.
// The returned reference is owned by the caller.
func (self *Task) AsTask() (*ITask, error) {
	return winrt.QueryInterface[ITask](unsafe.Pointer(self), &IID_ITask)
}

// AsBackgroundTask queries the instance's wrtapplicationmodelbackground.IBackgroundTask interface.
// The returned reference is owned by the caller.
func (self *Task) AsBackgroundTask() (*wrtapplicationmodelbackground.IBackgroundTask, error) {
	return winrt.QueryInterface[wrtapplicationmodelbackground.IBackgroundTask](unsafe.Pointer(self), &wrtapplicationmodelbackground.IID_IBackgroundTask)
}
