// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

// Package content binds the Microsoft.UI.Content API surface of the Windows App SDK.
package content
