// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package resources

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// ICustomXamlResourceLoader is the WinRT interface Microsoft.UI.Xaml.Resources.ICustomXamlResourceLoader.
// IID: 2832c2e5-2ace-5993-a173-3c9c3b992b2e
// Exclusive to the Microsoft.UI.Xaml.Resources.CustomXamlResourceLoader runtime class.
type ICustomXamlResourceLoader struct {
	syswinrt.IInspectable
}

// IID_ICustomXamlResourceLoader is the interface identifier for ICustomXamlResourceLoader.
var IID_ICustomXamlResourceLoader = win32.GUID{Data1: 0x2832c2e5, Data2: 0x2ace, Data3: 0x5993, Data4: [8]byte{0xa1, 0x73, 0x3c, 0x9c, 0x3b, 0x99, 0x2b, 0x2e}}

// ICustomXamlResourceLoaderFactory is the WinRT interface Microsoft.UI.Xaml.Resources.ICustomXamlResourceLoaderFactory.
// IID: 174d49a6-e1e2-5f7b-a618-a8a953d1b5a0
// Exclusive to the Microsoft.UI.Xaml.Resources.CustomXamlResourceLoader runtime class.
type ICustomXamlResourceLoaderFactory struct {
	syswinrt.IInspectable
}

// IID_ICustomXamlResourceLoaderFactory is the interface identifier for ICustomXamlResourceLoaderFactory.
var IID_ICustomXamlResourceLoaderFactory = win32.GUID{Data1: 0x174d49a6, Data2: 0xe1e2, Data3: 0x5f7b, Data4: [8]byte{0xa6, 0x18, 0xa8, 0xa9, 0x53, 0xd1, 0xb5, 0xa0}}

// CreateInstance dispatches through ICustomXamlResourceLoaderFactory's vtable slot 6.
func (self *ICustomXamlResourceLoaderFactory) CreateInstance(baseInterface *syswinrt.IInspectable, innerInterface **syswinrt.IInspectable) (*ICustomXamlResourceLoader, error) {
	result := new(*ICustomXamlResourceLoader)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(baseInterface)), uintptr(winrt.OutParam(unsafe.Pointer(innerInterface))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ICustomXamlResourceLoaderOverrides is the WinRT interface Microsoft.UI.Xaml.Resources.ICustomXamlResourceLoaderOverrides.
// IID: 84bb504c-6730-586a-bd04-9198264b2dc7
// Exclusive to the Microsoft.UI.Xaml.Resources.CustomXamlResourceLoader runtime class.
type ICustomXamlResourceLoaderOverrides struct {
	syswinrt.IInspectable
}

// IID_ICustomXamlResourceLoaderOverrides is the interface identifier for ICustomXamlResourceLoaderOverrides.
var IID_ICustomXamlResourceLoaderOverrides = win32.GUID{Data1: 0x84bb504c, Data2: 0x6730, Data3: 0x586a, Data4: [8]byte{0xbd, 0x04, 0x91, 0x98, 0x26, 0x4b, 0x2d, 0xc7}}

// GetResource dispatches through ICustomXamlResourceLoaderOverrides's vtable slot 6.
func (self *ICustomXamlResourceLoaderOverrides) GetResource(resourceId string, objectType string, propertyName string, propertyType string) (*syswinrt.IInspectable, error) {
	hResourceId, err := winrt.NewHString(resourceId)
	if err != nil {
		return nil, err
	}
	defer hResourceId.Close()
	hObjectType, err := winrt.NewHString(objectType)
	if err != nil {
		return nil, err
	}
	defer hObjectType.Close()
	hPropertyName, err := winrt.NewHString(propertyName)
	if err != nil {
		return nil, err
	}
	defer hPropertyName.Close()
	hPropertyType, err := winrt.NewHString(propertyType)
	if err != nil {
		return nil, err
	}
	defer hPropertyType.Close()
	result := new(*syswinrt.IInspectable)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hResourceId.Raw()), uintptr(hObjectType.Raw()), uintptr(hPropertyName.Raw()), uintptr(hPropertyType.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ICustomXamlResourceLoaderStatics is the WinRT interface Microsoft.UI.Xaml.Resources.ICustomXamlResourceLoaderStatics.
// IID: e08a5a92-b1a2-539a-9d4a-7994e4468cd7
// Exclusive to the Microsoft.UI.Xaml.Resources.CustomXamlResourceLoader runtime class.
type ICustomXamlResourceLoaderStatics struct {
	syswinrt.IInspectable
}

// IID_ICustomXamlResourceLoaderStatics is the interface identifier for ICustomXamlResourceLoaderStatics.
var IID_ICustomXamlResourceLoaderStatics = win32.GUID{Data1: 0xe08a5a92, Data2: 0xb1a2, Data3: 0x539a, Data4: [8]byte{0x9d, 0x4a, 0x79, 0x94, 0xe4, 0x46, 0x8c, 0xd7}}

// Current (propget get_Current) dispatches through ICustomXamlResourceLoaderStatics's vtable slot 6.
func (self *ICustomXamlResourceLoaderStatics) Current() (*ICustomXamlResourceLoader, error) {
	result := new(*ICustomXamlResourceLoader)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// SetCurrent (propput put_Current) dispatches through ICustomXamlResourceLoaderStatics's vtable slot 7.
func (self *ICustomXamlResourceLoaderStatics) SetCurrent(value *ICustomXamlResourceLoader) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}
