// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package automation

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	uixaml "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/ui/xaml"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// IVectorOfAutomationAnnotation is the WinRT interface Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Automation.AutomationAnnotation>.
// IID: e047e428-66a6-5759-a751-84f2bf6fdb30
// Requires: Windows.Foundation.Collections.IIterable`1<Microsoft.UI.Xaml.Automation.AutomationAnnotation>.
type IVectorOfAutomationAnnotation struct {
	syswinrt.IInspectable
}

// IID_IVectorOfAutomationAnnotation is the interface identifier for IVectorOfAutomationAnnotation.
var IID_IVectorOfAutomationAnnotation = win32.GUID{Data1: 0xe047e428, Data2: 0x66a6, Data3: 0x5759, Data4: [8]byte{0xa7, 0x51, 0x84, 0xf2, 0xbf, 0x6f, 0xdb, 0x30}}

// GetAt dispatches through IVectorOfAutomationAnnotation's vtable slot 6.
func (self *IVectorOfAutomationAnnotation) GetAt(index uint32) (*IAutomationAnnotation, error) {
	result := new(*IAutomationAnnotation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorOfAutomationAnnotation's vtable slot 7.
func (self *IVectorOfAutomationAnnotation) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfAutomationAnnotation's vtable slot 8.
func (self *IVectorOfAutomationAnnotation) GetView() (*IVectorViewOfAutomationAnnotation, error) {
	result := new(*IVectorViewOfAutomationAnnotation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfAutomationAnnotation's vtable slot 9.
func (self *IVectorOfAutomationAnnotation) IndexOf(value *IAutomationAnnotation, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfAutomationAnnotation's vtable slot 10.
func (self *IVectorOfAutomationAnnotation) SetAt(index uint32, value *IAutomationAnnotation) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfAutomationAnnotation's vtable slot 11.
func (self *IVectorOfAutomationAnnotation) InsertAt(index uint32, value *IAutomationAnnotation) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfAutomationAnnotation's vtable slot 12.
func (self *IVectorOfAutomationAnnotation) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfAutomationAnnotation's vtable slot 13.
func (self *IVectorOfAutomationAnnotation) Append(value *IAutomationAnnotation) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfAutomationAnnotation's vtable slot 14.
func (self *IVectorOfAutomationAnnotation) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfAutomationAnnotation's vtable slot 15.
func (self *IVectorOfAutomationAnnotation) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// IVectorOfDependencyObject is the WinRT interface Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.DependencyObject>.
// IID: 8e6b597a-ab20-585f-9db1-9394aac5a469
// Requires: Windows.Foundation.Collections.IIterable`1<Microsoft.UI.Xaml.DependencyObject>.
type IVectorOfDependencyObject struct {
	syswinrt.IInspectable
}

// IID_IVectorOfDependencyObject is the interface identifier for IVectorOfDependencyObject.
var IID_IVectorOfDependencyObject = win32.GUID{Data1: 0x8e6b597a, Data2: 0xab20, Data3: 0x585f, Data4: [8]byte{0x9d, 0xb1, 0x93, 0x94, 0xaa, 0xc5, 0xa4, 0x69}}

// GetAt dispatches through IVectorOfDependencyObject's vtable slot 6.
func (self *IVectorOfDependencyObject) GetAt(index uint32) (*uixaml.IDependencyObject, error) {
	result := new(*uixaml.IDependencyObject)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorOfDependencyObject's vtable slot 7.
func (self *IVectorOfDependencyObject) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfDependencyObject's vtable slot 8.
func (self *IVectorOfDependencyObject) GetView() (*IVectorViewOfDependencyObject, error) {
	result := new(*IVectorViewOfDependencyObject)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfDependencyObject's vtable slot 9.
func (self *IVectorOfDependencyObject) IndexOf(value *uixaml.IDependencyObject, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfDependencyObject's vtable slot 10.
func (self *IVectorOfDependencyObject) SetAt(index uint32, value *uixaml.IDependencyObject) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfDependencyObject's vtable slot 11.
func (self *IVectorOfDependencyObject) InsertAt(index uint32, value *uixaml.IDependencyObject) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfDependencyObject's vtable slot 12.
func (self *IVectorOfDependencyObject) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfDependencyObject's vtable slot 13.
func (self *IVectorOfDependencyObject) Append(value *uixaml.IDependencyObject) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfDependencyObject's vtable slot 14.
func (self *IVectorOfDependencyObject) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfDependencyObject's vtable slot 15.
func (self *IVectorOfDependencyObject) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// IVectorOfUIElement is the WinRT interface Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.UIElement>.
// IID: ea4a1af0-4286-5f11-8142-6b0169f4e9de
// Requires: Windows.Foundation.Collections.IIterable`1<Microsoft.UI.Xaml.UIElement>.
type IVectorOfUIElement struct {
	syswinrt.IInspectable
}

// IID_IVectorOfUIElement is the interface identifier for IVectorOfUIElement.
var IID_IVectorOfUIElement = win32.GUID{Data1: 0xea4a1af0, Data2: 0x4286, Data3: 0x5f11, Data4: [8]byte{0x81, 0x42, 0x6b, 0x01, 0x69, 0xf4, 0xe9, 0xde}}

// GetAt dispatches through IVectorOfUIElement's vtable slot 6.
func (self *IVectorOfUIElement) GetAt(index uint32) (*uixaml.IUIElement, error) {
	result := new(*uixaml.IUIElement)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorOfUIElement's vtable slot 7.
func (self *IVectorOfUIElement) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfUIElement's vtable slot 8.
func (self *IVectorOfUIElement) GetView() (*IVectorViewOfUIElement, error) {
	result := new(*IVectorViewOfUIElement)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfUIElement's vtable slot 9.
func (self *IVectorOfUIElement) IndexOf(value *uixaml.IUIElement, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfUIElement's vtable slot 10.
func (self *IVectorOfUIElement) SetAt(index uint32, value *uixaml.IUIElement) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfUIElement's vtable slot 11.
func (self *IVectorOfUIElement) InsertAt(index uint32, value *uixaml.IUIElement) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfUIElement's vtable slot 12.
func (self *IVectorOfUIElement) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfUIElement's vtable slot 13.
func (self *IVectorOfUIElement) Append(value *uixaml.IUIElement) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfUIElement's vtable slot 14.
func (self *IVectorOfUIElement) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfUIElement's vtable slot 15.
func (self *IVectorOfUIElement) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// slot 16: GetMany skipped: conformant array

// slot 17: ReplaceAll skipped: conformant array

// IVectorViewOfAutomationAnnotation is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Microsoft.UI.Xaml.Automation.AutomationAnnotation>.
// IID: 15c04825-b975-5bc5-adf9-e3b6062a7afa
// Requires: Windows.Foundation.Collections.IIterable`1<Microsoft.UI.Xaml.Automation.AutomationAnnotation>.
type IVectorViewOfAutomationAnnotation struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfAutomationAnnotation is the interface identifier for IVectorViewOfAutomationAnnotation.
var IID_IVectorViewOfAutomationAnnotation = win32.GUID{Data1: 0x15c04825, Data2: 0xb975, Data3: 0x5bc5, Data4: [8]byte{0xad, 0xf9, 0xe3, 0xb6, 0x06, 0x2a, 0x7a, 0xfa}}

// GetAt dispatches through IVectorViewOfAutomationAnnotation's vtable slot 6.
func (self *IVectorViewOfAutomationAnnotation) GetAt(index uint32) (*IAutomationAnnotation, error) {
	result := new(*IAutomationAnnotation)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfAutomationAnnotation's vtable slot 7.
func (self *IVectorViewOfAutomationAnnotation) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfAutomationAnnotation's vtable slot 8.
func (self *IVectorViewOfAutomationAnnotation) IndexOf(value *IAutomationAnnotation, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IVectorViewOfDependencyObject is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Microsoft.UI.Xaml.DependencyObject>.
// IID: 9eddd815-4420-5639-9b26-eab8013fa294
// Requires: Windows.Foundation.Collections.IIterable`1<Microsoft.UI.Xaml.DependencyObject>.
type IVectorViewOfDependencyObject struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfDependencyObject is the interface identifier for IVectorViewOfDependencyObject.
var IID_IVectorViewOfDependencyObject = win32.GUID{Data1: 0x9eddd815, Data2: 0x4420, Data3: 0x5639, Data4: [8]byte{0x9b, 0x26, 0xea, 0xb8, 0x01, 0x3f, 0xa2, 0x94}}

// GetAt dispatches through IVectorViewOfDependencyObject's vtable slot 6.
func (self *IVectorViewOfDependencyObject) GetAt(index uint32) (*uixaml.IDependencyObject, error) {
	result := new(*uixaml.IDependencyObject)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfDependencyObject's vtable slot 7.
func (self *IVectorViewOfDependencyObject) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfDependencyObject's vtable slot 8.
func (self *IVectorViewOfDependencyObject) IndexOf(value *uixaml.IDependencyObject, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array

// IVectorViewOfUIElement is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Microsoft.UI.Xaml.UIElement>.
// IID: 4fdea5ee-c725-5026-ba83-24e5771357c6
// Requires: Windows.Foundation.Collections.IIterable`1<Microsoft.UI.Xaml.UIElement>.
type IVectorViewOfUIElement struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfUIElement is the interface identifier for IVectorViewOfUIElement.
var IID_IVectorViewOfUIElement = win32.GUID{Data1: 0x4fdea5ee, Data2: 0xc725, Data3: 0x5026, Data4: [8]byte{0xba, 0x83, 0x24, 0xe5, 0x77, 0x13, 0x57, 0xc6}}

// GetAt dispatches through IVectorViewOfUIElement's vtable slot 6.
func (self *IVectorViewOfUIElement) GetAt(index uint32) (*uixaml.IUIElement, error) {
	result := new(*uixaml.IUIElement)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfUIElement's vtable slot 7.
func (self *IVectorViewOfUIElement) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfUIElement's vtable slot 8.
func (self *IVectorViewOfUIElement) IndexOf(value *uixaml.IUIElement, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// slot 9: GetMany skipped: conformant array
