// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

// Package composition binds the Microsoft.UI.Composition API surface of the Windows App SDK.
package composition
