// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

// Package systembackdrops binds the Microsoft.UI.Composition.SystemBackdrops API surface of the Windows App SDK.
package systembackdrops
