// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package appnotifications

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// IAsyncOperationOfAppNotificationProgressResult is the WinRT interface Windows.Foundation.IAsyncOperation`1<Microsoft.Windows.AppNotifications.AppNotificationProgressResult>.
// IID: aa739d3f-d458-5d30-b292-de6d52979eb4
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfAppNotificationProgressResult struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfAppNotificationProgressResult is the interface identifier for IAsyncOperationOfAppNotificationProgressResult.
var IID_IAsyncOperationOfAppNotificationProgressResult = win32.GUID{Data1: 0xaa739d3f, Data2: 0xd458, Data3: 0x5d30, Data4: [8]byte{0xb2, 0x92, 0xde, 0x6d, 0x52, 0x97, 0x9e, 0xb4}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfAppNotificationProgressResult's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfAppNotificationProgressResult) SetCompleted(handler *AsyncOperationCompletedHandlerOfAppNotificationProgressResult) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: Windows.Foundation.AsyncOperationCompletedHandler`1 is returned, not passed

// GetResults dispatches through IAsyncOperationOfAppNotificationProgressResult's vtable slot 8.
func (self *IAsyncOperationOfAppNotificationProgressResult) GetResults() (AppNotificationProgressResult, error) {
	result := new(AppNotificationProgressResult)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IAsyncOperationOfIVectorOfAppNotification is the WinRT interface Windows.Foundation.IAsyncOperation`1<Windows.Foundation.Collections.IVector`1<Microsoft.Windows.AppNotifications.AppNotification>>.
// IID: 704700c2-f4a1-5edd-871a-d0ba8b9b4c59
// Requires: Windows.Foundation.IAsyncInfo.
type IAsyncOperationOfIVectorOfAppNotification struct {
	syswinrt.IInspectable
}

// IID_IAsyncOperationOfIVectorOfAppNotification is the interface identifier for IAsyncOperationOfIVectorOfAppNotification.
var IID_IAsyncOperationOfIVectorOfAppNotification = win32.GUID{Data1: 0x704700c2, Data2: 0xf4a1, Data3: 0x5edd, Data4: [8]byte{0x87, 0x1a, 0xd0, 0xba, 0x8b, 0x9b, 0x4c, 0x59}}

// SetCompleted (propput put_Completed) dispatches through IAsyncOperationOfIVectorOfAppNotification's vtable slot 6.
// A nil handler passes NULL at the ABI (WinRT accepts it where a handler may be cleared).
func (self *IAsyncOperationOfIVectorOfAppNotification) SetCompleted(handler *AsyncOperationCompletedHandlerOfIVectorOfAppNotification) error {
	_handler := uintptr(0)
	if handler != nil {
		_handler = handler.Ptr()
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), _handler)
	return win32.ErrIfFailed(int32(r1))
}

// slot 7: get_Completed skipped: Windows.Foundation.AsyncOperationCompletedHandler`1 is returned, not passed

// GetResults dispatches through IAsyncOperationOfIVectorOfAppNotification's vtable slot 8.
func (self *IAsyncOperationOfIVectorOfAppNotification) GetResults() (*IVectorOfAppNotification, error) {
	result := new(*IVectorOfAppNotification)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IMapOfStringAndString is the WinRT interface Windows.Foundation.Collections.IMap`2<String, String>.
// IID: f6d1f700-49c2-52ae-8154-826f9908773c
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Foundation.Collections.IKeyValuePair`2<String, String>>.
type IMapOfStringAndString struct {
	syswinrt.IInspectable
}

// IID_IMapOfStringAndString is the interface identifier for IMapOfStringAndString.
var IID_IMapOfStringAndString = win32.GUID{Data1: 0xf6d1f700, Data2: 0x49c2, Data3: 0x52ae, Data4: [8]byte{0x81, 0x54, 0x82, 0x6f, 0x99, 0x08, 0x77, 0x3c}}

// Lookup dispatches through IMapOfStringAndString's vtable slot 6.
func (self *IMapOfStringAndString) Lookup(key string) (string, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return "", err
	}
	defer hKey.Close()
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IMapOfStringAndString's vtable slot 7.
func (self *IMapOfStringAndString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasKey dispatches through IMapOfStringAndString's vtable slot 8.
func (self *IMapOfStringAndString) HasKey(key string) (bool, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return false, err
	}
	defer hKey.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IMapOfStringAndString's vtable slot 9.
func (self *IMapOfStringAndString) GetView() (*IMapViewOfStringAndString, error) {
	result := new(*IMapViewOfStringAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Insert dispatches through IMapOfStringAndString's vtable slot 10.
func (self *IMapOfStringAndString) Insert(key string, value string) (bool, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return false, err
	}
	defer hKey.Close()
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return false, err
	}
	defer hValue.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(hValue.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// Remove dispatches through IMapOfStringAndString's vtable slot 11.
func (self *IMapOfStringAndString) Remove(key string) error {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return err
	}
	defer hKey.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IMapOfStringAndString's vtable slot 12.
func (self *IMapOfStringAndString) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// IMapViewOfStringAndString is the WinRT interface Windows.Foundation.Collections.IMapView`2<String, String>.
// IID: ac7f26f2-feb7-5b2a-8ac4-345bc62caede
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Foundation.Collections.IKeyValuePair`2<String, String>>.
type IMapViewOfStringAndString struct {
	syswinrt.IInspectable
}

// IID_IMapViewOfStringAndString is the interface identifier for IMapViewOfStringAndString.
var IID_IMapViewOfStringAndString = win32.GUID{Data1: 0xac7f26f2, Data2: 0xfeb7, Data3: 0x5b2a, Data4: [8]byte{0x8a, 0xc4, 0x34, 0x5b, 0xc6, 0x2c, 0xae, 0xde}}

// Lookup dispatches through IMapViewOfStringAndString's vtable slot 6.
func (self *IMapViewOfStringAndString) Lookup(key string) (string, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return "", err
	}
	defer hKey.Close()
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IMapViewOfStringAndString's vtable slot 7.
func (self *IMapViewOfStringAndString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasKey dispatches through IMapViewOfStringAndString's vtable slot 8.
func (self *IMapViewOfStringAndString) HasKey(key string) (bool, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return false, err
	}
	defer hKey.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// Split dispatches through IMapViewOfStringAndString's vtable slot 9.
func (self *IMapViewOfStringAndString) Split(first **IMapViewOfStringAndString, second **IMapViewOfStringAndString) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(first))), uintptr(winrt.OutParam(unsafe.Pointer(second))))
	return win32.ErrIfFailed(int32(r1))
}

// IVectorOfAppNotification is the WinRT interface Windows.Foundation.Collections.IVector`1<Microsoft.Windows.AppNotifications.AppNotification>.
// IID: de618ddb-bebc-5c93-91fe-ebd890df7cb7
// Requires: Windows.Foundation.Collections.IIterable`1<Microsoft.Windows.AppNotifications.AppNotification>.
type IVectorOfAppNotification struct {
	syswinrt.IInspectable
}

// IID_IVectorOfAppNotification is the interface identifier for IVectorOfAppNotification.
var IID_IVectorOfAppNotification = win32.GUID{Data1: 0xde618ddb, Data2: 0xbebc, Data3: 0x5c93, Data4: [8]byte{0x91, 0xfe, 0xeb, 0xd8, 0x90, 0xdf, 0x7c, 0xb7}}

// GetAt dispatches through IVectorOfAppNotification's vtable slot 6.
func (self *IVectorOfAppNotification) GetAt(index uint32) (*IAppNotification, error) {
	result := new(*IAppNotification)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorOfAppNotification's vtable slot 7.
func (self *IVectorOfAppNotification) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IVectorOfAppNotification's vtable slot 8.
func (self *IVectorOfAppNotification) GetView() (*IVectorViewOfAppNotification, error) {
	result := new(*IVectorViewOfAppNotification)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorOfAppNotification's vtable slot 9.
func (self *IVectorOfAppNotification) IndexOf(value *IAppNotification, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// SetAt dispatches through IVectorOfAppNotification's vtable slot 10.
func (self *IVectorOfAppNotification) SetAt(index uint32, value *IAppNotification) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// InsertAt dispatches through IVectorOfAppNotification's vtable slot 11.
func (self *IVectorOfAppNotification) InsertAt(index uint32, value *IAppNotification) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAt dispatches through IVectorOfAppNotification's vtable slot 12.
func (self *IVectorOfAppNotification) RemoveAt(index uint32) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)), uintptr(index))
	return win32.ErrIfFailed(int32(r1))
}

// Append dispatches through IVectorOfAppNotification's vtable slot 13.
func (self *IVectorOfAppNotification) Append(value *IAppNotification) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[13], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)))
	return win32.ErrIfFailed(int32(r1))
}

// RemoveAtEnd dispatches through IVectorOfAppNotification's vtable slot 14.
func (self *IVectorOfAppNotification) RemoveAtEnd() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[14], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IVectorOfAppNotification's vtable slot 15.
func (self *IVectorOfAppNotification) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[15], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// GetMany dispatches through IVectorOfAppNotification's vtable slot 16.
func (self *IVectorOfAppNotification) GetMany(startIndex uint32, items []*IAppNotification) (uint32, error) {
	_itemsSize := uintptr(len(items))
	_itemsData := uintptr(0)
	if len(items) > 0 {
		_itemsData = uintptr(winrt.OutParam(unsafe.Pointer(&items[0])))
	}
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[16], uintptr(unsafe.Pointer(self)), uintptr(startIndex), _itemsSize, _itemsData, uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ReplaceAll dispatches through IVectorOfAppNotification's vtable slot 17.
func (self *IVectorOfAppNotification) ReplaceAll(items []*IAppNotification) error {
	_itemsSize := uintptr(len(items))
	_itemsData := uintptr(0)
	if len(items) > 0 {
		_itemsData = uintptr(winrt.OutParam(unsafe.Pointer(&items[0])))
	}
	r1, _, _ := syscall.SyscallN(self.LpVtbl[17], uintptr(unsafe.Pointer(self)), _itemsSize, _itemsData)
	return win32.ErrIfFailed(int32(r1))
}

// IVectorViewOfAppNotification is the WinRT interface Windows.Foundation.Collections.IVectorView`1<Microsoft.Windows.AppNotifications.AppNotification>.
// IID: e645c6bd-e8e3-5b12-8b95-963bac29f974
// Requires: Windows.Foundation.Collections.IIterable`1<Microsoft.Windows.AppNotifications.AppNotification>.
type IVectorViewOfAppNotification struct {
	syswinrt.IInspectable
}

// IID_IVectorViewOfAppNotification is the interface identifier for IVectorViewOfAppNotification.
var IID_IVectorViewOfAppNotification = win32.GUID{Data1: 0xe645c6bd, Data2: 0xe8e3, Data3: 0x5b12, Data4: [8]byte{0x8b, 0x95, 0x96, 0x3b, 0xac, 0x29, 0xf9, 0x74}}

// GetAt dispatches through IVectorViewOfAppNotification's vtable slot 6.
func (self *IVectorViewOfAppNotification) GetAt(index uint32) (*IAppNotification, error) {
	result := new(*IAppNotification)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(index), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Size (propget get_Size) dispatches through IVectorViewOfAppNotification's vtable slot 7.
func (self *IVectorViewOfAppNotification) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IndexOf dispatches through IVectorViewOfAppNotification's vtable slot 8.
func (self *IVectorViewOfAppNotification) IndexOf(value *IAppNotification, index *uint32) (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(value)), uintptr(winrt.OutParam(unsafe.Pointer(index))), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// GetMany dispatches through IVectorViewOfAppNotification's vtable slot 9.
func (self *IVectorViewOfAppNotification) GetMany(startIndex uint32, items []*IAppNotification) (uint32, error) {
	_itemsSize := uintptr(len(items))
	_itemsData := uintptr(0)
	if len(items) > 0 {
		_itemsData = uintptr(winrt.OutParam(unsafe.Pointer(&items[0])))
	}
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(startIndex), _itemsSize, _itemsData, uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
