// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package pickers

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/ui"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// FileOpenPicker is the Microsoft.Windows.Storage.Pickers.FileOpenPicker runtime class, surfaced through its
// default interface IFileOpenPicker. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type FileOpenPicker struct {
	IFileOpenPicker
}

// AsFileOpenPicker queries the instance's IFileOpenPicker interface.
// The returned reference is owned by the caller.
func (self *FileOpenPicker) AsFileOpenPicker() (*IFileOpenPicker, error) {
	return winrt.QueryInterface[IFileOpenPicker](unsafe.Pointer(self), &IID_IFileOpenPicker)
}

// AsFileOpenPicker2 queries the instance's IFileOpenPicker2 interface.
// The returned reference is owned by the caller.
func (self *FileOpenPicker) AsFileOpenPicker2() (*IFileOpenPicker2, error) {
	return winrt.QueryInterface[IFileOpenPicker2](unsafe.Pointer(self), &IID_IFileOpenPicker2)
}

// CreateInstance constructs a Microsoft.Windows.Storage.Pickers.FileOpenPicker instance through
// Microsoft.Windows.Storage.Pickers.IFileOpenPickerFactory.CreateInstance. The activation factory is fetched
// per call (a factory cache is a future optimization).
func CreateInstance(windowId ui.WindowId) (*FileOpenPicker, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.Windows.Storage.Pickers.FileOpenPicker", &IID_IFileOpenPickerFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IFileOpenPickerFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	instance, err := factory.CreateInstance(windowId)
	if err != nil {
		return nil, err
	}
	return (*FileOpenPicker)(unsafe.Pointer(instance)), nil
}

// FileSavePicker is the Microsoft.Windows.Storage.Pickers.FileSavePicker runtime class, surfaced through its
// default interface IFileSavePicker. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type FileSavePicker struct {
	IFileSavePicker
}

// AsFileSavePicker queries the instance's IFileSavePicker interface.
// The returned reference is owned by the caller.
func (self *FileSavePicker) AsFileSavePicker() (*IFileSavePicker, error) {
	return winrt.QueryInterface[IFileSavePicker](unsafe.Pointer(self), &IID_IFileSavePicker)
}

// AsFileSavePicker2 queries the instance's IFileSavePicker2 interface.
// The returned reference is owned by the caller.
func (self *FileSavePicker) AsFileSavePicker2() (*IFileSavePicker2, error) {
	return winrt.QueryInterface[IFileSavePicker2](unsafe.Pointer(self), &IID_IFileSavePicker2)
}

// CreateInstanceFileSavePicker constructs a Microsoft.Windows.Storage.Pickers.FileSavePicker instance through
// Microsoft.Windows.Storage.Pickers.IFileSavePickerFactory.CreateInstance. The activation factory is fetched
// per call (a factory cache is a future optimization).
func CreateInstanceFileSavePicker(windowId ui.WindowId) (*FileSavePicker, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.Windows.Storage.Pickers.FileSavePicker", &IID_IFileSavePickerFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IFileSavePickerFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	instance, err := factory.CreateInstance(windowId)
	if err != nil {
		return nil, err
	}
	return (*FileSavePicker)(unsafe.Pointer(instance)), nil
}

// FolderPicker is the Microsoft.Windows.Storage.Pickers.FolderPicker runtime class, surfaced through its
// default interface IFolderPicker. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type FolderPicker struct {
	IFolderPicker
}

// AsFolderPicker queries the instance's IFolderPicker interface.
// The returned reference is owned by the caller.
func (self *FolderPicker) AsFolderPicker() (*IFolderPicker, error) {
	return winrt.QueryInterface[IFolderPicker](unsafe.Pointer(self), &IID_IFolderPicker)
}

// AsFolderPicker2 queries the instance's IFolderPicker2 interface.
// The returned reference is owned by the caller.
func (self *FolderPicker) AsFolderPicker2() (*IFolderPicker2, error) {
	return winrt.QueryInterface[IFolderPicker2](unsafe.Pointer(self), &IID_IFolderPicker2)
}

// CreateInstanceFolderPicker constructs a Microsoft.Windows.Storage.Pickers.FolderPicker instance through
// Microsoft.Windows.Storage.Pickers.IFolderPickerFactory.CreateInstance. The activation factory is fetched
// per call (a factory cache is a future optimization).
func CreateInstanceFolderPicker(windowId ui.WindowId) (*FolderPicker, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.Windows.Storage.Pickers.FolderPicker", &IID_IFolderPickerFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IFolderPickerFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	instance, err := factory.CreateInstance(windowId)
	if err != nil {
		return nil, err
	}
	return (*FolderPicker)(unsafe.Pointer(instance)), nil
}

// PickFileResult is the Microsoft.Windows.Storage.Pickers.PickFileResult runtime class, surfaced through its
// default interface IPickFileResult. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PickFileResult struct {
	IPickFileResult
}

// AsPickFileResult queries the instance's IPickFileResult interface.
// The returned reference is owned by the caller.
func (self *PickFileResult) AsPickFileResult() (*IPickFileResult, error) {
	return winrt.QueryInterface[IPickFileResult](unsafe.Pointer(self), &IID_IPickFileResult)
}

// PickFolderResult is the Microsoft.Windows.Storage.Pickers.PickFolderResult runtime class, surfaced through its
// default interface IPickFolderResult. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PickFolderResult struct {
	IPickFolderResult
}

// AsPickFolderResult queries the instance's IPickFolderResult interface.
// The returned reference is owned by the caller.
func (self *PickFolderResult) AsPickFolderResult() (*IPickFolderResult, error) {
	return winrt.QueryInterface[IPickFolderResult](unsafe.Pointer(self), &IID_IPickFolderResult)
}
