// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package providers

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// IMapOfStringAndString is the WinRT interface Windows.Foundation.Collections.IMap`2<String, String>.
// IID: f6d1f700-49c2-52ae-8154-826f9908773c
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Foundation.Collections.IKeyValuePair`2<String, String>>.
type IMapOfStringAndString struct {
	syswinrt.IInspectable
}

// IID_IMapOfStringAndString is the interface identifier for IMapOfStringAndString.
var IID_IMapOfStringAndString = win32.GUID{Data1: 0xf6d1f700, Data2: 0x49c2, Data3: 0x52ae, Data4: [8]byte{0x81, 0x54, 0x82, 0x6f, 0x99, 0x08, 0x77, 0x3c}}

// Lookup dispatches through IMapOfStringAndString's vtable slot 6.
func (self *IMapOfStringAndString) Lookup(key string) (string, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return "", err
	}
	defer hKey.Close()
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IMapOfStringAndString's vtable slot 7.
func (self *IMapOfStringAndString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasKey dispatches through IMapOfStringAndString's vtable slot 8.
func (self *IMapOfStringAndString) HasKey(key string) (bool, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return false, err
	}
	defer hKey.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// GetView dispatches through IMapOfStringAndString's vtable slot 9.
func (self *IMapOfStringAndString) GetView() (*IMapViewOfStringAndString, error) {
	result := new(*IMapViewOfStringAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// Insert dispatches through IMapOfStringAndString's vtable slot 10.
func (self *IMapOfStringAndString) Insert(key string, value string) (bool, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return false, err
	}
	defer hKey.Close()
	hValue, err := winrt.NewHString(value)
	if err != nil {
		return false, err
	}
	defer hValue.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(hValue.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// Remove dispatches through IMapOfStringAndString's vtable slot 11.
func (self *IMapOfStringAndString) Remove(key string) error {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return err
	}
	defer hKey.Close()
	r1, _, _ := syscall.SyscallN(self.LpVtbl[11], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()))
	return win32.ErrIfFailed(int32(r1))
}

// Clear dispatches through IMapOfStringAndString's vtable slot 12.
func (self *IMapOfStringAndString) Clear() error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[12], uintptr(unsafe.Pointer(self)))
	return win32.ErrIfFailed(int32(r1))
}

// IMapViewOfStringAndString is the WinRT interface Windows.Foundation.Collections.IMapView`2<String, String>.
// IID: ac7f26f2-feb7-5b2a-8ac4-345bc62caede
// Requires: Windows.Foundation.Collections.IIterable`1<Windows.Foundation.Collections.IKeyValuePair`2<String, String>>.
type IMapViewOfStringAndString struct {
	syswinrt.IInspectable
}

// IID_IMapViewOfStringAndString is the interface identifier for IMapViewOfStringAndString.
var IID_IMapViewOfStringAndString = win32.GUID{Data1: 0xac7f26f2, Data2: 0xfeb7, Data3: 0x5b2a, Data4: [8]byte{0x8a, 0xc4, 0x34, 0x5b, 0xc6, 0x2c, 0xae, 0xde}}

// Lookup dispatches through IMapViewOfStringAndString's vtable slot 6.
func (self *IMapViewOfStringAndString) Lookup(key string) (string, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return "", err
	}
	defer hKey.Close()
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Size (propget get_Size) dispatches through IMapViewOfStringAndString's vtable slot 7.
func (self *IMapViewOfStringAndString) Size() (uint32, error) {
	result := new(uint32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// HasKey dispatches through IMapViewOfStringAndString's vtable slot 8.
func (self *IMapViewOfStringAndString) HasKey(key string) (bool, error) {
	hKey, err := winrt.NewHString(key)
	if err != nil {
		return false, err
	}
	defer hKey.Close()
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(hKey.Raw()), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// Split dispatches through IMapViewOfStringAndString's vtable slot 9.
func (self *IMapViewOfStringAndString) Split(first **IMapViewOfStringAndString, second **IMapViewOfStringAndString) error {
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(first))), uintptr(winrt.OutParam(unsafe.Pointer(second))))
	return win32.ErrIfFailed(int32(r1))
}

// IReferenceOfBool is the WinRT interface Windows.Foundation.IReference`1<Bool>.
// IID: 3c00fd60-2950-5939-a21a-2d12c5a01b8a
// Requires: Windows.Foundation.IPropertyValue.
type IReferenceOfBool struct {
	syswinrt.IInspectable
}

// IID_IReferenceOfBool is the interface identifier for IReferenceOfBool.
var IID_IReferenceOfBool = win32.GUID{Data1: 0x3c00fd60, Data2: 0x2950, Data3: 0x5939, Data4: [8]byte{0xa2, 0x1a, 0x2d, 0x12, 0xc5, 0xa0, 0x1b, 0x8a}}

// Value (propget get_Value) dispatches through IReferenceOfBool's vtable slot 6.
func (self *IReferenceOfBool) Value() (bool, error) {
	result := new(byte)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result != 0, win32.ErrIfFailed(int32(r1))
}

// IReferenceOfInt32 is the WinRT interface Windows.Foundation.IReference`1<Int32>.
// IID: 548cefbd-bc8a-5fa0-8df2-957440fc8bf4
// Requires: Windows.Foundation.IPropertyValue.
type IReferenceOfInt32 struct {
	syswinrt.IInspectable
}

// IID_IReferenceOfInt32 is the interface identifier for IReferenceOfInt32.
var IID_IReferenceOfInt32 = win32.GUID{Data1: 0x548cefbd, Data2: 0xbc8a, Data3: 0x5fa0, Data4: [8]byte{0x8d, 0xf2, 0x95, 0x74, 0x40, 0xfc, 0x8b, 0xf4}}

// Value (propget get_Value) dispatches through IReferenceOfInt32's vtable slot 6.
func (self *IReferenceOfInt32) Value() (int32, error) {
	result := new(int32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
