// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

// Package power binds the Microsoft.Windows.System.Power API surface of the Windows App SDK.
package power
