// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package deployment

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	wrtapplicationmodel "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/applicationmodel"
)

// AddPackageOptions is the Microsoft.Windows.Management.Deployment.AddPackageOptions runtime class, surfaced through its
// default interface IAddPackageOptions. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type AddPackageOptions struct {
	IAddPackageOptions
}

// NewAddPackageOptions activates Microsoft.Windows.Management.Deployment.AddPackageOptions through its default
// constructor.
func NewAddPackageOptions() (*AddPackageOptions, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.AddPackageOptions")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[AddPackageOptions](unsafe.Pointer(instance), &IID_IAddPackageOptions)
}

// AsAddPackageOptions queries the instance's IAddPackageOptions interface.
// The returned reference is owned by the caller.
func (self *AddPackageOptions) AsAddPackageOptions() (*IAddPackageOptions, error) {
	return winrt.QueryInterface[IAddPackageOptions](unsafe.Pointer(self), &IID_IAddPackageOptions)
}

// AsAddPackageOptions2 queries the instance's IAddPackageOptions2 interface.
// The returned reference is owned by the caller.
func (self *AddPackageOptions) AsAddPackageOptions2() (*IAddPackageOptions2, error) {
	return winrt.QueryInterface[IAddPackageOptions2](unsafe.Pointer(self), &IID_IAddPackageOptions2)
}

// EnsureReadyOptions is the Microsoft.Windows.Management.Deployment.EnsureReadyOptions runtime class, surfaced through its
// default interface IEnsureReadyOptions. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type EnsureReadyOptions struct {
	IEnsureReadyOptions
}

// NewEnsureReadyOptions activates Microsoft.Windows.Management.Deployment.EnsureReadyOptions through its default
// constructor.
func NewEnsureReadyOptions() (*EnsureReadyOptions, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.EnsureReadyOptions")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[EnsureReadyOptions](unsafe.Pointer(instance), &IID_IEnsureReadyOptions)
}

// AsEnsureReadyOptions queries the instance's IEnsureReadyOptions interface.
// The returned reference is owned by the caller.
func (self *EnsureReadyOptions) AsEnsureReadyOptions() (*IEnsureReadyOptions, error) {
	return winrt.QueryInterface[IEnsureReadyOptions](unsafe.Pointer(self), &IID_IEnsureReadyOptions)
}

// AsEnsureReadyOptions2 queries the instance's IEnsureReadyOptions2 interface.
// The returned reference is owned by the caller.
func (self *EnsureReadyOptions) AsEnsureReadyOptions2() (*IEnsureReadyOptions2, error) {
	return winrt.QueryInterface[IEnsureReadyOptions2](unsafe.Pointer(self), &IID_IEnsureReadyOptions2)
}

// PackageCertificateEkuValidator is the Microsoft.Windows.Management.Deployment.PackageCertificateEkuValidator runtime class, surfaced through its
// default interface IPackageValidator. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageCertificateEkuValidator struct {
	IPackageValidator
}

// AsPackageValidator queries the instance's IPackageValidator interface.
// The returned reference is owned by the caller.
func (self *PackageCertificateEkuValidator) AsPackageValidator() (*IPackageValidator, error) {
	return winrt.QueryInterface[IPackageValidator](unsafe.Pointer(self), &IID_IPackageValidator)
}

// CreateInstance constructs a Microsoft.Windows.Management.Deployment.PackageCertificateEkuValidator instance through
// Microsoft.Windows.Management.Deployment.IPackageCertificateEkuValidatorFactory.CreateInstance. The activation factory is fetched
// per call (a factory cache is a future optimization).
func CreateInstance(expectedCertificateEku string) (*PackageCertificateEkuValidator, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageCertificateEkuValidator", &IID_IPackageCertificateEkuValidatorFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IPackageCertificateEkuValidatorFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	instance, err := factory.CreateInstance(expectedCertificateEku)
	if err != nil {
		return nil, err
	}
	return (*PackageCertificateEkuValidator)(unsafe.Pointer(instance)), nil
}

// PackageDeploymentManager is the Microsoft.Windows.Management.Deployment.PackageDeploymentManager runtime class, surfaced through its
// default interface IPackageDeploymentManager. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageDeploymentManager struct {
	IPackageDeploymentManager
}

// AsPackageDeploymentManager queries the instance's IPackageDeploymentManager interface.
// The returned reference is owned by the caller.
func (self *PackageDeploymentManager) AsPackageDeploymentManager() (*IPackageDeploymentManager, error) {
	return winrt.QueryInterface[IPackageDeploymentManager](unsafe.Pointer(self), &IID_IPackageDeploymentManager)
}

// AsPackageDeploymentManager2 queries the instance's IPackageDeploymentManager2 interface.
// The returned reference is owned by the caller.
func (self *PackageDeploymentManager) AsPackageDeploymentManager2() (*IPackageDeploymentManager2, error) {
	return winrt.QueryInterface[IPackageDeploymentManager2](unsafe.Pointer(self), &IID_IPackageDeploymentManager2)
}

// PackageDeploymentManagerStatics returns the Microsoft.Windows.Management.Deployment.IPackageDeploymentManagerStatics statics of the
// Microsoft.Windows.Management.Deployment.PackageDeploymentManager runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func PackageDeploymentManagerStatics() (*IPackageDeploymentManagerStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageDeploymentManager", &IID_IPackageDeploymentManagerStatics)
	if err != nil {
		return nil, err
	}
	return (*IPackageDeploymentManagerStatics)(unsafe.Pointer(factory)), nil
}

// PackageDeploymentManagerStatics2 returns the Microsoft.Windows.Management.Deployment.IPackageDeploymentManagerStatics2 statics of the
// Microsoft.Windows.Management.Deployment.PackageDeploymentManager runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func PackageDeploymentManagerStatics2() (*IPackageDeploymentManagerStatics2, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageDeploymentManager", &IID_IPackageDeploymentManagerStatics2)
	if err != nil {
		return nil, err
	}
	return (*IPackageDeploymentManagerStatics2)(unsafe.Pointer(factory)), nil
}

// PackageDeploymentResult is the Microsoft.Windows.Management.Deployment.PackageDeploymentResult runtime class, surfaced through its
// default interface IPackageDeploymentResult. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageDeploymentResult struct {
	IPackageDeploymentResult
}

// AsPackageDeploymentResult queries the instance's IPackageDeploymentResult interface.
// The returned reference is owned by the caller.
func (self *PackageDeploymentResult) AsPackageDeploymentResult() (*IPackageDeploymentResult, error) {
	return winrt.QueryInterface[IPackageDeploymentResult](unsafe.Pointer(self), &IID_IPackageDeploymentResult)
}

// PackageFamilyNameValidator is the Microsoft.Windows.Management.Deployment.PackageFamilyNameValidator runtime class, surfaced through its
// default interface IPackageValidator. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageFamilyNameValidator struct {
	IPackageValidator
}

// AsPackageValidator queries the instance's IPackageValidator interface.
// The returned reference is owned by the caller.
func (self *PackageFamilyNameValidator) AsPackageValidator() (*IPackageValidator, error) {
	return winrt.QueryInterface[IPackageValidator](unsafe.Pointer(self), &IID_IPackageValidator)
}

// CreateInstancePackageFamilyNameValidator constructs a Microsoft.Windows.Management.Deployment.PackageFamilyNameValidator instance through
// Microsoft.Windows.Management.Deployment.IPackageFamilyNameValidatorFactory.CreateInstance. The activation factory is fetched
// per call (a factory cache is a future optimization).
func CreateInstancePackageFamilyNameValidator(expectedPackageFamilyName string) (*PackageFamilyNameValidator, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageFamilyNameValidator", &IID_IPackageFamilyNameValidatorFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IPackageFamilyNameValidatorFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	instance, err := factory.CreateInstance(expectedPackageFamilyName)
	if err != nil {
		return nil, err
	}
	return (*PackageFamilyNameValidator)(unsafe.Pointer(instance)), nil
}

// PackageMinimumVersionValidator is the Microsoft.Windows.Management.Deployment.PackageMinimumVersionValidator runtime class, surfaced through its
// default interface IPackageValidator. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageMinimumVersionValidator struct {
	IPackageValidator
}

// AsPackageValidator queries the instance's IPackageValidator interface.
// The returned reference is owned by the caller.
func (self *PackageMinimumVersionValidator) AsPackageValidator() (*IPackageValidator, error) {
	return winrt.QueryInterface[IPackageValidator](unsafe.Pointer(self), &IID_IPackageValidator)
}

// CreateInstancePackageMinimumVersionValidator constructs a Microsoft.Windows.Management.Deployment.PackageMinimumVersionValidator instance through
// Microsoft.Windows.Management.Deployment.IPackageMinimumVersionValidatorFactory.CreateInstance. The activation factory is fetched
// per call (a factory cache is a future optimization).
func CreateInstancePackageMinimumVersionValidator(minimumVersion wrtapplicationmodel.PackageVersion) (*PackageMinimumVersionValidator, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageMinimumVersionValidator", &IID_IPackageMinimumVersionValidatorFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IPackageMinimumVersionValidatorFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	instance, err := factory.CreateInstance(minimumVersion)
	if err != nil {
		return nil, err
	}
	return (*PackageMinimumVersionValidator)(unsafe.Pointer(instance)), nil
}

// PackageRuntimeManager is the Microsoft.Windows.Management.Deployment.PackageRuntimeManager runtime class, surfaced through its
// default interface IPackageRuntimeManager. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageRuntimeManager struct {
	IPackageRuntimeManager
}

// AsPackageRuntimeManager queries the instance's IPackageRuntimeManager interface.
// The returned reference is owned by the caller.
func (self *PackageRuntimeManager) AsPackageRuntimeManager() (*IPackageRuntimeManager, error) {
	return winrt.QueryInterface[IPackageRuntimeManager](unsafe.Pointer(self), &IID_IPackageRuntimeManager)
}

// PackageRuntimeManagerStatics returns the Microsoft.Windows.Management.Deployment.IPackageRuntimeManagerStatics statics of the
// Microsoft.Windows.Management.Deployment.PackageRuntimeManager runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func PackageRuntimeManagerStatics() (*IPackageRuntimeManagerStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageRuntimeManager", &IID_IPackageRuntimeManagerStatics)
	if err != nil {
		return nil, err
	}
	return (*IPackageRuntimeManagerStatics)(unsafe.Pointer(factory)), nil
}

// PackageSet is the Microsoft.Windows.Management.Deployment.PackageSet runtime class, surfaced through its
// default interface IPackageSet. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageSet struct {
	IPackageSet
}

// NewPackageSet activates Microsoft.Windows.Management.Deployment.PackageSet through its default
// constructor.
func NewPackageSet() (*PackageSet, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.PackageSet")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[PackageSet](unsafe.Pointer(instance), &IID_IPackageSet)
}

// AsPackageSet queries the instance's IPackageSet interface.
// The returned reference is owned by the caller.
func (self *PackageSet) AsPackageSet() (*IPackageSet, error) {
	return winrt.QueryInterface[IPackageSet](unsafe.Pointer(self), &IID_IPackageSet)
}

// PackageSetItem is the Microsoft.Windows.Management.Deployment.PackageSetItem runtime class, surfaced through its
// default interface IPackageSetItem. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageSetItem struct {
	IPackageSetItem
}

// NewPackageSetItem activates Microsoft.Windows.Management.Deployment.PackageSetItem through its default
// constructor.
func NewPackageSetItem() (*PackageSetItem, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.PackageSetItem")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[PackageSetItem](unsafe.Pointer(instance), &IID_IPackageSetItem)
}

// AsPackageSetItem queries the instance's IPackageSetItem interface.
// The returned reference is owned by the caller.
func (self *PackageSetItem) AsPackageSetItem() (*IPackageSetItem, error) {
	return winrt.QueryInterface[IPackageSetItem](unsafe.Pointer(self), &IID_IPackageSetItem)
}

// PackageSetItemRuntimeDisposition is the Microsoft.Windows.Management.Deployment.PackageSetItemRuntimeDisposition runtime class, surfaced through its
// default interface IPackageSetItemRuntimeDisposition. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageSetItemRuntimeDisposition struct {
	IPackageSetItemRuntimeDisposition
}

// NewPackageSetItemRuntimeDisposition activates Microsoft.Windows.Management.Deployment.PackageSetItemRuntimeDisposition through its default
// constructor.
func NewPackageSetItemRuntimeDisposition() (*PackageSetItemRuntimeDisposition, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.PackageSetItemRuntimeDisposition")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[PackageSetItemRuntimeDisposition](unsafe.Pointer(instance), &IID_IPackageSetItemRuntimeDisposition)
}

// AsPackageSetItemRuntimeDisposition queries the instance's IPackageSetItemRuntimeDisposition interface.
// The returned reference is owned by the caller.
func (self *PackageSetItemRuntimeDisposition) AsPackageSetItemRuntimeDisposition() (*IPackageSetItemRuntimeDisposition, error) {
	return winrt.QueryInterface[IPackageSetItemRuntimeDisposition](unsafe.Pointer(self), &IID_IPackageSetItemRuntimeDisposition)
}

// PackageSetRuntimeDisposition is the Microsoft.Windows.Management.Deployment.PackageSetRuntimeDisposition runtime class, surfaced through its
// default interface IPackageSetRuntimeDisposition. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageSetRuntimeDisposition struct {
	IPackageSetRuntimeDisposition
}

// NewPackageSetRuntimeDisposition activates Microsoft.Windows.Management.Deployment.PackageSetRuntimeDisposition through its default
// constructor.
func NewPackageSetRuntimeDisposition() (*PackageSetRuntimeDisposition, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.PackageSetRuntimeDisposition")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[PackageSetRuntimeDisposition](unsafe.Pointer(instance), &IID_IPackageSetRuntimeDisposition)
}

// AsPackageSetRuntimeDisposition queries the instance's IPackageSetRuntimeDisposition interface.
// The returned reference is owned by the caller.
func (self *PackageSetRuntimeDisposition) AsPackageSetRuntimeDisposition() (*IPackageSetRuntimeDisposition, error) {
	return winrt.QueryInterface[IPackageSetRuntimeDisposition](unsafe.Pointer(self), &IID_IPackageSetRuntimeDisposition)
}

// PackageValidationEventArgs is the Microsoft.Windows.Management.Deployment.PackageValidationEventArgs runtime class, surfaced through its
// default interface IPackageValidationEventArgs. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageValidationEventArgs struct {
	IPackageValidationEventArgs
}

// AsPackageValidationEventArgs queries the instance's IPackageValidationEventArgs interface.
// The returned reference is owned by the caller.
func (self *PackageValidationEventArgs) AsPackageValidationEventArgs() (*IPackageValidationEventArgs, error) {
	return winrt.QueryInterface[IPackageValidationEventArgs](unsafe.Pointer(self), &IID_IPackageValidationEventArgs)
}

// PackageValidationEventSource is the Microsoft.Windows.Management.Deployment.PackageValidationEventSource runtime class, surfaced through its
// default interface IPackageValidationEventSource. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageValidationEventSource struct {
	IPackageValidationEventSource
}

// AsPackageValidationEventSource queries the instance's IPackageValidationEventSource interface.
// The returned reference is owned by the caller.
func (self *PackageValidationEventSource) AsPackageValidationEventSource() (*IPackageValidationEventSource, error) {
	return winrt.QueryInterface[IPackageValidationEventSource](unsafe.Pointer(self), &IID_IPackageValidationEventSource)
}

// PackageValidationHandler is the Microsoft.Windows.Management.Deployment.PackageValidationHandler runtime class, surfaced through its
// default interface IPackageValidationHandler. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageValidationHandler struct {
	IPackageValidationHandler
}

// AsPackageValidationHandler queries the instance's IPackageValidationHandler interface.
// The returned reference is owned by the caller.
func (self *PackageValidationHandler) AsPackageValidationHandler() (*IPackageValidationHandler, error) {
	return winrt.QueryInterface[IPackageValidationHandler](unsafe.Pointer(self), &IID_IPackageValidationHandler)
}

// CreateInstancePackageValidationHandler constructs a Microsoft.Windows.Management.Deployment.PackageValidationHandler instance through
// Microsoft.Windows.Management.Deployment.IPackageValidationHandlerFactory.CreateInstance. The activation factory is fetched
// per call (a factory cache is a future optimization).
func CreateInstancePackageValidationHandler(validator *IPackageValidator) (*PackageValidationHandler, error) {
	factoryUnknown, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageValidationHandler", &IID_IPackageValidationHandlerFactory)
	if err != nil {
		return nil, err
	}
	factory := (*IPackageValidationHandlerFactory)(unsafe.Pointer(factoryUnknown))
	defer factory.Release()
	instance, err := factory.CreateInstance(validator)
	if err != nil {
		return nil, err
	}
	return (*PackageValidationHandler)(unsafe.Pointer(instance)), nil
}

// PackageVolume is the Microsoft.Windows.Management.Deployment.PackageVolume runtime class, surfaced through its
// default interface IPackageVolume. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type PackageVolume struct {
	IPackageVolume
}

// AsPackageVolume queries the instance's IPackageVolume interface.
// The returned reference is owned by the caller.
func (self *PackageVolume) AsPackageVolume() (*IPackageVolume, error) {
	return winrt.QueryInterface[IPackageVolume](unsafe.Pointer(self), &IID_IPackageVolume)
}

// AsPackageVolume2 queries the instance's IPackageVolume2 interface.
// The returned reference is owned by the caller.
func (self *PackageVolume) AsPackageVolume2() (*IPackageVolume2, error) {
	return winrt.QueryInterface[IPackageVolume2](unsafe.Pointer(self), &IID_IPackageVolume2)
}

// PackageVolumeStatics returns the Microsoft.Windows.Management.Deployment.IPackageVolumeStatics statics of the
// Microsoft.Windows.Management.Deployment.PackageVolume runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func PackageVolumeStatics() (*IPackageVolumeStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageVolume", &IID_IPackageVolumeStatics)
	if err != nil {
		return nil, err
	}
	return (*IPackageVolumeStatics)(unsafe.Pointer(factory)), nil
}

// PackageVolumeStatics2 returns the Microsoft.Windows.Management.Deployment.IPackageVolumeStatics2 statics of the
// Microsoft.Windows.Management.Deployment.PackageVolume runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func PackageVolumeStatics2() (*IPackageVolumeStatics2, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.Windows.Management.Deployment.PackageVolume", &IID_IPackageVolumeStatics2)
	if err != nil {
		return nil, err
	}
	return (*IPackageVolumeStatics2)(unsafe.Pointer(factory)), nil
}

// ProvisionPackageOptions is the Microsoft.Windows.Management.Deployment.ProvisionPackageOptions runtime class, surfaced through its
// default interface IProvisionPackageOptions. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type ProvisionPackageOptions struct {
	IProvisionPackageOptions
}

// NewProvisionPackageOptions activates Microsoft.Windows.Management.Deployment.ProvisionPackageOptions through its default
// constructor.
func NewProvisionPackageOptions() (*ProvisionPackageOptions, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.ProvisionPackageOptions")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[ProvisionPackageOptions](unsafe.Pointer(instance), &IID_IProvisionPackageOptions)
}

// AsProvisionPackageOptions queries the instance's IProvisionPackageOptions interface.
// The returned reference is owned by the caller.
func (self *ProvisionPackageOptions) AsProvisionPackageOptions() (*IProvisionPackageOptions, error) {
	return winrt.QueryInterface[IProvisionPackageOptions](unsafe.Pointer(self), &IID_IProvisionPackageOptions)
}

// RegisterPackageOptions is the Microsoft.Windows.Management.Deployment.RegisterPackageOptions runtime class, surfaced through its
// default interface IRegisterPackageOptions. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type RegisterPackageOptions struct {
	IRegisterPackageOptions
}

// NewRegisterPackageOptions activates Microsoft.Windows.Management.Deployment.RegisterPackageOptions through its default
// constructor.
func NewRegisterPackageOptions() (*RegisterPackageOptions, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.RegisterPackageOptions")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[RegisterPackageOptions](unsafe.Pointer(instance), &IID_IRegisterPackageOptions)
}

// AsRegisterPackageOptions queries the instance's IRegisterPackageOptions interface.
// The returned reference is owned by the caller.
func (self *RegisterPackageOptions) AsRegisterPackageOptions() (*IRegisterPackageOptions, error) {
	return winrt.QueryInterface[IRegisterPackageOptions](unsafe.Pointer(self), &IID_IRegisterPackageOptions)
}

// RemovePackageOptions is the Microsoft.Windows.Management.Deployment.RemovePackageOptions runtime class, surfaced through its
// default interface IRemovePackageOptions. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type RemovePackageOptions struct {
	IRemovePackageOptions
}

// NewRemovePackageOptions activates Microsoft.Windows.Management.Deployment.RemovePackageOptions through its default
// constructor.
func NewRemovePackageOptions() (*RemovePackageOptions, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.RemovePackageOptions")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[RemovePackageOptions](unsafe.Pointer(instance), &IID_IRemovePackageOptions)
}

// AsRemovePackageOptions queries the instance's IRemovePackageOptions interface.
// The returned reference is owned by the caller.
func (self *RemovePackageOptions) AsRemovePackageOptions() (*IRemovePackageOptions, error) {
	return winrt.QueryInterface[IRemovePackageOptions](unsafe.Pointer(self), &IID_IRemovePackageOptions)
}

// StagePackageOptions is the Microsoft.Windows.Management.Deployment.StagePackageOptions runtime class, surfaced through its
// default interface IStagePackageOptions. Release when done (promoted from
// the embedded IInspectable → IUnknown chain).
type StagePackageOptions struct {
	IStagePackageOptions
}

// NewStagePackageOptions activates Microsoft.Windows.Management.Deployment.StagePackageOptions through its default
// constructor.
func NewStagePackageOptions() (*StagePackageOptions, error) {
	instance, err := winrt.ActivateInstance("Microsoft.Windows.Management.Deployment.StagePackageOptions")
	if err != nil {
		return nil, err
	}
	defer instance.Release()
	return winrt.QueryInterface[StagePackageOptions](unsafe.Pointer(instance), &IID_IStagePackageOptions)
}

// AsStagePackageOptions queries the instance's IStagePackageOptions interface.
// The returned reference is owned by the caller.
func (self *StagePackageOptions) AsStagePackageOptions() (*IStagePackageOptions, error) {
	return winrt.QueryInterface[IStagePackageOptions](unsafe.Pointer(self), &IID_IStagePackageOptions)
}

// AsStagePackageOptions2 queries the instance's IStagePackageOptions2 interface.
// The returned reference is owned by the caller.
func (self *StagePackageOptions) AsStagePackageOptions2() (*IStagePackageOptions2, error) {
	return winrt.QueryInterface[IStagePackageOptions2](unsafe.Pointer(self), &IID_IStagePackageOptions2)
}
