// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package foundation

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// DecimalHelperStatics returns the Microsoft.Windows.Foundation.IDecimalHelperStatics statics of the
// Microsoft.Windows.Foundation.DecimalHelper runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func DecimalHelperStatics() (*IDecimalHelperStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.Windows.Foundation.DecimalHelper", &IID_IDecimalHelperStatics)
	if err != nil {
		return nil, err
	}
	return (*IDecimalHelperStatics)(unsafe.Pointer(factory)), nil
}
