// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package globalization

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
)

// ApplicationLanguagesStatics returns the Microsoft.Windows.Globalization.IApplicationLanguagesStatics statics of the
// Microsoft.Windows.Globalization.ApplicationLanguages runtime class. The activation factory is queried for
// the statics IID directly, so the returned reference (owned by the caller;
// Release when done) is the statics interface itself.
func ApplicationLanguagesStatics() (*IApplicationLanguagesStatics, error) {
	factory, err := winrt.GetActivationFactory("Microsoft.Windows.Globalization.ApplicationLanguages", &IID_IApplicationLanguagesStatics)
	if err != nil {
		return nil, err
	}
	return (*IApplicationLanguagesStatics)(unsafe.Pointer(factory)), nil
}
