// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package imaging

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	syswinrt "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/winrt"
	graphicsimaging "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/graphics/imaging"
	windowsai "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/windows/ai"
	windowsaicontentsafety "github.com/deploymenttheory/go-bindings-windowsappsdk/bindings/winui/windows/ai/contentsafety"
	"github.com/deploymenttheory/go-bindings-winrt/bindings/runtime/winrt"
	wrtgraphicsimaging "github.com/deploymenttheory/go-bindings-winrt/bindings/winrt/graphics/imaging"
)

// IImageDescriptionGenerator is the WinRT interface Microsoft.Windows.AI.Imaging.IImageDescriptionGenerator.
// IID: 576b989e-9829-5682-91b0-a7110fa7d51e
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageDescriptionGenerator runtime class.
type IImageDescriptionGenerator struct {
	syswinrt.IInspectable
}

// IID_IImageDescriptionGenerator is the interface identifier for IImageDescriptionGenerator.
var IID_IImageDescriptionGenerator = win32.GUID{Data1: 0x576b989e, Data2: 0x9829, Data3: 0x5682, Data4: [8]byte{0x91, 0xb0, 0xa7, 0x11, 0x0f, 0xa7, 0xd5, 0x1e}}

// DescribeAsync dispatches through IImageDescriptionGenerator's vtable slot 6.
func (self *IImageDescriptionGenerator) DescribeAsync(image *graphicsimaging.IImageBuffer, kind ImageDescriptionKind, contentFilterOptions *windowsaicontentsafety.IContentFilterOptions) (*IAsyncOperationWithProgressOfImageDescriptionResultAndString, error) {
	result := new(*IAsyncOperationWithProgressOfImageDescriptionResultAndString)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(image)), uintptr(kind), uintptr(unsafe.Pointer(contentFilterOptions)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageDescriptionGeneratorStatics is the WinRT interface Microsoft.Windows.AI.Imaging.IImageDescriptionGeneratorStatics.
// IID: 5fb50b2a-5700-55a7-b413-6073b4b7f175
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageDescriptionGenerator runtime class.
type IImageDescriptionGeneratorStatics struct {
	syswinrt.IInspectable
}

// IID_IImageDescriptionGeneratorStatics is the interface identifier for IImageDescriptionGeneratorStatics.
var IID_IImageDescriptionGeneratorStatics = win32.GUID{Data1: 0x5fb50b2a, Data2: 0x5700, Data3: 0x55a7, Data4: [8]byte{0xb4, 0x13, 0x60, 0x73, 0xb4, 0xb7, 0xf1, 0x75}}

// GetReadyState dispatches through IImageDescriptionGeneratorStatics's vtable slot 6.
func (self *IImageDescriptionGeneratorStatics) GetReadyState() (windowsai.AIFeatureReadyState, error) {
	result := new(windowsai.AIFeatureReadyState)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// EnsureReadyAsync dispatches through IImageDescriptionGeneratorStatics's vtable slot 7.
func (self *IImageDescriptionGeneratorStatics) EnsureReadyAsync() (*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble, error) {
	result := new(*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateAsync dispatches through IImageDescriptionGeneratorStatics's vtable slot 8.
func (self *IImageDescriptionGeneratorStatics) CreateAsync() (*IAsyncOperationOfImageDescriptionGenerator, error) {
	result := new(*IAsyncOperationOfImageDescriptionGenerator)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageDescriptionResult is the WinRT interface Microsoft.Windows.AI.Imaging.IImageDescriptionResult.
// IID: a066dd0c-110b-5275-a635-52bed7519a2f
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageDescriptionResult runtime class.
type IImageDescriptionResult struct {
	syswinrt.IInspectable
}

// IID_IImageDescriptionResult is the interface identifier for IImageDescriptionResult.
var IID_IImageDescriptionResult = win32.GUID{Data1: 0xa066dd0c, Data2: 0x110b, Data3: 0x5275, Data4: [8]byte{0xa6, 0x35, 0x52, 0xbe, 0xd7, 0x51, 0x9a, 0x2f}}

// Description (propget get_Description) dispatches through IImageDescriptionResult's vtable slot 6.
func (self *IImageDescriptionResult) Description() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// Status (propget get_Status) dispatches through IImageDescriptionResult's vtable slot 7.
func (self *IImageDescriptionResult) Status() (ImageDescriptionResultStatus, error) {
	result := new(ImageDescriptionResultStatus)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageObjectExtractor is the WinRT interface Microsoft.Windows.AI.Imaging.IImageObjectExtractor.
// IID: 2919fdc0-d772-5fd9-a8b7-ffb56010c99c
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageObjectExtractor runtime class.
type IImageObjectExtractor struct {
	syswinrt.IInspectable
}

// IID_IImageObjectExtractor is the interface identifier for IImageObjectExtractor.
var IID_IImageObjectExtractor = win32.GUID{Data1: 0x2919fdc0, Data2: 0xd772, Data3: 0x5fd9, Data4: [8]byte{0xa8, 0xb7, 0xff, 0xb5, 0x60, 0x10, 0xc9, 0x9c}}

// GetSoftwareBitmapObjectMask dispatches through IImageObjectExtractor's vtable slot 6.
func (self *IImageObjectExtractor) GetSoftwareBitmapObjectMask(hint *IImageObjectExtractorHint) (*wrtgraphicsimaging.ISoftwareBitmap, error) {
	result := new(*wrtgraphicsimaging.ISoftwareBitmap)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(hint)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetImageBufferObjectMask dispatches through IImageObjectExtractor's vtable slot 7.
func (self *IImageObjectExtractor) GetImageBufferObjectMask(hint *IImageObjectExtractorHint) (*graphicsimaging.IImageBuffer, error) {
	result := new(*graphicsimaging.IImageBuffer)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(hint)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageObjectExtractorHint is the WinRT interface Microsoft.Windows.AI.Imaging.IImageObjectExtractorHint.
// IID: 1bd8d67c-8a7a-5fe7-98a5-cbdfeb509452
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageObjectExtractorHint runtime class.
type IImageObjectExtractorHint struct {
	syswinrt.IInspectable
}

// IID_IImageObjectExtractorHint is the interface identifier for IImageObjectExtractorHint.
var IID_IImageObjectExtractorHint = win32.GUID{Data1: 0x1bd8d67c, Data2: 0x8a7a, Data3: 0x5fe7, Data4: [8]byte{0x98, 0xa5, 0xcb, 0xdf, 0xeb, 0x50, 0x94, 0x52}}

// IncludeRects (propget get_IncludeRects) dispatches through IImageObjectExtractorHint's vtable slot 6.
func (self *IImageObjectExtractorHint) IncludeRects() (*IVectorViewOfRectInt32, error) {
	result := new(*IVectorViewOfRectInt32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IncludePoints (propget get_IncludePoints) dispatches through IImageObjectExtractorHint's vtable slot 7.
func (self *IImageObjectExtractorHint) IncludePoints() (*IVectorViewOfPointInt32, error) {
	result := new(*IVectorViewOfPointInt32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ExcludePoints (propget get_ExcludePoints) dispatches through IImageObjectExtractorHint's vtable slot 8.
func (self *IImageObjectExtractorHint) ExcludePoints() (*IVectorViewOfPointInt32, error) {
	result := new(*IVectorViewOfPointInt32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageObjectExtractorHintFactory is the WinRT interface Microsoft.Windows.AI.Imaging.IImageObjectExtractorHintFactory.
// IID: 5028f206-145d-5a70-9a51-e17e60cfbad8
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageObjectExtractorHint runtime class.
type IImageObjectExtractorHintFactory struct {
	syswinrt.IInspectable
}

// IID_IImageObjectExtractorHintFactory is the interface identifier for IImageObjectExtractorHintFactory.
var IID_IImageObjectExtractorHintFactory = win32.GUID{Data1: 0x5028f206, Data2: 0x145d, Data3: 0x5a70, Data4: [8]byte{0x9a, 0x51, 0xe1, 0x7e, 0x60, 0xcf, 0xba, 0xd8}}

// CreateInstance dispatches through IImageObjectExtractorHintFactory's vtable slot 6.
func (self *IImageObjectExtractorHintFactory) CreateInstance(includeRects *IVectorOfRectInt32, includePoints *IVectorOfPointInt32, excludePoints *IVectorOfPointInt32) (*IImageObjectExtractorHint, error) {
	result := new(*IImageObjectExtractorHint)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(includeRects)), uintptr(unsafe.Pointer(includePoints)), uintptr(unsafe.Pointer(excludePoints)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageObjectExtractorStatics is the WinRT interface Microsoft.Windows.AI.Imaging.IImageObjectExtractorStatics.
// IID: 38fa261e-2c33-54cb-9e10-98d50685743d
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageObjectExtractor runtime class.
type IImageObjectExtractorStatics struct {
	syswinrt.IInspectable
}

// IID_IImageObjectExtractorStatics is the interface identifier for IImageObjectExtractorStatics.
var IID_IImageObjectExtractorStatics = win32.GUID{Data1: 0x38fa261e, Data2: 0x2c33, Data3: 0x54cb, Data4: [8]byte{0x9e, 0x10, 0x98, 0xd5, 0x06, 0x85, 0x74, 0x3d}}

// CreateWithSoftwareBitmapAsync dispatches through IImageObjectExtractorStatics's vtable slot 6.
func (self *IImageObjectExtractorStatics) CreateWithSoftwareBitmapAsync(softwareBitmap *wrtgraphicsimaging.ISoftwareBitmap) (*IAsyncOperationOfImageObjectExtractor, error) {
	result := new(*IAsyncOperationOfImageObjectExtractor)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(softwareBitmap)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateWithImageBufferAsync dispatches through IImageObjectExtractorStatics's vtable slot 7.
func (self *IImageObjectExtractorStatics) CreateWithImageBufferAsync(imageBuffer *graphicsimaging.IImageBuffer) (*IAsyncOperationOfImageObjectExtractor, error) {
	result := new(*IAsyncOperationOfImageObjectExtractor)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(imageBuffer)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// GetReadyState dispatches through IImageObjectExtractorStatics's vtable slot 8.
func (self *IImageObjectExtractorStatics) GetReadyState() (windowsai.AIFeatureReadyState, error) {
	result := new(windowsai.AIFeatureReadyState)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// EnsureReadyAsync dispatches through IImageObjectExtractorStatics's vtable slot 9.
func (self *IImageObjectExtractorStatics) EnsureReadyAsync() (*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble, error) {
	result := new(*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageObjectRemover is the WinRT interface Microsoft.Windows.AI.Imaging.IImageObjectRemover.
// IID: cfa20faf-5ae1-5b8c-b0d8-e7c64db59d26
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageObjectRemover runtime class.
type IImageObjectRemover struct {
	syswinrt.IInspectable
}

// IID_IImageObjectRemover is the interface identifier for IImageObjectRemover.
var IID_IImageObjectRemover = win32.GUID{Data1: 0xcfa20faf, Data2: 0x5ae1, Data3: 0x5b8c, Data4: [8]byte{0xb0, 0xd8, 0xe7, 0xc6, 0x4d, 0xb5, 0x9d, 0x26}}

// RemoveFromSoftwareBitmap dispatches through IImageObjectRemover's vtable slot 6.
func (self *IImageObjectRemover) RemoveFromSoftwareBitmap(softwareBitmap *wrtgraphicsimaging.ISoftwareBitmap, softwareBitmapMask *wrtgraphicsimaging.ISoftwareBitmap) (*wrtgraphicsimaging.ISoftwareBitmap, error) {
	result := new(*wrtgraphicsimaging.ISoftwareBitmap)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(softwareBitmap)), uintptr(unsafe.Pointer(softwareBitmapMask)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RemoveFromImageBuffer dispatches through IImageObjectRemover's vtable slot 7.
func (self *IImageObjectRemover) RemoveFromImageBuffer(imageBuffer *graphicsimaging.IImageBuffer, imageBufferMask *graphicsimaging.IImageBuffer) (*graphicsimaging.IImageBuffer, error) {
	result := new(*graphicsimaging.IImageBuffer)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(imageBuffer)), uintptr(unsafe.Pointer(imageBufferMask)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageObjectRemoverStatics is the WinRT interface Microsoft.Windows.AI.Imaging.IImageObjectRemoverStatics.
// IID: cbcbd7e1-5b81-503f-8fcb-66ae1d6e5b9c
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageObjectRemover runtime class.
type IImageObjectRemoverStatics struct {
	syswinrt.IInspectable
}

// IID_IImageObjectRemoverStatics is the interface identifier for IImageObjectRemoverStatics.
var IID_IImageObjectRemoverStatics = win32.GUID{Data1: 0xcbcbd7e1, Data2: 0x5b81, Data3: 0x503f, Data4: [8]byte{0x8f, 0xcb, 0x66, 0xae, 0x1d, 0x6e, 0x5b, 0x9c}}

// GetReadyState dispatches through IImageObjectRemoverStatics's vtable slot 6.
func (self *IImageObjectRemoverStatics) GetReadyState() (windowsai.AIFeatureReadyState, error) {
	result := new(windowsai.AIFeatureReadyState)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// EnsureReadyAsync dispatches through IImageObjectRemoverStatics's vtable slot 7.
func (self *IImageObjectRemoverStatics) EnsureReadyAsync() (*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble, error) {
	result := new(*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateAsync dispatches through IImageObjectRemoverStatics's vtable slot 8.
func (self *IImageObjectRemoverStatics) CreateAsync() (*IAsyncOperationOfImageObjectRemover, error) {
	result := new(*IAsyncOperationOfImageObjectRemover)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageScaler is the WinRT interface Microsoft.Windows.AI.Imaging.IImageScaler.
// IID: 06eec88e-91c5-5326-8128-2807faafa571
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageScaler runtime class.
type IImageScaler struct {
	syswinrt.IInspectable
}

// IID_IImageScaler is the interface identifier for IImageScaler.
var IID_IImageScaler = win32.GUID{Data1: 0x06eec88e, Data2: 0x91c5, Data3: 0x5326, Data4: [8]byte{0x81, 0x28, 0x28, 0x07, 0xfa, 0xaf, 0xa5, 0x71}}

// ScaleSoftwareBitmap dispatches through IImageScaler's vtable slot 6.
func (self *IImageScaler) ScaleSoftwareBitmap(softwareBitmap *wrtgraphicsimaging.ISoftwareBitmap, width int32, height int32) (*wrtgraphicsimaging.ISoftwareBitmap, error) {
	result := new(*wrtgraphicsimaging.ISoftwareBitmap)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(softwareBitmap)), uintptr(width), uintptr(height), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ScaleImageBuffer dispatches through IImageScaler's vtable slot 7.
func (self *IImageScaler) ScaleImageBuffer(imageBuffer *graphicsimaging.IImageBuffer, width int32, height int32) (*graphicsimaging.IImageBuffer, error) {
	result := new(*graphicsimaging.IImageBuffer)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(imageBuffer)), uintptr(width), uintptr(height), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MaxSupportedScaleFactor (propget get_MaxSupportedScaleFactor) dispatches through IImageScaler's vtable slot 8.
func (self *IImageScaler) MaxSupportedScaleFactor() (int32, error) {
	result := new(int32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IImageScalerStatics is the WinRT interface Microsoft.Windows.AI.Imaging.IImageScalerStatics.
// IID: 75380c81-9c7f-544b-9337-6e638cfb464a
// Exclusive to the Microsoft.Windows.AI.Imaging.ImageScaler runtime class.
type IImageScalerStatics struct {
	syswinrt.IInspectable
}

// IID_IImageScalerStatics is the interface identifier for IImageScalerStatics.
var IID_IImageScalerStatics = win32.GUID{Data1: 0x75380c81, Data2: 0x9c7f, Data3: 0x544b, Data4: [8]byte{0x93, 0x37, 0x6e, 0x63, 0x8c, 0xfb, 0x46, 0x4a}}

// GetReadyState dispatches through IImageScalerStatics's vtable slot 6.
func (self *IImageScalerStatics) GetReadyState() (windowsai.AIFeatureReadyState, error) {
	result := new(windowsai.AIFeatureReadyState)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// EnsureReadyAsync dispatches through IImageScalerStatics's vtable slot 7.
func (self *IImageScalerStatics) EnsureReadyAsync() (*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble, error) {
	result := new(*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateAsync dispatches through IImageScalerStatics's vtable slot 8.
func (self *IImageScalerStatics) CreateAsync() (*IAsyncOperationOfImageScaler, error) {
	result := new(*IAsyncOperationOfImageScaler)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IRecognizedLine is the WinRT interface Microsoft.Windows.AI.Imaging.IRecognizedLine.
// IID: 612a6be6-f6bb-53c9-84ce-f0a5e565faa7
// Exclusive to the Microsoft.Windows.AI.Imaging.RecognizedLine runtime class.
type IRecognizedLine struct {
	syswinrt.IInspectable
}

// IID_IRecognizedLine is the interface identifier for IRecognizedLine.
var IID_IRecognizedLine = win32.GUID{Data1: 0x612a6be6, Data2: 0xf6bb, Data3: 0x53c9, Data4: [8]byte{0x84, 0xce, 0xf0, 0xa5, 0xe5, 0x65, 0xfa, 0xa7}}

// Text (propget get_Text) dispatches through IRecognizedLine's vtable slot 6.
func (self *IRecognizedLine) Text() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// BoundingBox (propget get_BoundingBox) dispatches through IRecognizedLine's vtable slot 7.
func (self *IRecognizedLine) BoundingBox() (RecognizedTextBoundingBox, error) {
	result := new(RecognizedTextBoundingBox)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// slot 8: get_Words skipped: conformant array

// Style (propget get_Style) dispatches through IRecognizedLine's vtable slot 9.
func (self *IRecognizedLine) Style() (RecognizedLineStyle, error) {
	result := new(RecognizedLineStyle)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[9], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// LineStyleConfidence (propget get_LineStyleConfidence) dispatches through IRecognizedLine's vtable slot 10.
func (self *IRecognizedLine) LineStyleConfidence() (float32, error) {
	result := new(float32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[10], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IRecognizedText is the WinRT interface Microsoft.Windows.AI.Imaging.IRecognizedText.
// IID: ae4766d3-2924-57a6-b3d3-b866f59b9972
// Exclusive to the Microsoft.Windows.AI.Imaging.RecognizedText runtime class.
type IRecognizedText struct {
	syswinrt.IInspectable
}

// IID_IRecognizedText is the interface identifier for IRecognizedText.
var IID_IRecognizedText = win32.GUID{Data1: 0xae4766d3, Data2: 0x2924, Data3: 0x57a6, Data4: [8]byte{0xb3, 0xd3, 0xb8, 0x66, 0xf5, 0x9b, 0x99, 0x72}}

// slot 6: get_Lines skipped: conformant array

// TextAngle (propget get_TextAngle) dispatches through IRecognizedText's vtable slot 7.
func (self *IRecognizedText) TextAngle() (float32, error) {
	result := new(float32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// IRecognizedWord is the WinRT interface Microsoft.Windows.AI.Imaging.IRecognizedWord.
// IID: 6b53daab-3410-5088-826a-0788a1ee3b52
// Exclusive to the Microsoft.Windows.AI.Imaging.RecognizedWord runtime class.
type IRecognizedWord struct {
	syswinrt.IInspectable
}

// IID_IRecognizedWord is the interface identifier for IRecognizedWord.
var IID_IRecognizedWord = win32.GUID{Data1: 0x6b53daab, Data2: 0x3410, Data3: 0x5088, Data4: [8]byte{0x82, 0x6a, 0x07, 0x88, 0xa1, 0xee, 0x3b, 0x52}}

// Text (propget get_Text) dispatches through IRecognizedWord's vtable slot 6.
func (self *IRecognizedWord) Text() (string, error) {
	result := new(syswinrt.HSTRING)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	if err := win32.ErrIfFailed(int32(r1)); err != nil {
		return "", err
	}
	return winrt.TakeHString(*result), nil
}

// BoundingBox (propget get_BoundingBox) dispatches through IRecognizedWord's vtable slot 7.
func (self *IRecognizedWord) BoundingBox() (RecognizedTextBoundingBox, error) {
	result := new(RecognizedTextBoundingBox)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// MatchConfidence (propget get_MatchConfidence) dispatches through IRecognizedWord's vtable slot 8.
func (self *IRecognizedWord) MatchConfidence() (float32, error) {
	result := new(float32)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextRecognizer is the WinRT interface Microsoft.Windows.AI.Imaging.ITextRecognizer.
// IID: be7bf6c0-30f6-570d-bd92-3ffe5665d933
// Exclusive to the Microsoft.Windows.AI.Imaging.TextRecognizer runtime class.
type ITextRecognizer struct {
	syswinrt.IInspectable
}

// IID_ITextRecognizer is the interface identifier for ITextRecognizer.
var IID_ITextRecognizer = win32.GUID{Data1: 0xbe7bf6c0, Data2: 0x30f6, Data3: 0x570d, Data4: [8]byte{0xbd, 0x92, 0x3f, 0xfe, 0x56, 0x65, 0xd9, 0x33}}

// RecognizeTextFromImageAsync dispatches through ITextRecognizer's vtable slot 6.
func (self *ITextRecognizer) RecognizeTextFromImageAsync(imageBuffer *graphicsimaging.IImageBuffer) (*IAsyncOperationOfRecognizedText, error) {
	result := new(*IAsyncOperationOfRecognizedText)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(imageBuffer)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// RecognizeTextFromImage dispatches through ITextRecognizer's vtable slot 7.
func (self *ITextRecognizer) RecognizeTextFromImage(imageBuffer *graphicsimaging.IImageBuffer) (*IRecognizedText, error) {
	result := new(*IRecognizedText)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(unsafe.Pointer(imageBuffer)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// ITextRecognizerStatics is the WinRT interface Microsoft.Windows.AI.Imaging.ITextRecognizerStatics.
// IID: 3788c2fd-e496-53ab-85a7-e54a135824e9
// Exclusive to the Microsoft.Windows.AI.Imaging.TextRecognizer runtime class.
type ITextRecognizerStatics struct {
	syswinrt.IInspectable
}

// IID_ITextRecognizerStatics is the interface identifier for ITextRecognizerStatics.
var IID_ITextRecognizerStatics = win32.GUID{Data1: 0x3788c2fd, Data2: 0xe496, Data3: 0x53ab, Data4: [8]byte{0x85, 0xa7, 0xe5, 0x4a, 0x13, 0x58, 0x24, 0xe9}}

// GetReadyState dispatches through ITextRecognizerStatics's vtable slot 6.
func (self *ITextRecognizerStatics) GetReadyState() (windowsai.AIFeatureReadyState, error) {
	result := new(windowsai.AIFeatureReadyState)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[6], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// EnsureReadyAsync dispatches through ITextRecognizerStatics's vtable slot 7.
func (self *ITextRecognizerStatics) EnsureReadyAsync() (*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble, error) {
	result := new(*IAsyncOperationWithProgressOfAIFeatureReadyResultAndDouble)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[7], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}

// CreateAsync dispatches through ITextRecognizerStatics's vtable slot 8.
func (self *ITextRecognizerStatics) CreateAsync() (*IAsyncOperationOfTextRecognizer, error) {
	result := new(*IAsyncOperationOfTextRecognizer)
	r1, _, _ := syscall.SyscallN(self.LpVtbl[8], uintptr(unsafe.Pointer(self)), uintptr(winrt.OutParam(unsafe.Pointer(result))))
	return *result, win32.ErrIfFailed(int32(r1))
}
