// Code generated by go-bindings-windowsappsdk-codegen. DO NOT EDIT.

//go:build windows && amd64

package media

import (
	"fmt"
)

// AlignmentX is Microsoft.UI.Xaml.Media.AlignmentX.
type AlignmentX int32

const (
	AlignmentXLeft   AlignmentX = 0
	AlignmentXCenter AlignmentX = 1
	AlignmentXRight  AlignmentX = 2
)

// String returns the AlignmentX constant's name, or its numeric form when
// the value is not a known constant.
func (e AlignmentX) String() string {
	switch e {
	case AlignmentXLeft:
		return "AlignmentXLeft"
	case AlignmentXCenter:
		return "AlignmentXCenter"
	case AlignmentXRight:
		return "AlignmentXRight"
	default:
		return fmt.Sprintf("AlignmentX(%d)", int32(e))
	}
}

// AlignmentY is Microsoft.UI.Xaml.Media.AlignmentY.
type AlignmentY int32

const (
	AlignmentYTop    AlignmentY = 0
	AlignmentYCenter AlignmentY = 1
	AlignmentYBottom AlignmentY = 2
)

// String returns the AlignmentY constant's name, or its numeric form when
// the value is not a known constant.
func (e AlignmentY) String() string {
	switch e {
	case AlignmentYTop:
		return "AlignmentYTop"
	case AlignmentYCenter:
		return "AlignmentYCenter"
	case AlignmentYBottom:
		return "AlignmentYBottom"
	default:
		return fmt.Sprintf("AlignmentY(%d)", int32(e))
	}
}

// BrushMappingMode is Microsoft.UI.Xaml.Media.BrushMappingMode.
type BrushMappingMode int32

const (
	BrushMappingModeAbsolute              BrushMappingMode = 0
	BrushMappingModeRelativeToBoundingBox BrushMappingMode = 1
)

// String returns the BrushMappingMode constant's name, or its numeric form when
// the value is not a known constant.
func (e BrushMappingMode) String() string {
	switch e {
	case BrushMappingModeAbsolute:
		return "BrushMappingModeAbsolute"
	case BrushMappingModeRelativeToBoundingBox:
		return "BrushMappingModeRelativeToBoundingBox"
	default:
		return fmt.Sprintf("BrushMappingMode(%d)", int32(e))
	}
}

// ColorInterpolationMode is Microsoft.UI.Xaml.Media.ColorInterpolationMode.
type ColorInterpolationMode int32

const (
	ColorInterpolationModeScRgbLinearInterpolation ColorInterpolationMode = 0
	ColorInterpolationModeSRgbLinearInterpolation  ColorInterpolationMode = 1
)

// String returns the ColorInterpolationMode constant's name, or its numeric form when
// the value is not a known constant.
func (e ColorInterpolationMode) String() string {
	switch e {
	case ColorInterpolationModeScRgbLinearInterpolation:
		return "ColorInterpolationModeScRgbLinearInterpolation"
	case ColorInterpolationModeSRgbLinearInterpolation:
		return "ColorInterpolationModeSRgbLinearInterpolation"
	default:
		return fmt.Sprintf("ColorInterpolationMode(%d)", int32(e))
	}
}

// ElementCompositeMode is Microsoft.UI.Xaml.Media.ElementCompositeMode.
type ElementCompositeMode int32

const (
	ElementCompositeModeInherit    ElementCompositeMode = 0
	ElementCompositeModeSourceOver ElementCompositeMode = 1
	ElementCompositeModeMinBlend   ElementCompositeMode = 2
)

// String returns the ElementCompositeMode constant's name, or its numeric form when
// the value is not a known constant.
func (e ElementCompositeMode) String() string {
	switch e {
	case ElementCompositeModeInherit:
		return "ElementCompositeModeInherit"
	case ElementCompositeModeSourceOver:
		return "ElementCompositeModeSourceOver"
	case ElementCompositeModeMinBlend:
		return "ElementCompositeModeMinBlend"
	default:
		return fmt.Sprintf("ElementCompositeMode(%d)", int32(e))
	}
}

// FastPlayFallbackBehaviour is Microsoft.UI.Xaml.Media.FastPlayFallbackBehaviour.
type FastPlayFallbackBehaviour int32

const (
	FastPlayFallbackBehaviourSkip    FastPlayFallbackBehaviour = 0
	FastPlayFallbackBehaviourHide    FastPlayFallbackBehaviour = 1
	FastPlayFallbackBehaviourDisable FastPlayFallbackBehaviour = 2
)

// String returns the FastPlayFallbackBehaviour constant's name, or its numeric form when
// the value is not a known constant.
func (e FastPlayFallbackBehaviour) String() string {
	switch e {
	case FastPlayFallbackBehaviourSkip:
		return "FastPlayFallbackBehaviourSkip"
	case FastPlayFallbackBehaviourHide:
		return "FastPlayFallbackBehaviourHide"
	case FastPlayFallbackBehaviourDisable:
		return "FastPlayFallbackBehaviourDisable"
	default:
		return fmt.Sprintf("FastPlayFallbackBehaviour(%d)", int32(e))
	}
}

// FillRule is Microsoft.UI.Xaml.Media.FillRule.
type FillRule int32

const (
	FillRuleEvenOdd FillRule = 0
	FillRuleNonzero FillRule = 1
)

// String returns the FillRule constant's name, or its numeric form when
// the value is not a known constant.
func (e FillRule) String() string {
	switch e {
	case FillRuleEvenOdd:
		return "FillRuleEvenOdd"
	case FillRuleNonzero:
		return "FillRuleNonzero"
	default:
		return fmt.Sprintf("FillRule(%d)", int32(e))
	}
}

// GradientSpreadMethod is Microsoft.UI.Xaml.Media.GradientSpreadMethod.
type GradientSpreadMethod int32

const (
	GradientSpreadMethodPad     GradientSpreadMethod = 0
	GradientSpreadMethodReflect GradientSpreadMethod = 1
	GradientSpreadMethodRepeat  GradientSpreadMethod = 2
)

// String returns the GradientSpreadMethod constant's name, or its numeric form when
// the value is not a known constant.
func (e GradientSpreadMethod) String() string {
	switch e {
	case GradientSpreadMethodPad:
		return "GradientSpreadMethodPad"
	case GradientSpreadMethodReflect:
		return "GradientSpreadMethodReflect"
	case GradientSpreadMethodRepeat:
		return "GradientSpreadMethodRepeat"
	default:
		return fmt.Sprintf("GradientSpreadMethod(%d)", int32(e))
	}
}

// LoadedImageSourceLoadStatus is Microsoft.UI.Xaml.Media.LoadedImageSourceLoadStatus.
type LoadedImageSourceLoadStatus int32

const (
	LoadedImageSourceLoadStatusSuccess       LoadedImageSourceLoadStatus = 0
	LoadedImageSourceLoadStatusNetworkError  LoadedImageSourceLoadStatus = 1
	LoadedImageSourceLoadStatusInvalidFormat LoadedImageSourceLoadStatus = 2
	LoadedImageSourceLoadStatusOther         LoadedImageSourceLoadStatus = 3
)

// String returns the LoadedImageSourceLoadStatus constant's name, or its numeric form when
// the value is not a known constant.
func (e LoadedImageSourceLoadStatus) String() string {
	switch e {
	case LoadedImageSourceLoadStatusSuccess:
		return "LoadedImageSourceLoadStatusSuccess"
	case LoadedImageSourceLoadStatusNetworkError:
		return "LoadedImageSourceLoadStatusNetworkError"
	case LoadedImageSourceLoadStatusInvalidFormat:
		return "LoadedImageSourceLoadStatusInvalidFormat"
	case LoadedImageSourceLoadStatusOther:
		return "LoadedImageSourceLoadStatusOther"
	default:
		return fmt.Sprintf("LoadedImageSourceLoadStatus(%d)", int32(e))
	}
}

// PenLineCap is Microsoft.UI.Xaml.Media.PenLineCap.
type PenLineCap int32

const (
	PenLineCapFlat     PenLineCap = 0
	PenLineCapSquare   PenLineCap = 1
	PenLineCapRound    PenLineCap = 2
	PenLineCapTriangle PenLineCap = 3
)

// String returns the PenLineCap constant's name, or its numeric form when
// the value is not a known constant.
func (e PenLineCap) String() string {
	switch e {
	case PenLineCapFlat:
		return "PenLineCapFlat"
	case PenLineCapSquare:
		return "PenLineCapSquare"
	case PenLineCapRound:
		return "PenLineCapRound"
	case PenLineCapTriangle:
		return "PenLineCapTriangle"
	default:
		return fmt.Sprintf("PenLineCap(%d)", int32(e))
	}
}

// PenLineJoin is Microsoft.UI.Xaml.Media.PenLineJoin.
type PenLineJoin int32

const (
	PenLineJoinMiter PenLineJoin = 0
	PenLineJoinBevel PenLineJoin = 1
	PenLineJoinRound PenLineJoin = 2
)

// String returns the PenLineJoin constant's name, or its numeric form when
// the value is not a known constant.
func (e PenLineJoin) String() string {
	switch e {
	case PenLineJoinMiter:
		return "PenLineJoinMiter"
	case PenLineJoinBevel:
		return "PenLineJoinBevel"
	case PenLineJoinRound:
		return "PenLineJoinRound"
	default:
		return fmt.Sprintf("PenLineJoin(%d)", int32(e))
	}
}

// Stretch is Microsoft.UI.Xaml.Media.Stretch.
type Stretch int32

const (
	StretchNone          Stretch = 0
	StretchFill          Stretch = 1
	StretchUniform       Stretch = 2
	StretchUniformToFill Stretch = 3
)

// String returns the Stretch constant's name, or its numeric form when
// the value is not a known constant.
func (e Stretch) String() string {
	switch e {
	case StretchNone:
		return "StretchNone"
	case StretchFill:
		return "StretchFill"
	case StretchUniform:
		return "StretchUniform"
	case StretchUniformToFill:
		return "StretchUniformToFill"
	default:
		return fmt.Sprintf("Stretch(%d)", int32(e))
	}
}

// StyleSimulations is Microsoft.UI.Xaml.Media.StyleSimulations.
type StyleSimulations int32

const (
	StyleSimulationsNone                 StyleSimulations = 0
	StyleSimulationsBoldSimulation       StyleSimulations = 1
	StyleSimulationsItalicSimulation     StyleSimulations = 2
	StyleSimulationsBoldItalicSimulation StyleSimulations = 3
)

// String returns the StyleSimulations constant's name, or its numeric form when
// the value is not a known constant.
func (e StyleSimulations) String() string {
	switch e {
	case StyleSimulationsNone:
		return "StyleSimulationsNone"
	case StyleSimulationsBoldSimulation:
		return "StyleSimulationsBoldSimulation"
	case StyleSimulationsItalicSimulation:
		return "StyleSimulationsItalicSimulation"
	case StyleSimulationsBoldItalicSimulation:
		return "StyleSimulationsBoldItalicSimulation"
	default:
		return fmt.Sprintf("StyleSimulations(%d)", int32(e))
	}
}

// SweepDirection is Microsoft.UI.Xaml.Media.SweepDirection.
type SweepDirection int32

const (
	SweepDirectionCounterclockwise SweepDirection = 0
	SweepDirectionClockwise        SweepDirection = 1
)

// String returns the SweepDirection constant's name, or its numeric form when
// the value is not a known constant.
func (e SweepDirection) String() string {
	switch e {
	case SweepDirectionCounterclockwise:
		return "SweepDirectionCounterclockwise"
	case SweepDirectionClockwise:
		return "SweepDirectionClockwise"
	default:
		return fmt.Sprintf("SweepDirection(%d)", int32(e))
	}
}
